import { NextResponse } from "next/server";
import { getSession, isDemoUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { ensureSchema } from "@/lib/db/migrate";
import { logAudit } from "@/lib/audit";
import { ingestPdfFile, ingestDnaForUser, ingestImageFile } from "@/lib/ingest";
import path from "node:path";
import { writeFile, mkdir } from "node:fs/promises";

async function pdfParse(buf: Buffer): Promise<string> {
  try {
    const mod = (await import("pdf-parse")) as unknown as { default: (b: Buffer) => Promise<{ text: string }> };
    const fn = (mod as { default?: (b: Buffer) => Promise<{ text: string }> }).default ?? (mod as unknown as (b: Buffer) => Promise<{ text: string }>);
    const r = await fn(buf);
    return (r?.text ?? "").slice(0, 8000);
  } catch { return ""; }
}

const BLOOD_TEST_MARKERS = /\b(cholest[ée]rol|hdl|ldl|trigly|h[ée]moglobin|h[ée]matocr|leucocyt|plaquett|cr[ée]atinin|gly[cé]mie|hba1c|insulin[ea]|tsh|t3 ?libre|t4 ?libre|alat|asat|gamma ?gt|ggt|ferritin|fer ?s[ée]rique|transferrin|crp|hscrp|magn[ée]sium|vitamin[ea]? ?d|vitamin[ea]? ?b12|folate|homocyst[ée]in|testost[ée]ron|oestradiol|cortisol|dhea|igf-?1|apolipoprot[ée]in|apo ?b|apo ?a|lp\(?a\)?)\b/i;


export const runtime = "nodejs";
export const maxDuration = 300;

const DATA_ROOT = path.join(process.cwd(), "data");

type DetectKind =
  | "whoop-cycles" | "whoop-sleep" | "whoop-workouts" | "whoop-journal"
  | "oura-trends" | "generic-csv"
  | "dna-23andme" | "pdf-document" | "image" | "markdown-note"
  | "spreadsheet" | "unknown";

type DetectResult = { kind: DetectKind; folder?: string; reason: string };

function sniff(filename: string, head: string): DetectResult {
  const f = filename.toLowerCase();
  const t = head.toLowerCase();

  // Whoop FR
  if (/score de récupération|score de recuperation/.test(t) && /variabilité de la fréquence cardiaque|variabilite de la frequence cardiaque/.test(t))
    return { kind: "whoop-cycles", reason: "Whoop · cycles physiologiques (FR)" };
  if (/performance sommeil/.test(t) && /durée du sommeil paradoxal/.test(t) && !/score de récupération/.test(t))
    return { kind: "whoop-sleep", reason: "Whoop · sommeil (FR)" };
  if (/nom de l'activité|nom de l.activite/.test(t) && /zone fc/.test(t))
    return { kind: "whoop-workouts", reason: "Whoop · entraînements (FR)" };
  if (/texte de la question/.test(t) && /a répondu oui|a repondu oui/.test(t))
    return { kind: "whoop-journal", reason: "Whoop · journal entries (FR)" };

  // Whoop EN
  if (/recovery score/.test(t) && /heart rate variability/.test(t))
    return { kind: "whoop-cycles", reason: "Whoop · physiological cycles (EN)" };
  if (/sleep performance|sleep score/.test(t) && /rem sleep/.test(t) && !/recovery/.test(t))
    return { kind: "whoop-sleep", reason: "Whoop · sleeps (EN)" };

  // Oura
  if (/readiness score/.test(t) || (/^date,/.test(head.toLowerCase()) && /average resting heart rate/.test(t)))
    return { kind: "oura-trends", reason: "Oura · trends" };

  // 23andMe / AncestryDNA raw genome (.txt or .zip).
  // The "# rsid chromosome position genotype" header sits AFTER ~20 comment
  // lines ("# This data file generated by 23andMe at: ..."), so the old
  // ^-anchored regexes never matched and the file fell through to
  // markdown-note. We scan the whole head for a content signature, and match
  // the filename too — 23andMe exports are named genome_<Name>_v5_Full_*.txt,
  // which don't contain the literal "23andme".
  const genomeByContent =
    /generated by 23andMe/i.test(head) ||
    /\brsid\s+chromosome\s+position\s+(genotype|allele)/i.test(head) ||
    /(^|\n)\s*(rs|i)\d+\t[0-9XYMT]+\t\d+\t[ACGTDI-]{1,2}\b/i.test(head);
  const genomeByName = /23andme|ancestrydna|genome[_-].*\.(txt|zip)$/i.test(f);
  if (genomeByContent || genomeByName)
    return { kind: "dna-23andme", reason: "23andMe · raw genome" };

  // PDFs
  if (f.endsWith(".pdf")) {
    if (/sang|biol|labo|analys|h[ée]matol|nfs|bilan/.test(f)) return { kind: "pdf-document", folder: "analyses-sang", reason: "PDF · analyse sanguine" };
    if (/consult|visit|cabinet|rapport.*m[ée]decin|cr_/.test(f)) return { kind: "pdf-document", folder: "consultations", reason: "PDF · consultation" };
    if (/dna|gene|genetic|adn/.test(f)) return { kind: "pdf-document", folder: "genetique", reason: "PDF · génétique" };
    if (/oeil|ophtalm|eye|retin|vision/.test(f)) return { kind: "pdf-document", folder: "ophtalmologie", reason: "PDF · ophtalmologie" };
    if (/imager|irm|scanner|radio|echo/.test(f)) return { kind: "pdf-document", folder: "imagerie", reason: "PDF · imagerie médicale" };
    if (/sha[\s-]?wellness|cure|retraite/.test(f)) return { kind: "pdf-document", folder: "sha-wellness-clinic", reason: "PDF · SHA Wellness" };
    return { kind: "pdf-document", folder: "divers", reason: "PDF · à classer" };
  }

  if (/\.(jpe?g|png|webp|heic|gif|bmp|tif)$/i.test(f)) return { kind: "image", folder: "divers", reason: "Image · divers" };
  if (/\.(md|txt)$/i.test(f)) return { kind: "markdown-note", reason: "Note texte/markdown" };
  if (/\.(xlsx?|ods)$/i.test(f)) return { kind: "spreadsheet", folder: "divers", reason: "Tableur (à classer)" };
  if (f.endsWith(".csv")) return { kind: "generic-csv", reason: "CSV générique" };
  return { kind: "unknown", reason: "Type inconnu" };
}

// ---- Wearable parsers ----
type Row = { date: string; source: string; kind: string; value: number; unit?: string };

const WHOOP_FR_PATTERNS: Array<{ rx: RegExp; kind: string; unit?: string }> = [
  { rx: /score de récupération|score de recuperation/i, kind: "recovery", unit: "%" },
  { rx: /fréquence cardiaque au repos|frequence cardiaque au repos/i, kind: "rhr", unit: "bpm" },
  { rx: /variabilité de la fréquence cardiaque|variabilite de la frequence cardiaque/i, kind: "hrv", unit: "ms" },
  { rx: /température cutanée|temperature cutanee/i, kind: "skin_temp", unit: "°C" },
  { rx: /niveau d'oxygène|niveau d.oxygene/i, kind: "spo2", unit: "%" },
  { rx: /effort du jour/i, kind: "strain_day", unit: "score" },
  { rx: /effort activité|effort activite/i, kind: "strain_workout", unit: "score" },
  { rx: /dépense énergétique|depense energetique/i, kind: "energy_kcal", unit: "kcal" },
  { rx: /performance sommeil/i, kind: "sleep_score", unit: "%" },
  { rx: /fréquence respiratoire|frequence respiratoire/i, kind: "respiratory_rate", unit: "rpm" },
  { rx: /durée du sommeil léger|duree du sommeil leger/i, kind: "sleep_light_min", unit: "min" },
  { rx: /durée du sommeil profond|duree du sommeil profond/i, kind: "sleep_deep_min", unit: "min" },
  { rx: /durée du sommeil paradoxal|duree du sommeil paradoxal/i, kind: "sleep_rem_min", unit: "min" },
  { rx: /^durée du sommeil( |$)|^duree du sommeil( |$)|durée du sommeil \(min\)/i, kind: "sleep_total_min", unit: "min" },
  { rx: /temps passé au lit|temps passe au lit/i, kind: "time_in_bed_min", unit: "min" },
  { rx: /temps d'éveil|temps d.eveil/i, kind: "sleep_awake_min", unit: "min" },
  { rx: /efficacité du sommeil|efficacite du sommeil/i, kind: "sleep_efficiency", unit: "%" },
  { rx: /régularité du sommeil|regularite du sommeil/i, kind: "sleep_regularity", unit: "%" },
  { rx: /dette de sommeil/i, kind: "sleep_debt_min", unit: "min" },
  { rx: /besoins en sommeil/i, kind: "sleep_need_min", unit: "min" },
  { rx: /fc max/i, kind: "hr_max", unit: "bpm" },
  { rx: /fc moyenne/i, kind: "hr_avg", unit: "bpm" },
  { rx: /durée \(min\)|duree \(min\)/i, kind: "workout_duration_min", unit: "min" },
];

// Strip BOM and invisible markers (Whoop exports include U+FEFF)
function clean(s: string): string { return s.replace(/^﻿/, "").trim(); }

function splitCsvLine(line: string): string[] {
  // Whoop uses comma but no quoted commas in numeric data; quoted values are simple. Simple parser:
  const out: string[] = [];
  let cur = ""; let inQ = false;
  for (let i = 0; i < line.length; i++) {
    const c = line[i];
    if (c === '"') { inQ = !inQ; continue; }
    if (c === "," && !inQ) { out.push(cur); cur = ""; continue; }
    cur += c;
  }
  out.push(cur);
  return out;
}

function parseDate(raw: string): string | null {
  if (!raw) return null;
  const m = raw.match(/(\d{4})-(\d{2})-(\d{2})/);
  return m ? `${m[1]}-${m[2]}-${m[3]}` : null;
}

function parseWhoopFr(text: string, _kind: DetectKind): Row[] {
  const lines = clean(text).split(/\r?\n/).filter(Boolean);
  if (lines.length < 2) return [];
  const headers = splitCsvLine(lines[0]).map((h) => clean(h));
  const dateIdx = headers.findIndex((h) => /heure de début du cycle|cycle start time/i.test(h));
  if (dateIdx < 0) return [];
  const fields = headers.map((h) => WHOOP_FR_PATTERNS.find((p) => p.rx.test(h)));
  const out: Row[] = [];
  for (let i = 1; i < lines.length; i++) {
    const cells = splitCsvLine(lines[i]);
    const date = parseDate(cells[dateIdx] ?? "");
    if (!date) continue;
    for (let j = 0; j < cells.length; j++) {
      const f = fields[j];
      if (!f) continue;
      const v = parseFloat(cells[j].replace(",", "."));
      if (!Number.isFinite(v)) continue;
      out.push({ date, source: "whoop", kind: f.kind, value: v, unit: f.unit });
    }
  }
  return out;
}

function parseGenericCsv(text: string, source: string): Row[] {
  const lines = clean(text).split(/\r?\n/).filter(Boolean);
  if (lines.length < 2) return [];
  const headers = splitCsvLine(lines[0]).map((h) => clean(h).toLowerCase());
  const dateIdx = headers.findIndex((h) => /date|day|jour/.test(h));
  if (dateIdx < 0) return [];
  const out: Row[] = [];
  for (let i = 1; i < lines.length; i++) {
    const cells = splitCsvLine(lines[i]);
    const date = parseDate(cells[dateIdx] ?? "");
    if (!date) continue;
    for (let j = 0; j < cells.length; j++) {
      if (j === dateIdx) continue;
      const v = parseFloat(cells[j].replace(",", "."));
      if (!Number.isFinite(v)) continue;
      out.push({ date, source, kind: headers[j].replace(/\s+/g, "_").slice(0, 60), value: v });
    }
  }
  return out;
}

/** Per-user data root: data/u/<userId>/. Keeps each account's files (and the
 * globally-unique document.path) isolated on disk. */
function userDataRoot(userId: number): string {
  return path.join(DATA_ROOT, "u", String(userId));
}

async function saveBinary(userId: number, folder: string, filename: string, buf: ArrayBuffer): Promise<string> {
  const dir = path.join(userDataRoot(userId), folder);
  await mkdir(dir, { recursive: true });
  // Avoid collisions: prefix with date if file already exists conceptually
  const safeName = filename.replace(/[^\w.\-_éèàâêîôûäëïöüç ()]/g, "_");
  const target = path.join(dir, safeName);
  await writeFile(target, Buffer.from(buf));
  return target;
}

function ensureWearableTable() {
  const sqlite = db().$client;
  sqlite.exec(`CREATE TABLE IF NOT EXISTS wearable_metric (id INTEGER PRIMARY KEY AUTOINCREMENT, date TEXT NOT NULL, source TEXT NOT NULL, kind TEXT NOT NULL, value REAL NOT NULL, unit TEXT, user_id INTEGER DEFAULT 1, UNIQUE(date, source, kind, user_id))`);
}

function insertWearables(rows: Row[], userId: number): number {
  if (rows.length === 0) return 0;
  ensureWearableTable();
  const sqlite = db().$client;
  const stmt = sqlite.prepare(`INSERT OR REPLACE INTO wearable_metric (date, source, kind, value, unit, user_id) VALUES (?, ?, ?, ?, ?, ?)`);
  const tx = sqlite.transaction((items: Row[]) => { for (const r of items) stmt.run(r.date, r.source, r.kind, r.value, r.unit ?? null, userId); });
  tx(rows);
  return rows.length;
}

type FileResult = {
  filename: string;
  size: number;
  detected: DetectKind;
  reason: string;
  status: "ok" | "skipped" | "error";
  message: string;
  inserted?: number;
  destination?: string;
};

export async function POST(req: Request) {
  const s = await getSession();
  if (!s) return NextResponse.json({ error: "unauthorized" }, { status: 401 });
  if (isDemoUser(s.userId)) return NextResponse.json({ error: "Mode démo en lecture seule. Crée un compte pour modifier." }, { status: 403 });
  ensureSchema();

  const fd = await req.formData();
  const files = fd.getAll("files") as File[];
  if (files.length === 0) return NextResponse.json({ error: "no files" }, { status: 400 });

  const results: FileResult[] = [];

  for (const f of files) {
    const filename = f.name;
    const size = f.size;
    let detected: DetectKind = "unknown";
    let reason = "";
    let folder: string | undefined;
    try {
      const isText = /\.(csv|txt|md|tsv)$/i.test(filename);
      let head = "";
      if (isText) {
        const buf = await f.slice(0, 8000).arrayBuffer();
        head = clean(new TextDecoder("utf-8").decode(buf));
      }
      const det = sniff(filename, head);
      detected = det.kind; reason = det.reason; folder = det.folder;

      if (detected.startsWith("whoop")) {
        const text = await f.text();
        let rows: Row[] = [];
        if (detected === "whoop-cycles" || detected === "whoop-sleep" || detected === "whoop-workouts") {
          rows = parseWhoopFr(text, detected);
        } else if (detected === "whoop-journal") {
          // Skip for v1 (free-text questions, no good fit yet)
          results.push({ filename, size, detected, reason, status: "skipped", message: "Journal entries non importés (v1)" });
          continue;
        }
        const inserted = insertWearables(rows, s.userId);
        results.push({ filename, size, detected, reason, status: "ok", message: `${inserted} mesures insérées`, inserted });
      } else if (detected === "oura-trends") {
        const text = await f.text();
        const rows = parseGenericCsv(text, "oura"); // headers cover most kinds
        const inserted = insertWearables(rows, s.userId);
        results.push({ filename, size, detected, reason, status: "ok", message: `${inserted} mesures insérées`, inserted });
      } else if (detected === "generic-csv") {
        const text = await f.text();
        const rows = parseGenericCsv(text, "generic");
        const inserted = insertWearables(rows, s.userId);
        results.push({ filename, size, detected, reason, status: "ok", message: `${inserted} mesures insérées`, inserted });
      } else if (detected === "pdf-document" || detected === "image" || detected === "spreadsheet" || detected === "dna-23andme") {
        let targetFolder = detected === "dna-23andme" ? "genetique" : (folder ?? "divers");
        let bloodSwitched = false;
        const buf = await f.arrayBuffer();
        // Content-based blood test detection on PDFs that landed in divers/ — move to analyses-sang if it looks like a lab
        if (detected === "pdf-document" && targetFolder === "divers") {
          const peek = await pdfParse(Buffer.from(buf));
          if (peek && BLOOD_TEST_MARKERS.test(peek)) {
            targetFolder = "analyses-sang";
            bloodSwitched = true;
            reason = "PDF · analyse sanguine (détecté par contenu)";
          }
        }
        const dest = await saveBinary(s.userId, targetFolder, filename, buf);
        // Ingest inline with the uploader's userId: the data lands in THEIR
        // account and is queryable immediately (the welcome wizard calls
        // auto-extract right after this returns). No detached global ingest.
        let extra = "";
        if (detected === "pdf-document") {
          const res = await ingestPdfFile(dest, s.userId, targetFolder, { useLlm: true });
          extra = res.biomarkers > 0 ? ` · ${res.biomarkers} biomarqueurs extraits` : "";
        } else if (detected === "image") {
          // A photographed lab result → read it with Claude vision. If markers
          // come back, treat it as a blood panel; otherwise it stays a plain image.
          const res = await ingestImageFile(dest, s.userId, "analyses-sang");
          if (res.biomarkers > 0) { extra = ` · ${res.biomarkers} biomarqueurs extraits de ta photo`; reason = "Image · analyse sanguine (photo)"; }
        } else if (detected === "dna-23andme") {
          const res = await ingestDnaForUser(s.userId, userDataRoot(s.userId));
          extra = ` · ${res.insights} insights ADN`;
        }
        const msg = bloodSwitched
          ? `Analyse sanguine détectée — importée${extra}.`
          : `Importé${extra}.`;
        results.push({ filename, size, detected, reason, status: "ok", message: msg, destination: dest });
      } else if (detected === "markdown-note") {
        const buf = await f.arrayBuffer();
        const dest = await saveBinary(s.userId, "knowledge-base", filename, buf);
        results.push({ filename, size, detected, reason, status: "ok", message: "Sauvegardé dans la knowledge base.", destination: dest });
      } else {
        const buf = await f.arrayBuffer();
        const dest = await saveBinary(s.userId, "divers", filename, buf);
        results.push({ filename, size, detected, reason, status: "ok", message: "Type inconnu — sauvegardé dans divers/", destination: dest });
      }
    } catch (e) {
      results.push({ filename, size, detected, reason, status: "error", message: (e as Error).message });
    }
  }

  logAudit("upload-auto", `files=${files.length} user=${s.userId}`, req);
  return NextResponse.json({ results });
}
