/**
 * Curated DNA insight catalog. Sources: SNPedia (CC-BY-SA 3.0), ClinVar, dbSNP, peer-reviewed lit.
 * 130+ entries covering 10 categories. Magnitude 1=minor, 2=moderate, 3=strong, 4=major.
 * Risk genotypes use sorted alleles (e.g. "AT" not "TA"). Empty array = informational only.
 */

export type CatalogEntry = {
  rsid: string;
  category: "cardiovascular" | "metabolism" | "longevity" | "nutrition" | "fitness" | "cognitive" | "hormones" | "immunity" | "detox" | "carriers";
  trait: string;
  riskGenotypes: string[];
  effect?: string;
  summary: string;
  source: string;
  magnitude?: number;
};

export const CATALOG: CatalogEntry[] = [
  // ============================ LONGEVITY (15) ============================
  { rsid: "rs429358", category: "longevity", trait: "APOE — Alzheimer / longévité", riskGenotypes: ["CC", "CT"], magnitude: 4,
    effect: "L'allèle C (ε4) augmente le risque d'Alzheimer et de maladies cardiovasculaires.",
    summary: "Le SNP le plus important pour le risque d'Alzheimer tardif. ε4/ε4 multiplie le risque par ~10. ε2 protège.",
    source: "https://www.snpedia.com/index.php/Rs429358" },
  { rsid: "rs7412", category: "longevity", trait: "APOE — variant ε2 protecteur", riskGenotypes: ["CC"], magnitude: 2,
    effect: "Combiné à rs429358, détermine ε2/ε3/ε4. Allèle T = ε2 (protecteur).",
    summary: "rs7412(T) avec rs429358(T) = ε2, longévité accrue, cholestérol plus bas.",
    source: "https://www.snpedia.com/index.php/Rs7412" },
  { rsid: "rs2802292", category: "longevity", trait: "FOXO3 — longévité extrême", riskGenotypes: ["TT"], magnitude: 2,
    effect: "Allèle G associé à longévité accrue chez les centenaires.",
    summary: "Un des rares SNPs validés pour la longévité humaine extrême. Effet via résistance au stress oxydatif.",
    source: "https://www.snpedia.com/index.php/Rs2802292" },
  { rsid: "rs1042522", category: "longevity", trait: "TP53 codon 72 (Arg/Pro)", riskGenotypes: ["GG"], magnitude: 1,
    effect: "Pro/Pro (GG) = longévité légèrement accrue mais réponse apoptotique réduite.",
    summary: "Trade-off cancer/longévité. Pro = longévité, Arg = meilleure réponse anti-tumorale.",
    source: "https://www.snpedia.com/index.php/Rs1042522" },
  { rsid: "rs9536314", category: "longevity", trait: "KLOTHO KL-VS — vieillissement", riskGenotypes: [], magnitude: 2,
    effect: "Hétérozygotie KL-VS associée à longévité, meilleure cognition, moins d'AVC.",
    summary: "Klotho régule le métabolisme du phosphate et la signalisation insuline. Variant rare protecteur.",
    source: "https://www.snpedia.com/index.php/Rs9536314" },
  { rsid: "rs1556516", category: "longevity", trait: "CDKN2B-AS1 — sénescence cellulaire", riskGenotypes: ["GG"], magnitude: 1,
    effect: "Variant lié au locus 9p21 (sénescence + risque cardio).",
    summary: "Région INK4/ARF, régulateur clé de la sénescence cellulaire.",
    source: "https://www.snpedia.com/index.php/Rs1556516" },
  { rsid: "rs2811712", category: "longevity", trait: "CDKN2A — sénescence", riskGenotypes: ["AA"], magnitude: 1,
    effect: "Influence p16INK4a et la sénescence cellulaire.",
    summary: "Marqueur de senescent cell burden. Variant majeur du locus 9p21.",
    source: "https://www.snpedia.com/index.php/Rs2811712" },
  { rsid: "rs7762395", category: "longevity", trait: "Télomères TERT — longueur télomérique", riskGenotypes: [], magnitude: 1,
    effect: "Influence l'activité télomérase et la longueur télomérique de base.",
    summary: "TERT = sous-unité catalytique de la télomérase. Lien avec longévité, cancer, fibrose pulmonaire.",
    source: "https://www.snpedia.com/index.php/TERT" },
  { rsid: "rs2736100", category: "longevity", trait: "TERT — gliomes / longueur télomères", riskGenotypes: ["CC"], magnitude: 1,
    effect: "Allèle C augmente l'expression télomérase et la longueur télomérique mais aussi le risque de gliome.",
    summary: "Trade-off télomères/cancer.",
    source: "https://www.snpedia.com/index.php/Rs2736100" },
  { rsid: "rs10936599", category: "longevity", trait: "TERC — longueur télomères", riskGenotypes: ["CC"], magnitude: 1,
    effect: "Allèle T associé à des télomères plus courts.",
    summary: "TERC = composante ARN de la télomérase.",
    source: "https://www.snpedia.com/index.php/Rs10936599" },
  { rsid: "rs1800629", category: "longevity", trait: "TNF-α -308G/A — inflammaging", riskGenotypes: ["AA", "AG"], magnitude: 2,
    effect: "Allèle A augmente l'expression TNF-α, inflammation chronique.",
    summary: "Inflammaging = inflammation chronique de bas grade qui accélère le vieillissement.",
    source: "https://www.snpedia.com/index.php/Rs1800629" },
  { rsid: "rs1800795", category: "longevity", trait: "IL-6 -174G/C — inflammation", riskGenotypes: ["GG"], magnitude: 2,
    effect: "Allèle G augmente l'expression IL-6.",
    summary: "Marqueur d'inflammation chronique. IL-6 élevée = vieillissement accéléré.",
    source: "https://www.snpedia.com/index.php/Rs1800795" },
  { rsid: "rs7041", category: "longevity", trait: "GC (DBP) — transport vitamine D", riskGenotypes: ["GG"], magnitude: 2,
    effect: "Allèle G = transport vitamine D moins efficace, taux 25(OH)D plus bas.",
    summary: "Determines vitamin D binding protein function. Influence le statut vitamine D actif.",
    source: "https://www.snpedia.com/index.php/Rs7041" },
  { rsid: "rs4880", category: "longevity", trait: "SOD2 Val16Ala — stress oxydatif", riskGenotypes: ["TT"], magnitude: 2,
    effect: "T (Val) = SOD2 mitochondriale moins active, plus de stress oxydatif.",
    summary: "Superoxyde dismutase mitochondriale. Variant majeur pour la défense antioxydante.",
    source: "https://www.snpedia.com/index.php/Rs4880" },
  { rsid: "rs1799782", category: "longevity", trait: "XRCC1 — réparation ADN", riskGenotypes: ["TT"], magnitude: 1,
    effect: "T = capacité de réparation ADN réduite.",
    summary: "Réparation par excision de bases. Variant lié au risque de cancer et au vieillissement cellulaire.",
    source: "https://www.snpedia.com/index.php/Rs1799782" },

  // ============================ CARDIOVASCULAR (18) ============================
  { rsid: "rs10757274", category: "cardiovascular", trait: "9p21 — risque coronarien", riskGenotypes: ["GG"], magnitude: 2,
    effect: "GG augmente le risque d'infarctus du myocarde de ~30%.",
    summary: "Région 9p21 = signal GWAS le plus fort pour la maladie coronarienne. Effet indépendant des lipides.",
    source: "https://www.snpedia.com/index.php/Rs10757274" },
  { rsid: "rs1333049", category: "cardiovascular", trait: "9p21 — confirmation coronaire", riskGenotypes: ["CC"], magnitude: 2,
    effect: "C augmente le risque coronarien (~25%/allèle).",
    summary: "SNP de confirmation du locus 9p21. À combiner avec rs10757274.",
    source: "https://www.snpedia.com/index.php/Rs1333049" },
  { rsid: "rs6025", category: "cardiovascular", trait: "Facteur V Leiden — thrombose", riskGenotypes: ["AA", "AG"], magnitude: 4,
    effect: "Allèle A = mutation Leiden. Risque de thrombose veineuse 5-10x (hétéro), 50-80x (homo).",
    summary: "Mutation thrombophile la plus commune. Vigilance avec contraceptifs œstrogéniques, immobilisation, vols longs.",
    source: "https://www.snpedia.com/index.php/Rs6025" },
  { rsid: "rs1799963", category: "cardiovascular", trait: "Prothrombine G20210A — thrombose", riskGenotypes: ["AA", "AG"], magnitude: 3,
    effect: "Allèle A augmente le risque de thrombose veineuse 2-3x (hétéro).",
    summary: "Deuxième mutation thrombophile la plus fréquente. Cumulé avec FVL = risque majoré.",
    source: "https://www.snpedia.com/index.php/Rs1799963" },
  { rsid: "rs5918", category: "cardiovascular", trait: "ITGB3 PlA1/A2 — résistance aspirine", riskGenotypes: ["CC", "CT"], magnitude: 2,
    effect: "C (PlA2) = résistance partielle à l'aspirine et risque thrombose accru.",
    summary: "Polymorphisme du récepteur GPIIIa des plaquettes. Influence l'efficacité de l'aspirine.",
    source: "https://www.snpedia.com/index.php/Rs5918" },
  { rsid: "rs10455872", category: "cardiovascular", trait: "Lp(a) — lipoprotéine(a) élevée", riskGenotypes: ["AG", "GG"], magnitude: 3,
    effect: "G augmente Lp(a) et le risque coronarien indépendamment du LDL.",
    summary: "Lp(a) est génétiquement déterminée à >90%. Mesurer une fois suffit. Pas de traitement spécifique sauf statines + niacine.",
    source: "https://www.snpedia.com/index.php/Rs10455872" },
  { rsid: "rs3798220", category: "cardiovascular", trait: "Lp(a) — variant majeur", riskGenotypes: ["CT", "TT"], magnitude: 3,
    effect: "T augmente Lp(a) significativement.",
    summary: "Second SNP majeur du locus LPA. Souvent combiné à rs10455872.",
    source: "https://www.snpedia.com/index.php/Rs3798220" },
  { rsid: "rs662", category: "cardiovascular", trait: "PON1 Q192R — détoxification organophosphorés", riskGenotypes: ["AA"], magnitude: 1,
    effect: "AA = activité paraoxonase réduite, sensibilité accrue aux pesticides.",
    summary: "Influence la sensibilité aux organophosphorés et le risque cardiovasculaire (HDL antioxydant).",
    source: "https://www.snpedia.com/index.php/Rs662" },
  { rsid: "rs4977574", category: "cardiovascular", trait: "9p21 — IDM", riskGenotypes: ["GG"], magnitude: 2,
    effect: "GG augmente le risque d'IDM précoce.",
    summary: "Variant 9p21 confirmant le risque coronarien.",
    source: "https://www.snpedia.com/index.php/Rs4977574" },
  { rsid: "rs2228671", category: "cardiovascular", trait: "LDLR — sensibilité statines", riskGenotypes: ["CC"], magnitude: 1,
    effect: "T = LDL plus bas naturellement, meilleure réponse aux statines.",
    summary: "Variant du récepteur LDL. Influence le LDL basal et la réponse thérapeutique.",
    source: "https://www.snpedia.com/index.php/Rs2228671" },
  { rsid: "rs5174", category: "cardiovascular", trait: "LRP8 (ApoER2) — IDM précoce", riskGenotypes: ["AA"], magnitude: 1,
    effect: "Allèle A associé à IDM précoce dans certaines populations.",
    summary: "Récepteur des apolipoprotéines impliqué dans signalisation Reelin et inflammation.",
    source: "https://www.snpedia.com/index.php/Rs5174" },
  { rsid: "rs2107595", category: "cardiovascular", trait: "HDAC9 — AVC ischémique", riskGenotypes: ["AA"], magnitude: 1,
    effect: "A augmente le risque d'AVC ischémique de grandes artères.",
    summary: "HDAC9 régule l'inflammation vasculaire. Cible thérapeutique émergente.",
    source: "https://www.snpedia.com/index.php/Rs2107595" },
  { rsid: "rs1746048", category: "cardiovascular", trait: "CXCL12 — coronaire", riskGenotypes: ["CC"], magnitude: 1,
    effect: "C augmente le risque coronarien.",
    summary: "Locus 10q11. CXCL12 = chemokine pro-athérogène.",
    source: "https://www.snpedia.com/index.php/Rs1746048" },
  { rsid: "rs17228212", category: "cardiovascular", trait: "SMAD3 — coronaire", riskGenotypes: ["CC"], magnitude: 1,
    effect: "C augmente le risque coronarien.",
    summary: "SMAD3 = signalisation TGF-β, fibrose vasculaire.",
    source: "https://www.snpedia.com/index.php/Rs17228212" },
  { rsid: "rs599839", category: "cardiovascular", trait: "PSRC1/SORT1 — LDL", riskGenotypes: ["GG"], magnitude: 2,
    effect: "G augmente le LDL et le risque coronarien.",
    summary: "Locus 1p13. SORT1 module la sécrétion VLDL hépatique.",
    source: "https://www.snpedia.com/index.php/Rs599839" },
  { rsid: "rs5882", category: "cardiovascular", trait: "CETP I405V — HDL & longévité", riskGenotypes: [], magnitude: 1,
    effect: "GG (Val/Val) = CETP réduite, HDL plus élevé, longévité accrue (Ashkenazes).",
    summary: "CETP transfère les esters de cholestérol entre HDL et VLDL/LDL. Variants protecteurs.",
    source: "https://www.snpedia.com/index.php/Rs5882" },
  { rsid: "rs3764261", category: "cardiovascular", trait: "CETP — niveaux HDL", riskGenotypes: ["GG"], magnitude: 2,
    effect: "T augmente le HDL.",
    summary: "Variant majeur GWAS pour le HDL.",
    source: "https://www.snpedia.com/index.php/Rs3764261" },
  { rsid: "rs1800775", category: "cardiovascular", trait: "CETP -629 — HDL & risque", riskGenotypes: ["CC"], magnitude: 1,
    effect: "A = HDL plus élevé.",
    summary: "Promoter polymorphism modifiant l'expression CETP.",
    source: "https://www.snpedia.com/index.php/Rs1800775" },

  // ============================ METABOLISM (18) ============================
  { rsid: "rs9939609", category: "metabolism", trait: "FTO — obésité", riskGenotypes: ["AA", "AT"], magnitude: 3,
    effect: "Allèle A augmente le risque d'obésité de 20-30% par allèle.",
    summary: "Le SNP le mieux établi pour l'obésité. Effet largement compensé par l'exercice régulier.",
    source: "https://www.snpedia.com/index.php/Rs9939609" },
  { rsid: "rs7903146", category: "metabolism", trait: "TCF7L2 — diabète T2", riskGenotypes: ["TT", "CT"], magnitude: 3,
    effect: "Allèle T augmente le risque de diabète T2 de ~40% par allèle.",
    summary: "Marqueur génétique le plus fort du diabète T2. Affecte la sécrétion d'insuline.",
    source: "https://www.snpedia.com/index.php/Rs7903146" },
  { rsid: "rs1801282", category: "metabolism", trait: "PPARG Pro12Ala", riskGenotypes: ["CC"], magnitude: 1,
    effect: "CC (Pro/Pro) = risque DT2 légèrement accru. CG/GG (Ala carrier) = protecteur.",
    summary: "Ala12 améliore la sensibilité à l'insuline. Effet modulé par les acides gras alimentaires.",
    source: "https://www.snpedia.com/index.php/Rs1801282" },
  { rsid: "rs1799945", category: "metabolism", trait: "HFE H63D — hémochromatose", riskGenotypes: ["GG", "CG"], magnitude: 2,
    effect: "Allèle G augmente l'absorption du fer. GG ou C282Y/H63D composite = risque hémochromatose.",
    summary: "Une des deux mutations principales de l'hémochromatose. Surveiller ferritine si porteur.",
    source: "https://www.snpedia.com/index.php/Rs1799945" },
  { rsid: "rs1800562", category: "metabolism", trait: "HFE C282Y — hémochromatose majeure", riskGenotypes: ["AA", "AG"], magnitude: 4,
    effect: "Mutation principale de l'hémochromatose. AA = phénotype quasi-certain.",
    summary: "Pénétrance variable. Surveillance fer/ferritine/saturation transferrine recommandée.",
    source: "https://www.snpedia.com/index.php/Rs1800562" },
  { rsid: "rs10830963", category: "metabolism", trait: "MTNR1B — glycémie / mélatonine", riskGenotypes: ["GG"], magnitude: 1,
    effect: "G = glycémie à jeun plus élevée, perturbation de la sécrétion d'insuline nocturne.",
    summary: "Lien rythme circadien et métabolisme du glucose. Influence DT2 et diabète gestationnel.",
    source: "https://www.snpedia.com/index.php/Rs10830963" },
  { rsid: "rs17782313", category: "metabolism", trait: "MC4R — appétit", riskGenotypes: ["CC"], magnitude: 1,
    effect: "C = appétit augmenté, prise alimentaire accrue.",
    summary: "MC4R régule la satiété. Variant fréquent associé à un IMC plus élevé.",
    source: "https://www.snpedia.com/index.php/Rs17782313" },
  { rsid: "rs4994", category: "metabolism", trait: "ADRB3 Trp64Arg — obésité", riskGenotypes: ["GG", "AG"], magnitude: 1,
    effect: "G (Arg) = lipolyse réduite, prise de poids facilitée.",
    summary: "Récepteur β3-adrénergique. Effet plus marqué en combinaison avec hypocaloriques.",
    source: "https://www.snpedia.com/index.php/Rs4994" },
  { rsid: "rs1042713", category: "metabolism", trait: "ADRB2 Arg16Gly", riskGenotypes: ["AA"], magnitude: 1,
    effect: "AA (Arg/Arg) = réponse adrénergique différente.",
    summary: "Module la lipolyse, la dilatation bronchique et la réponse à la salbutamol.",
    source: "https://www.snpedia.com/index.php/Rs1042713" },
  { rsid: "rs5400", category: "metabolism", trait: "GLUT2 — préférence sucre", riskGenotypes: ["TT", "CT"], magnitude: 1,
    effect: "T = préférence accrue pour le sucre.",
    summary: "GLUT2 = senseur de glucose hypothalamique.",
    source: "https://www.snpedia.com/index.php/Rs5400" },
  { rsid: "rs4607103", category: "metabolism", trait: "ADAMTS9 — DT2", riskGenotypes: ["CC"], magnitude: 1,
    effect: "C augmente le risque de DT2.",
    summary: "Variant GWAS du DT2.",
    source: "https://www.snpedia.com/index.php/Rs4607103" },
  { rsid: "rs5219", category: "metabolism", trait: "KCNJ11 E23K — DT2", riskGenotypes: ["TT"], magnitude: 1,
    effect: "T = sécrétion d'insuline réduite, risque DT2 accru.",
    summary: "Canal KATP des cellules β pancréatiques. Cible des sulfonylurées.",
    source: "https://www.snpedia.com/index.php/Rs5219" },
  { rsid: "rs13266634", category: "metabolism", trait: "SLC30A8 — DT2", riskGenotypes: ["CC"], magnitude: 1,
    effect: "C augmente le risque DT2.",
    summary: "Transporteur de zinc dans les cellules β.",
    source: "https://www.snpedia.com/index.php/Rs13266634" },
  { rsid: "rs10811661", category: "metabolism", trait: "CDKN2A/2B — DT2", riskGenotypes: ["CC"], magnitude: 1,
    effect: "C augmente le risque DT2 (effet via cellules β).",
    summary: "Locus partagé entre DT2 et risque coronarien.",
    source: "https://www.snpedia.com/index.php/Rs10811661" },
  { rsid: "rs2237892", category: "metabolism", trait: "KCNQ1 — DT2", riskGenotypes: ["CC"], magnitude: 1,
    effect: "C augmente le risque DT2 (population asiatique surtout).",
    summary: "Canal potassique cardiaque + pancréatique.",
    source: "https://www.snpedia.com/index.php/Rs2237892" },
  { rsid: "rs7754840", category: "metabolism", trait: "CDKAL1 — DT2", riskGenotypes: ["CC"], magnitude: 1,
    effect: "C augmente le risque DT2.",
    summary: "Variant GWAS du DT2 affectant la fonction des cellules β.",
    source: "https://www.snpedia.com/index.php/Rs7754840" },
  { rsid: "rs2241766", category: "metabolism", trait: "ADIPOQ — adiponectine", riskGenotypes: ["GG"], magnitude: 1,
    effect: "G associé à adiponectine plus basse, sensibilité insuline réduite.",
    summary: "L'adiponectine est l'adipokine la plus protectrice métaboliquement.",
    source: "https://www.snpedia.com/index.php/Rs2241766" },
  { rsid: "rs1801278", category: "metabolism", trait: "IRS1 Gly972Arg — résistance insuline", riskGenotypes: ["AA", "AG"], magnitude: 2,
    effect: "A (Arg) = signalisation insuline défectueuse, résistance accrue.",
    summary: "Substrat clé du récepteur de l'insuline. Variant mineur mais très fonctionnel.",
    source: "https://www.snpedia.com/index.php/Rs1801278" },

  // ============================ NUTRITION (20) ============================
  { rsid: "rs1801133", category: "nutrition", trait: "MTHFR C677T — méthylation", riskGenotypes: ["TT", "CT"], magnitude: 3,
    effect: "L'allèle T réduit l'activité de la MTHFR de 30-70%, augmentant l'homocystéine.",
    summary: "Important pour méthylation et métabolisme folates. Porteurs TT bénéficient de méthylfolate plutôt qu'acide folique.",
    source: "https://www.snpedia.com/index.php/Rs1801133" },
  { rsid: "rs1801131", category: "nutrition", trait: "MTHFR A1298C", riskGenotypes: ["GG"], magnitude: 1,
    effect: "GG = activité MTHFR réduite, à combiner avec C677T.",
    summary: "Deuxième variant MTHFR clinique. Effet additif avec rs1801133.",
    source: "https://www.snpedia.com/index.php/Rs1801131" },
  { rsid: "rs1805087", category: "nutrition", trait: "MTR A2756G — méthionine synthase", riskGenotypes: ["GG"], magnitude: 1,
    effect: "G = activité réduite, homocystéine plus élevée.",
    summary: "Methionine synthase. Cofacteur B12.",
    source: "https://www.snpedia.com/index.php/Rs1805087" },
  { rsid: "rs1801394", category: "nutrition", trait: "MTRR A66G — recyclage B12", riskGenotypes: ["GG"], magnitude: 1,
    effect: "G = activité MTRR réduite.",
    summary: "Régénère la B12 active. Variant pertinent pour la nutrithérapie.",
    source: "https://www.snpedia.com/index.php/Rs1801394" },
  { rsid: "rs602662", category: "nutrition", trait: "FUT2 — absorption B12", riskGenotypes: ["GG"], magnitude: 2,
    effect: "G (sécréteur) ou A (non-sécréteur) influence le microbiome et l'absorption B12.",
    summary: "Détermine le statut sécréteur ABO et la capacité d'absorption B12.",
    source: "https://www.snpedia.com/index.php/Rs602662" },
  { rsid: "rs601338", category: "nutrition", trait: "FUT2 — non-sécréteur", riskGenotypes: ["AA"], magnitude: 2,
    effect: "AA = non-sécréteur, B12 plus basse, microbiote différent, protection partielle norovirus.",
    summary: "Mutation nonsense majeure. ~20% des Européens.",
    source: "https://www.snpedia.com/index.php/Rs601338" },
  { rsid: "rs762551", category: "nutrition", trait: "CYP1A2 — métabolisme caféine", riskGenotypes: ["CC", "AC"], magnitude: 2,
    effect: "Allèle C = métaboliseur lent. Risque cardiovasculaire majoré si >2 cafés/jour.",
    summary: "AA = fast metabolizer. AC ou CC = slow, augmente le risque d'infarctus avec consommation élevée.",
    source: "https://www.snpedia.com/index.php/Rs762551" },
  { rsid: "rs2472297", category: "nutrition", trait: "Consommation caféine — habitus", riskGenotypes: [], magnitude: 1,
    effect: "T augmente la consommation habituelle de caféine.",
    summary: "Variant proche de CYP1A2. Influence le 'besoin' de café.",
    source: "https://www.snpedia.com/index.php/Rs2472297" },
  { rsid: "rs1229984", category: "nutrition", trait: "ADH1B — métabolisme alcool", riskGenotypes: ["GG"], magnitude: 3,
    effect: "G = ADH lente (fréquent en Europe). A = rapide (Asie), flush et aversion à l'alcool.",
    summary: "Premier enzyme du métabolisme de l'alcool. A = protection contre l'alcoolisme.",
    source: "https://www.snpedia.com/index.php/Rs1229984" },
  { rsid: "rs671", category: "nutrition", trait: "ALDH2 — flush alcool", riskGenotypes: ["AA", "AG"], magnitude: 4,
    effect: "A = ALDH2 inactive, accumulation d'acétaldéhyde, flush, nausées, risque cancer œsophage avec alcool.",
    summary: "La 'mutation Asian flush'. Très rare en Europe. Si porteur, l'alcool est un cancérogène majoré.",
    source: "https://www.snpedia.com/index.php/Rs671" },
  { rsid: "rs4988235", category: "nutrition", trait: "Persistance lactase", riskGenotypes: ["GG"], magnitude: 3,
    effect: "GG = intolérance au lactose probable. AG/AA = persistance lactase.",
    summary: "Le SNP majeur pour la tolérance au lactose chez les Européens.",
    source: "https://www.snpedia.com/index.php/Rs4988235" },
  { rsid: "rs2187668", category: "nutrition", trait: "HLA-DQ2.5 — cœliakie", riskGenotypes: ["AA", "AG"], magnitude: 3,
    effect: "Allèle A = HLA-DQ2.5, prérequis génétique de la maladie cœliaque.",
    summary: "~95% des cœliaques portent DQ2.5. Absence = exclusion presque totale du risque.",
    source: "https://www.snpedia.com/index.php/Rs2187668" },
  { rsid: "rs2305480", category: "nutrition", trait: "GSDMB — sensibilité gluten / asthme", riskGenotypes: ["AA"], magnitude: 1,
    effect: "Variant lié à l'inflammation digestive et l'asthme.",
    summary: "Gasdermin B, médiateur d'inflammation muqueuse.",
    source: "https://www.snpedia.com/index.php/Rs2305480" },
  { rsid: "rs2282679", category: "nutrition", trait: "GC — vitamine D circulante", riskGenotypes: ["CC"], magnitude: 2,
    effect: "C = niveaux plus bas de 25(OH)D.",
    summary: "Vitamin D Binding Protein. Si porteur, viser 50-80 ng/mL plutôt que 30.",
    source: "https://www.snpedia.com/index.php/Rs2282679" },
  { rsid: "rs10741657", category: "nutrition", trait: "CYP2R1 — synthèse 25-OH-D", riskGenotypes: ["AA"], magnitude: 2,
    effect: "A = hydroxylation hépatique réduite de la vitamine D.",
    summary: "Enzyme clé de la conversion vitamine D → 25(OH)D.",
    source: "https://www.snpedia.com/index.php/Rs10741657" },
  { rsid: "rs7041", category: "nutrition", trait: "GC isoforme — transport vitamine D", riskGenotypes: ["GG"], magnitude: 2,
    effect: "G = transport moins efficace, statut vitamine D plus bas.",
    summary: "Affinité du transporteur. Influence la biodisponibilité.",
    source: "https://www.snpedia.com/index.php/Rs7041" },
  { rsid: "rs2228570", category: "nutrition", trait: "VDR FokI — récepteur vitamine D", riskGenotypes: ["TT"], magnitude: 1,
    effect: "T (f) = récepteur tronqué moins actif.",
    summary: "Influence la réponse cellulaire à la vitamine D.",
    source: "https://www.snpedia.com/index.php/Rs2228570" },
  { rsid: "rs174537", category: "nutrition", trait: "FADS1 — conversion oméga-3", riskGenotypes: ["GG"], magnitude: 2,
    effect: "G = conversion ALA → EPA/DHA réduite.",
    summary: "Enzyme désaturase. Si porteur, EPA/DHA marin > ALA végétal.",
    source: "https://www.snpedia.com/index.php/Rs174537" },
  { rsid: "rs7946", category: "nutrition", trait: "PEMT — choline et SAM", riskGenotypes: ["AA"], magnitude: 2,
    effect: "A = synthèse de choline endogène réduite, besoin alimentaire accru.",
    summary: "Important pour la membrane cellulaire et la méthylation. Surtout chez les femmes ménopausées.",
    source: "https://www.snpedia.com/index.php/Rs7946" },
  { rsid: "rs1726866", category: "nutrition", trait: "TAS2R38 — perception amer", riskGenotypes: [], magnitude: 1,
    effect: "Variants AVI/PAV = perception amer (brocoli, choux).",
    summary: "Le 'super-taster gene'. Influence préférence légumes amers.",
    source: "https://www.snpedia.com/index.php/Rs1726866" },

  // ============================ FITNESS (10) ============================
  { rsid: "rs1815739", category: "fitness", trait: "ACTN3 R577X — fibres rapides", riskGenotypes: ["TT"], magnitude: 2,
    effect: "TT = absence d'α-actinine-3, fibres rapides moins efficaces. Avantage endurance.",
    summary: "CC = sprinter, TT = endurance, CT = mixte. Influence force explosive et risque blessure.",
    source: "https://www.snpedia.com/index.php/Rs1815739" },
  { rsid: "rs17602729", category: "fitness", trait: "AMPD1 — fatigue musculaire", riskGenotypes: ["AA", "AG"], magnitude: 2,
    effect: "A = déficit AMPD1, fatigue précoce à l'effort intense.",
    summary: "~10% des Caucasiens hétérozygotes. Performance réduite mais pas pathologique.",
    source: "https://www.snpedia.com/index.php/Rs17602729" },
  { rsid: "rs1800012", category: "fitness", trait: "COL1A1 — densité osseuse / blessures tendon", riskGenotypes: ["TT"], magnitude: 2,
    effect: "T = collagène plus fragile, risque accru tendinopathie + ostéoporose.",
    summary: "Variant Sp1. Surveiller densité osseuse + force tendineuse.",
    source: "https://www.snpedia.com/index.php/Rs1800012" },
  { rsid: "rs12722", category: "fitness", trait: "COL5A1 — souplesse / blessure", riskGenotypes: ["TT"], magnitude: 2,
    effect: "T = collagène plus rigide, risque tendinopathie d'Achille.",
    summary: "CC = plus souple, TT = plus raide. Pertinent pour stretching et yoga.",
    source: "https://www.snpedia.com/index.php/Rs12722" },
  { rsid: "rs8192678", category: "fitness", trait: "PPARGC1A — biogenèse mitochondriale", riskGenotypes: ["AA"], magnitude: 1,
    effect: "G favorise la biogenèse mitochondriale, l'endurance.",
    summary: "PGC-1α est le master switch de la mitochondrie. Variant lié à VO2max.",
    source: "https://www.snpedia.com/index.php/Rs8192678" },
  { rsid: "rs699", category: "fitness", trait: "AGT M235T — pression artérielle exercice", riskGenotypes: ["GG"], magnitude: 1,
    effect: "G augmente l'angiotensinogène, la TA et l'hypertrophie cardiaque à l'effort.",
    summary: "Influence l'adaptation cardiaque à l'entraînement (cardiac remodeling).",
    source: "https://www.snpedia.com/index.php/Rs699" },
  { rsid: "rs4253778", category: "fitness", trait: "PPARA — endurance", riskGenotypes: ["GG"], magnitude: 1,
    effect: "G favorise l'oxydation lipidique à l'effort.",
    summary: "Variant identifié chez les athlètes d'endurance d'élite.",
    source: "https://www.snpedia.com/index.php/Rs4253778" },
  { rsid: "rs1801133", category: "fitness", trait: "MTHFR — récupération exercice", riskGenotypes: ["TT"], magnitude: 1,
    effect: "T = besoin folate accru après exercice intense.",
    summary: "Pertinent pour la récupération musculaire (méthylation).",
    source: "https://www.snpedia.com/index.php/Rs1801133" },
  { rsid: "rs1799752", category: "fitness", trait: "ACE I/D — endurance vs puissance", riskGenotypes: [], magnitude: 1,
    effect: "I/I = endurance. D/D = puissance.",
    summary: "Variant insertion/délétion non capturé directement par 23andMe v4.",
    source: "https://www.snpedia.com/index.php/Rs1799752" },
  { rsid: "rs1572312", category: "fitness", trait: "NOS3 — vasodilatation effort", riskGenotypes: ["AA"], magnitude: 1,
    effect: "C = meilleure production NO, vasodilatation à l'effort.",
    summary: "eNOS endothéliale. Module la performance aérobie.",
    source: "https://www.snpedia.com/index.php/Rs1572312" },

  // ============================ COGNITIVE (12) ============================
  { rsid: "rs6265", category: "cognitive", trait: "BDNF Val66Met", riskGenotypes: ["TT", "CT"], magnitude: 2,
    effect: "Allèle T (Met) réduit la sécrétion de BDNF, affecte mémoire et plasticité.",
    summary: "BDNF favorise la neurogenèse. Val/Val = mémoire optimale, Met carrier = sensibilité au stress.",
    source: "https://www.snpedia.com/index.php/Rs6265" },
  { rsid: "rs4680", category: "cognitive", trait: "COMT Val158Met — dopamine", riskGenotypes: ["AA"], magnitude: 2,
    effect: "AA (Met/Met) = COMT lente, plus de dopamine préfrontale. Cognition fine au calme, mais sensibilité au stress.",
    summary: "Le 'warrior vs worrier'. GG = warrior (focus sous stress). AA = worrier (créatif au calme, débordé sous stress).",
    source: "https://www.snpedia.com/index.php/Rs4680" },
  { rsid: "rs53576", category: "cognitive", trait: "OXTR — récepteur ocytocine / empathie", riskGenotypes: ["AA"], magnitude: 1,
    effect: "AA = empathie réduite. AG/GG = empathie accrue.",
    summary: "Influence l'empathie, l'attachement et la régulation du stress social.",
    source: "https://www.snpedia.com/index.php/Rs53576" },
  { rsid: "rs1800497", category: "cognitive", trait: "DRD2 Taq1A — dopamine", riskGenotypes: ["AA", "AG"], magnitude: 2,
    effect: "A = densité D2 réduite, vulnérabilité accrue à l'addiction.",
    summary: "Polymorphisme du récepteur dopamine D2. Variant 'reward deficiency'.",
    source: "https://www.snpedia.com/index.php/Rs1800497" },
  { rsid: "rs1800955", category: "cognitive", trait: "DRD4 — recherche de nouveauté", riskGenotypes: [], magnitude: 1,
    effect: "T associé à recherche de nouveauté plus marquée.",
    summary: "Récepteur dopamine D4 7R-allele lié à la novelty seeking (variant VNTR non sur 23andMe).",
    source: "https://www.snpedia.com/index.php/Rs1800955" },
  { rsid: "rs25531", category: "cognitive", trait: "5-HTTLPR — sérotonine", riskGenotypes: [], magnitude: 1,
    effect: "Allèle court = vulnérabilité au stress et dépression.",
    summary: "Variant du transporteur sérotonine. Module la réponse aux ISRS.",
    source: "https://www.snpedia.com/index.php/Rs25531" },
  { rsid: "rs6311", category: "cognitive", trait: "HTR2A -1438G/A — récepteur 5-HT2A", riskGenotypes: ["GG"], magnitude: 1,
    effect: "G influence l'expression du récepteur 5-HT2A.",
    summary: "Pertinent pour réponse aux antidépresseurs et psychédéliques.",
    source: "https://www.snpedia.com/index.php/Rs6311" },
  { rsid: "rs6313", category: "cognitive", trait: "HTR2A T102C", riskGenotypes: ["TT"], magnitude: 1,
    effect: "T = expression 5-HT2A modifiée.",
    summary: "Lié à la dépression et à la réponse aux ISRS.",
    source: "https://www.snpedia.com/index.php/Rs6313" },
  { rsid: "rs1006737", category: "cognitive", trait: "CACNA1C — humeur / bipolarité", riskGenotypes: ["AA"], magnitude: 1,
    effect: "A = risque accru bipolarité, schizophrénie.",
    summary: "Canal calcique L-type. Cible thérapeutique (lithium, antagonistes Ca).",
    source: "https://www.snpedia.com/index.php/Rs1006737" },
  { rsid: "rs2298952", category: "cognitive", trait: "CHRM2 — intelligence cognitive", riskGenotypes: [], magnitude: 1,
    effect: "Variants associés à mémoire de travail et QI.",
    summary: "Récepteur muscarinique M2.",
    source: "https://www.snpedia.com/index.php/CHRM2" },
  { rsid: "rs429358", category: "cognitive", trait: "APOE — déclin cognitif", riskGenotypes: ["CC", "CT"], magnitude: 3,
    effect: "ε4 accélère le déclin cognitif lié à l'âge.",
    summary: "Au-delà d'Alzheimer, ε4 affecte la cognition normale dès 50 ans.",
    source: "https://www.snpedia.com/index.php/APOE" },
  { rsid: "rs17070145", category: "cognitive", trait: "KIBRA — mémoire épisodique", riskGenotypes: ["CC"], magnitude: 1,
    effect: "T (T-allele) = mémoire épisodique légèrement supérieure.",
    summary: "WWC1/KIBRA. Impact modeste mais robuste sur la mémoire.",
    source: "https://www.snpedia.com/index.php/Rs17070145" },

  // ============================ HORMONES (8) ============================
  { rsid: "rs1042769", category: "hormones", trait: "AR (récepteur androgène) — sensibilité", riskGenotypes: [], magnitude: 1,
    effect: "Influence la sensibilité aux androgènes (cible de la testostérone).",
    summary: "Variant pertinent pour réponse à la TRT et susceptibilité à la calvitie androgénétique.",
    source: "https://www.snpedia.com/index.php/AR" },
  { rsid: "rs523349", category: "hormones", trait: "SRD5A2 V89L — DHT / cheveux", riskGenotypes: ["GG"], magnitude: 2,
    effect: "G augmente la conversion testostérone → DHT. Calvitie + risque prostate.",
    summary: "Cible du finastéride. Si carrier G, finastéride très efficace contre l'alopécie.",
    source: "https://www.snpedia.com/index.php/Rs523349" },
  { rsid: "rs700518", category: "hormones", trait: "CYP19A1 — aromatase", riskGenotypes: ["GG"], magnitude: 1,
    effect: "G augmente l'aromatisation testostérone → œstradiol.",
    summary: "Pertinent pour les utilisateurs de TRT (risque gyno).",
    source: "https://www.snpedia.com/index.php/Rs700518" },
  { rsid: "rs6259", category: "hormones", trait: "SHBG D356N — biodisponibilité testo", riskGenotypes: ["AA"], magnitude: 1,
    effect: "A = SHBG plus haute, testostérone biodisponible plus basse.",
    summary: "Influence la testostérone libre (cliniquement plus pertinente que la totale).",
    source: "https://www.snpedia.com/index.php/Rs6259" },
  { rsid: "rs225014", category: "hormones", trait: "DIO2 Thr92Ala — conversion T4→T3", riskGenotypes: ["CC"], magnitude: 2,
    effect: "C (Ala) = conversion T4→T3 réduite tissulairement.",
    summary: "Si symptômes hypothyroïdiens malgré TSH normale + carrier, envisager T3 (lévotyrox+cynomel).",
    source: "https://www.snpedia.com/index.php/Rs225014" },
  { rsid: "rs11206244", category: "hormones", trait: "DIO1 — conversion thyroïde périphérique", riskGenotypes: ["TT"], magnitude: 1,
    effect: "T influence le ratio T3/T4.",
    summary: "DIO1 contribue à la conversion T4→T3 hépatique et rénale.",
    source: "https://www.snpedia.com/index.php/Rs11206244" },
  { rsid: "rs4644", category: "hormones", trait: "Galectin-3 — fibrose cardiaque", riskGenotypes: ["CC"], magnitude: 1,
    effect: "C augmente la fibrose myocardique.",
    summary: "Marqueur d'insuffisance cardiaque débutante.",
    source: "https://www.snpedia.com/index.php/Rs4644" },
  { rsid: "rs10046", category: "hormones", trait: "CYP19A1 — œstradiol post-ménop.", riskGenotypes: [], magnitude: 1,
    effect: "Influence E2 chez la femme post-ménopause et les hommes.",
    summary: "Cible des inhibiteurs d'aromatase.",
    source: "https://www.snpedia.com/index.php/Rs10046" },

  // ============================ IMMUNITY (8) ============================
  { rsid: "rs7574865", category: "immunity", trait: "STAT4 — auto-immunité", riskGenotypes: ["TT"], magnitude: 1,
    effect: "T = risque accru lupus, polyarthrite rhumatoïde.",
    summary: "STAT4 module la réponse Th1/Th17. Variant impliqué dans plusieurs maladies auto-immunes.",
    source: "https://www.snpedia.com/index.php/Rs7574865" },
  { rsid: "rs2476601", category: "immunity", trait: "PTPN22 — auto-immunité multi-systémique", riskGenotypes: ["AA", "AG"], magnitude: 3,
    effect: "A = risque DT1, lupus, PR, vitiligo, Hashimoto.",
    summary: "Le SNP auto-immun le plus pléiotrope chez les Européens.",
    source: "https://www.snpedia.com/index.php/Rs2476601" },
  { rsid: "rs11209026", category: "immunity", trait: "IL23R — protection contre IBD/psoriasis", riskGenotypes: ["GG"], magnitude: 2,
    effect: "A (Arg381Gln) = protection contre Crohn, RCH, psoriasis.",
    summary: "Variant fonctionnel rare protecteur. Cible des biothérapies anti-IL23.",
    source: "https://www.snpedia.com/index.php/Rs11209026" },
  { rsid: "rs2066844", category: "immunity", trait: "NOD2 R702W — Crohn", riskGenotypes: ["TT", "CT"], magnitude: 2,
    effect: "T = risque accru de maladie de Crohn.",
    summary: "Une des trois variants NOD2 majeures. Effet additif si carrier de plusieurs.",
    source: "https://www.snpedia.com/index.php/Rs2066844" },
  { rsid: "rs2066845", category: "immunity", trait: "NOD2 G908R — Crohn", riskGenotypes: ["CC", "CG"], magnitude: 2,
    effect: "C = risque Crohn accru.",
    summary: "Deuxième variant NOD2 clinique.",
    source: "https://www.snpedia.com/index.php/Rs2066845" },
  { rsid: "rs2104286", category: "immunity", trait: "IL2RA — sclérose en plaques", riskGenotypes: ["AA"], magnitude: 1,
    effect: "A = risque SEP accru.",
    summary: "Variant GWAS classique de la SEP.",
    source: "https://www.snpedia.com/index.php/Rs2104286" },
  { rsid: "rs3129889", category: "immunity", trait: "HLA-DRB1*15:01 — SEP", riskGenotypes: ["AG", "GG"], magnitude: 3,
    effect: "G = HLA-DRB1*15:01 risque SEP majoré x3.",
    summary: "Variant tag pour DR15, le facteur génétique majeur de SEP.",
    source: "https://www.snpedia.com/index.php/Rs3129889" },
  { rsid: "rs6457617", category: "immunity", trait: "HLA-DQB1 — auto-immunité", riskGenotypes: ["TT"], magnitude: 1,
    effect: "T = risque accru DT1, narcolepsie, RA.",
    summary: "Tag pour HLA classe II.",
    source: "https://www.snpedia.com/index.php/Rs6457617" },

  // ============================ DETOX / PHARMACOGENOMICS (15) ============================
  { rsid: "rs1799853", category: "detox", trait: "CYP2C9*2 — warfarine/AINS", riskGenotypes: ["TT", "CT"], magnitude: 2,
    effect: "Réduit le métabolisme de warfarine, ibuprofène, losartan.",
    summary: "Pharmacogenomic important. Doses plus faibles requises.",
    source: "https://www.snpedia.com/index.php/Rs1799853" },
  { rsid: "rs1057910", category: "detox", trait: "CYP2C9*3 — warfarine très lente", riskGenotypes: ["AC", "CC"], magnitude: 3,
    effect: "C = métaboliseur très lent. Doses warfarine 50% normales.",
    summary: "Combiné à VKORC1 = dosage fin requis.",
    source: "https://www.snpedia.com/index.php/Rs1057910" },
  { rsid: "rs9923231", category: "detox", trait: "VKORC1 — sensibilité warfarine", riskGenotypes: ["TT"], magnitude: 3,
    effect: "TT = sensibilité forte à la warfarine.",
    summary: "Critique pour ajustement warfarine. Combiné à CYP2C9.",
    source: "https://www.snpedia.com/index.php/Rs9923231" },
  { rsid: "rs4244285", category: "detox", trait: "CYP2C19*2 — clopidogrel", riskGenotypes: ["AA", "AG"], magnitude: 3,
    effect: "A = métaboliseur lent du clopidogrel (Plavix). Risque thrombose si stent.",
    summary: "FDA black box: prefer prasugrel/ticagrelor si carrier.",
    source: "https://www.snpedia.com/index.php/Rs4244285" },
  { rsid: "rs12248560", category: "detox", trait: "CYP2C19*17 — métaboliseur ultra-rapide", riskGenotypes: ["TT", "CT"], magnitude: 2,
    effect: "T = métabolisme accéléré, IPP (oméprazole) moins efficaces, saignements sous clopidogrel.",
    summary: "Inverse de *2. Important pour IPP, ISRS.",
    source: "https://www.snpedia.com/index.php/Rs12248560" },
  { rsid: "rs3892097", category: "detox", trait: "CYP2D6*4 — antidépresseurs / opioïdes", riskGenotypes: ["AA"], magnitude: 3,
    effect: "A = enzyme inactive. Codéine inefficace, antidépresseurs accumulés.",
    summary: "CYP2D6 métabolise 25% des médicaments. Phenotypage clinique recommandé.",
    source: "https://www.snpedia.com/index.php/Rs3892097" },
  { rsid: "rs1801272", category: "detox", trait: "CYP2A6 — nicotine, coumarines", riskGenotypes: ["AA"], magnitude: 1,
    effect: "A = métabolisme nicotine ralenti.",
    summary: "Influence la dépendance tabagique et la cessation.",
    source: "https://www.snpedia.com/index.php/Rs1801272" },
  { rsid: "rs2231142", category: "detox", trait: "ABCG2 — urate / médicaments", riskGenotypes: ["TT", "GT"], magnitude: 2,
    effect: "T = transport urate réduit, risque goutte.",
    summary: "Affecte clairance urate et plusieurs médicaments (statines, antiviraux).",
    source: "https://www.snpedia.com/index.php/Rs2231142" },
  { rsid: "rs1045642", category: "detox", trait: "ABCB1 (MDR1) — biodisponibilité médicaments", riskGenotypes: ["TT"], magnitude: 1,
    effect: "T = activité P-gp réduite, biodisponibilité accrue de nombreux médicaments.",
    summary: "Pertinent pour digoxine, ciclosporine, antiépileptiques, antirétroviraux.",
    source: "https://www.snpedia.com/index.php/Rs1045642" },
  { rsid: "rs4880", category: "detox", trait: "SOD2 — défense antioxydante", riskGenotypes: ["TT"], magnitude: 2,
    effect: "T (Val) = SOD2 mitochondriale moins active.",
    summary: "Stress oxydatif majoré. Bénéfice avec NAC, glutathion, vitamine E.",
    source: "https://www.snpedia.com/index.php/Rs4880" },
  { rsid: "rs1800566", category: "detox", trait: "NQO1 — détoxification quinones", riskGenotypes: ["TT"], magnitude: 2,
    effect: "T = NQO1 inactive, détoxication quinones réduite.",
    summary: "Important pour la détoxification de la fumée, pollutants, chimiothérapies.",
    source: "https://www.snpedia.com/index.php/Rs1800566" },
  { rsid: "rs1695", category: "detox", trait: "GSTP1 Ile105Val — glutathion S-transférase", riskGenotypes: ["GG"], magnitude: 2,
    effect: "G (Val) = GSTP1 moins efficace, détoxication phase 2 réduite.",
    summary: "Pertinent pour pollutants, chimiothérapies, plaquettes.",
    source: "https://www.snpedia.com/index.php/Rs1695" },
  { rsid: "rs1799930", category: "detox", trait: "NAT2 — acétylation lente", riskGenotypes: ["AA"], magnitude: 2,
    effect: "A = acétylation lente. Risque accru toxicité isoniazide, sulfamides, certains cancers.",
    summary: "Important pour métabolisme amines aromatiques (viande grillée, fumée).",
    source: "https://www.snpedia.com/index.php/Rs1799930" },
  { rsid: "rs10509681", category: "detox", trait: "CYP2C8 — paclitaxel / repaglinide", riskGenotypes: ["CC"], magnitude: 1,
    effect: "C = métabolisme normal. T = ralenti.",
    summary: "Pertinent en oncologie et pour le repaglinide.",
    source: "https://www.snpedia.com/index.php/Rs10509681" },
  { rsid: "rs2032582", category: "detox", trait: "ABCB1 G2677T — efflux médicaments", riskGenotypes: ["TT"], magnitude: 1,
    effect: "T = activité P-gp réduite.",
    summary: "Variant complémentaire à rs1045642.",
    source: "https://www.snpedia.com/index.php/Rs2032582" },

  // ============================ CARRIERS (5) ============================
  { rsid: "rs334", category: "carriers", trait: "HBB — drépanocytose (sickle cell)", riskGenotypes: ["AT", "TT"], magnitude: 4,
    effect: "T = mutation HbS. AT = trait drépanocytaire (porteur), TT = drépanocytose.",
    summary: "Mutation autosomique récessive. Conseil génétique si conjoint(e) porteur.",
    source: "https://www.snpedia.com/index.php/Rs334" },
  { rsid: "rs28940279", category: "carriers", trait: "PAH — phénylcétonurie", riskGenotypes: ["AA"], magnitude: 4,
    effect: "Mutation PKU. Hétérozygote = porteur asymptomatique.",
    summary: "Dépisté à la naissance. Important pour planning familial.",
    source: "https://www.snpedia.com/index.php/Rs28940279" },
  { rsid: "rs113993960", category: "carriers", trait: "CFTR ΔF508 — mucoviscidose", riskGenotypes: [], magnitude: 4,
    effect: "Mutation principale CF. Variant délétion non capturée par 23andMe v4 directement.",
    summary: "1/25 Européens porteurs. Conseil génétique si projet bébé.",
    source: "https://www.snpedia.com/index.php/Rs113993960" },
  { rsid: "rs80357906", category: "carriers", trait: "BRCA1 — cancer sein/ovaire", riskGenotypes: [], magnitude: 4,
    effect: "Mutations délétères BRCA1 augmentent fortement le risque.",
    summary: "23andMe ne couvre que ~3 variantes Ashkenazes. Pas un dépistage exhaustif.",
    source: "https://www.snpedia.com/index.php/BRCA1" },
  { rsid: "rs80359550", category: "carriers", trait: "BRCA2 — cancer sein/ovaire/prostate", riskGenotypes: [], magnitude: 4,
    effect: "Mutation BRCA2.",
    summary: "Important pour la prostate aussi (homme).",
    source: "https://www.snpedia.com/index.php/BRCA2" },
];

export function evaluate(catalog: CatalogEntry, userGenotype: string): { hasRisk: boolean; userGenotype: string } {
  if (!userGenotype || userGenotype.length < 2) return { hasRisk: false, userGenotype };
  const sorted = userGenotype.split("").sort().join("");
  const sortedRisk = catalog.riskGenotypes.map((g) => g.split("").sort().join(""));
  return { hasRisk: sortedRisk.includes(sorted), userGenotype };
}

// Compound trait calculator: APOE genotype derived from rs429358 + rs7412
export function apoeGenotype(g429358: string | null, g7412: string | null): string {
  if (!g429358 || !g7412) return "unknown";
  const k = `${g429358}/${g7412}`;
  // C at 429358 = ε4, T at 429358 = ε2/ε3; T at 7412 = ε2, C at 7412 = ε3/ε4
  const map: Record<string, string> = {
    "TT/TT": "ε2/ε2", "CT/TT": "ε2/ε4", "TT/CT": "ε2/ε3",
    "CT/CT": "ε3/ε4", "CT/CC": "ε3/ε4", "CC/CC": "ε4/ε4",
    "TT/CC": "ε3/ε3", "CC/CT": "ε4/ε4", "CC/TT": "(error)",
  };
  return map[k] || "unknown";
}
