/**
 * Curated DNA insight catalog. Sources: SNPedia (CC-BY-SA 3.0), ClinVar, dbSNP, peer-reviewed lit.
 * 130+ entries covering 10 categories. Magnitude 1=minor, 2=moderate, 3=strong, 4=major.
 * Risk genotypes use sorted alleles (e.g. "AT" not "TA"). Empty array = informational only.
 */

export type CatalogEntry = {
  rsid: string;
  category: "cardiovascular" | "metabolism" | "longevity" | "nutrition" | "fitness" | "cognitive" | "hormones" | "immunity" | "detox" | "carriers";
  trait: string;
  riskGenotypes: string[];
  protectiveGenotypes?: string[];
  effect?: string;
  summary: string;
  source: string;
  magnitude?: number;
};

export const CATALOG: CatalogEntry[] = [
  // ============================ LONGEVITY (15) ============================
  { rsid: "rs429358", category: "longevity", trait: "APOE — Alzheimer / longévité", riskGenotypes: ["CC", "CT"], magnitude: 4,
    effect: "L'allèle C (ε4) augmente le risque d'Alzheimer et de maladies cardiovasculaires.",
    summary: "Le SNP le plus important pour le risque d'Alzheimer tardif. ε4/ε4 multiplie le risque par ~10. ε2 protège.",
    source: "https://www.snpedia.com/index.php/Rs429358" },
  { rsid: "rs7412", category: "longevity", trait: "APOE — variant ε2 protecteur", riskGenotypes: [], protectiveGenotypes: ["CT", "TT"], magnitude: 2,
    effect: "La version T correspond à la forme protectrice (ε2), associée à un cholestérol plus bas et une meilleure longévité.",
    summary: "C'est une bonne version à porter : elle tend à baisser le cholestérol et est plus fréquente chez les personnes très âgées. Rien de particulier à faire, c'est un atout.",
    source: "https://www.snpedia.com/index.php/Rs7412" },
  { rsid: "rs2802292", category: "longevity", trait: "FOXO3 — longévité extrême", riskGenotypes: [], protectiveGenotypes: ["GG", "GT"], magnitude: 2,
    effect: "La version G est associée à une plus grande longévité et une meilleure résistance au stress des cellules.",
    summary: "C'est l'une des rares versions génétiques solidement liées à une vie très longue, fréquente chez les centenaires. C'est un atout, rien à corriger.",
    source: "https://www.snpedia.com/index.php/Rs2802292" },
  { rsid: "rs1042522", category: "longevity", trait: "TP53 codon 72 (Arg/Pro)", riskGenotypes: ["GG"], magnitude: 1,
    effect: "La version G (Pro/Pro) est liée à une longévité légèrement supérieure mais à une capacité un peu réduite à éliminer les cellules anormales.",
    summary: "C'est un compromis : cette version peut favoriser la longévité tout en rendant la défense anti-cancer un peu moins réactive. Rien d'alarmant ; un suivi médical de dépistage habituel suffit.",
    source: "https://www.snpedia.com/index.php/Rs1042522" },
  { rsid: "rs9536314", category: "longevity", trait: "KLOTHO KL-VS — vieillissement", riskGenotypes: [], protectiveGenotypes: ["GT"], magnitude: 2,
    effect: "Porter une seule copie de cette version est associé à une meilleure longévité, une meilleure mémoire et moins d'accidents vasculaires cérébraux.",
    summary: "Avoir exactement une copie de cette version rare est plutôt un avantage pour le cerveau et la longévité. C'est un atout, rien à faire.",
    source: "https://www.snpedia.com/index.php/Rs9536314" },
  { rsid: "rs1556516", category: "longevity", trait: "CDKN2B-AS1 — sénescence cellulaire", riskGenotypes: ["GG"], magnitude: 1,
    effect: "Cette version est liée à un vieillissement un peu plus rapide des cellules et à un risque cardiaque légèrement accru.",
    summary: "Effet modeste sur le vieillissement des cellules et le cœur. Les bonnes habitudes cardiovasculaires (activité physique, alimentation, pas de tabac) restent la meilleure parade.",
    source: "https://www.snpedia.com/index.php/Rs1556516" },
  { rsid: "rs2811712", category: "longevity", trait: "CDKN2A — sénescence", riskGenotypes: ["AA"], magnitude: 1,
    effect: "Ce profil est lié à un vieillissement cellulaire un peu plus marqué.",
    summary: "Une forme plus rare de ce gène protège la forme physique en vieillissant. Cette version, plus courante, ne procure pas cet avantage.",
    source: "https://www.snpedia.com/index.php/Rs2811712" },
  { rsid: "rs7762395", category: "longevity", trait: "Télomères TERT — longueur télomérique", riskGenotypes: [], magnitude: 1,
    effect: "Cette version influence l'activité de l'enzyme qui entretient les extrémités des chromosomes (les télomères).",
    summary: "Elle peut légèrement modifier la longueur de base des télomères, un marqueur du vieillissement des cellules. Aucune action spécifique requise.",
    source: "https://www.snpedia.com/index.php/TERT" },
  { rsid: "rs2736100", category: "longevity", trait: "TERT — gliomes / longueur télomères", riskGenotypes: ["CC"], magnitude: 1,
    effect: "La version C tend à allonger les télomères mais augmente aussi légèrement le risque d'une tumeur cérébrale (gliome).",
    summary: "C'est un compromis : télomères un peu plus longs mais risque de gliome légèrement majoré (risque qui reste très faible en absolu). Aucune surveillance particulière n'est recommandée pour la population générale.",
    source: "https://www.snpedia.com/index.php/Rs2736100" },
  { rsid: "rs10936599", category: "longevity", trait: "TERC — longueur télomères", riskGenotypes: ["TT"], magnitude: 1,
    effect: "La version T raccourcit légèrement les télomères, les capuchons qui protègent les chromosomes du vieillissement.",
    summary: "Deux copies T tendent à raccourcir les télomères. Sommeil, activité physique et gestion du stress aident à les préserver.",
    source: "https://www.snpedia.com/index.php/Rs10936599" },
  { rsid: "rs1800629", category: "longevity", trait: "TNF-α -308G/A — inflammaging", riskGenotypes: ["AA", "AG"], magnitude: 2,
    effect: "La version A augmente la production d'une molécule inflammatoire (TNF-alpha) et entretient une inflammation chronique de bas niveau.",
    summary: "Cette version peut maintenir un fond inflammatoire qui accélère un peu le vieillissement. Une alimentation anti-inflammatoire, l'activité physique et un bon sommeil aident à le contenir.",
    source: "https://www.snpedia.com/index.php/Rs1800629" },
  { rsid: "rs1800795", category: "longevity", trait: "IL-6 -174G/C — inflammation", riskGenotypes: ["GG"], magnitude: 2,
    effect: "Ce profil favorise une production d'interleukine-6 un peu plus élevée.",
    summary: "L'interleukine-6 est un messager de l'inflammation. Cette version tend à en produire davantage, ce qui peut entretenir une inflammation de fond.",
    source: "https://www.snpedia.com/index.php/Rs1800795" },
  { rsid: "rs7041", category: "longevity", trait: "GC (DBP) — transport vitamine D", riskGenotypes: ["GG"], magnitude: 2,
    effect: "Allèle G = transport vitamine D moins efficace, taux 25(OH)D plus bas.",
    summary: "Determines vitamin D binding protein function. Influence le statut vitamine D actif.",
    source: "https://www.snpedia.com/index.php/Rs7041" },
  { rsid: "rs4880", category: "longevity", trait: "SOD2 Val16Ala — stress oxydatif", riskGenotypes: ["TT"], magnitude: 2,
    effect: "T (Val) = SOD2 mitochondriale moins active, plus de stress oxydatif.",
    summary: "Superoxyde dismutase mitochondriale. Variant majeur pour la défense antioxydante.",
    source: "https://www.snpedia.com/index.php/Rs4880" },
  { rsid: "rs1799782", category: "longevity", trait: "XRCC1 — réparation ADN", riskGenotypes: ["TT"], magnitude: 1,
    effect: "La version T réduit un peu la capacité des cellules à réparer leur ADN.",
    summary: "Une réparation de l'ADN légèrement moins efficace peut un peu augmenter le risque de cancer sur le long terme. Limiter les expositions à risque (tabac, UV, toxiques) et suivre les dépistages habituels est conseillé.",
    source: "https://www.snpedia.com/index.php/Rs1799782" },

  // ============================ CARDIOVASCULAR (18) ============================
  { rsid: "rs10757274", category: "cardiovascular", trait: "9p21 — risque coronarien", riskGenotypes: ["GG"], magnitude: 2,
    effect: "La version G augmente d'environ 30% le risque d'infarctus, indépendamment du cholestérol.",
    summary: "Cette version est l'un des signaux génétiques les plus forts pour la maladie des artères du cœur. Surveille ta tension, ton cholestérol et garde une bonne hygiène cardiovasculaire ; parles-en à ton médecin.",
    source: "https://www.snpedia.com/index.php/Rs10757274" },
  { rsid: "rs1333049", category: "cardiovascular", trait: "9p21 — confirmation coronaire", riskGenotypes: ["CC"], magnitude: 2,
    effect: "La version C augmente le risque de maladie des artères du cœur (environ 25% par copie).",
    summary: "Cette version renforce le risque cardiaque dans la même région génétique que le marqueur précédent. Surveillance cardiovasculaire et bonnes habitudes recommandées, avec l'avis de ton médecin.",
    source: "https://www.snpedia.com/index.php/Rs1333049" },
  { rsid: "rs6025", category: "cardiovascular", trait: "Facteur V Leiden — thrombose", riskGenotypes: ["AA", "AG"], magnitude: 4,
    effect: "La version A (mutation Leiden) augmente fortement le risque de caillots dans les veines : environ 5 à 10 fois avec une copie, beaucoup plus avec deux.",
    summary: "Tu as un risque accru de phlébite ou d'embolie. Sois vigilant lors des longs voyages, d'une immobilisation ou d'une grossesse, et discute avec ton médecin avant toute contraception aux œstrogènes.",
    source: "https://www.snpedia.com/index.php/Rs6025" },
  { rsid: "rs1799963", category: "cardiovascular", trait: "Prothrombine G20210A — thrombose", riskGenotypes: ["AA", "AG"], magnitude: 3,
    effect: "La version A augmente le risque de caillots dans les veines (environ 2 à 3 fois avec une copie).",
    summary: "Risque de thrombose un peu plus élevé, qui s'additionne aux autres facteurs comme le Facteur V Leiden. Prudence lors des immobilisations, longs trajets et grossesse ; parles-en à ton médecin.",
    source: "https://www.snpedia.com/index.php/Rs1799963" },
  { rsid: "rs5918", category: "cardiovascular", trait: "ITGB3 PlA1/A2 — résistance aspirine", riskGenotypes: ["CC", "CT"], magnitude: 2,
    effect: "La version C peut rendre les plaquettes un peu moins sensibles à l'aspirine et légèrement augmenter le risque de caillots.",
    summary: "Si tu prends de l'aspirine pour protéger ton cœur, elle pourrait être un peu moins efficace. N'arrête ni ne modifie jamais ton traitement seul : parles-en à ton médecin.",
    source: "https://www.snpedia.com/index.php/Rs5918" },
  { rsid: "rs10455872", category: "cardiovascular", trait: "Lp(a) — lipoprotéine(a) élevée", riskGenotypes: ["AG", "GG"], magnitude: 3,
    effect: "Si vous portez la version G, votre taux de Lp(a) est naturellement plus élevé, ce qui augmente le risque pour le cœur et les artères, indépendamment du mauvais cholestérol.",
    summary: "Ce taux est fixé par les gènes à vie : un seul dosage sanguin suffit à le connaître. Il n'existe pas de traitement spécifique, mais bien gérer ses autres facteurs de risque cardiaque (cholestérol, tension) est d'autant plus important.",
    source: "https://www.snpedia.com/index.php/Rs10455872" },
  { rsid: "rs3798220", category: "cardiovascular", trait: "Lp(a) — cholestérol héréditaire", riskGenotypes: ["CC", "CT"], magnitude: 3,
    effect: "La version rare C augmente fortement la Lp(a), une particule de cholestérol qui accroît le risque cardiovasculaire.",
    summary: "Si tu portes cette version, demande un dosage sanguin de la Lp(a) : elle est surtout génétique et utile à connaître pour ton cœur.",
    source: "https://www.snpedia.com/index.php/Rs3798220" },
  { rsid: "rs662", category: "cardiovascular", trait: "PON1 Q192R — détoxification organophosphorés", riskGenotypes: ["AA"], magnitude: 1,
    effect: "Avec cette version du gène, une enzyme du sang qui aide à neutraliser certains pesticides et à protéger le cholestérol fonctionne moins bien.",
    summary: "Cela peut rendre un peu plus sensible aux pesticides de type organophosphorés et réduire un effet protecteur sur les artères. Utile surtout en cas d'exposition professionnelle à ces produits.",
    source: "https://www.snpedia.com/index.php/Rs662" },
  { rsid: "rs4977574", category: "cardiovascular", trait: "9p21 — IDM", riskGenotypes: ["GG"], magnitude: 2,
    effect: "Avec deux copies de la version G, le risque d'infarctus, notamment avant 60 ans, est augmenté.",
    summary: "C'est l'un des marqueurs cardiaques les mieux confirmés. Il ne change rien au quotidien, mais renforce l'intérêt de surveiller tension, cholestérol et mode de vie.",
    source: "https://www.snpedia.com/index.php/Rs4977574" },
  { rsid: "rs2228671", category: "cardiovascular", trait: "LDLR — cholestérol & statines", riskGenotypes: [], protectiveGenotypes: ["TT", "CT"], magnitude: 1,
    effect: "La version T s'accompagne d'un mauvais cholestérol (LDL) naturellement plus bas et d'une meilleure réponse aux statines.",
    summary: "Ne pas avoir cette version favorable est simplement la norme, ce n'est pas un risque en soi.",
    source: "https://www.snpedia.com/index.php/Rs2228671" },
  { rsid: "rs5174", category: "cardiovascular", trait: "LRP8 (ApoER2) — IDM précoce", riskGenotypes: ["AA"], magnitude: 1,
    effect: "Cette version du gène a été associée, dans certaines populations, à un risque d'infarctus plus précoce.",
    summary: "Le lien reste modéré et dépend des origines. À considérer avec les autres facteurs cardiaques plutôt que seul.",
    source: "https://www.snpedia.com/index.php/Rs5174" },
  { rsid: "rs2107595", category: "cardiovascular", trait: "HDAC9 — AVC ischémique", riskGenotypes: ["AA"], magnitude: 1,
    effect: "Avec deux copies de la version A, le risque d'AVC dû à l'obstruction des grosses artères est augmenté.",
    summary: "Ce gène influence l'inflammation des vaisseaux. Le résultat invite surtout à bien contrôler tension, cholestérol et tabac.",
    source: "https://www.snpedia.com/index.php/Rs2107595" },
  { rsid: "rs1746048", category: "cardiovascular", trait: "CXCL12 — coronaire", riskGenotypes: ["CC"], magnitude: 1,
    effect: "Avec deux copies de la version C, le risque de maladie des artères du cœur est légèrement augmenté.",
    summary: "Effet modeste, qui s'additionne aux autres facteurs. Mode de vie et suivi cardiaque restent la priorité.",
    source: "https://www.snpedia.com/index.php/Rs1746048" },
  { rsid: "rs17228212", category: "cardiovascular", trait: "SMAD3 — coronaire", riskGenotypes: ["CC"], magnitude: 1,
    effect: "Avec deux copies de la version C, le risque de maladie des artères du cœur est légèrement augmenté.",
    summary: "Ce gène intervient dans la cicatrisation et la rigidité des vaisseaux. L'effet est faible et à interpréter avec l'ensemble du bilan cardiaque.",
    source: "https://www.snpedia.com/index.php/Rs17228212" },
  { rsid: "rs599839", category: "cardiovascular", trait: "PSRC1/SORT1 — LDL", riskGenotypes: ["GG"], magnitude: 2,
    effect: "Avec deux copies de la version G, le mauvais cholestérol (LDL) et le risque cardiaque tendent à être plus élevés.",
    summary: "Ce gène règle la façon dont le foie gère le cholestérol. Le résultat renforce l'intérêt de surveiller le LDL.",
    source: "https://www.snpedia.com/index.php/Rs599839" },
  { rsid: "rs5882", category: "cardiovascular", trait: "CETP I405V — HDL & longévité", riskGenotypes: [], protectiveGenotypes: ["GG"], magnitude: 1,
    effect: "La version GG est associée à un bon cholestérol (HDL) plus élevé et à une longévité un peu meilleure dans certaines populations.",
    summary: "C'est une version plutôt favorable pour le profil de cholestérol. Aucune action particulière n'est requise.",
    source: "https://www.snpedia.com/index.php/Rs5882" },
  { rsid: "rs3764261", category: "cardiovascular", trait: "CETP — bon cholestérol (HDL)", riskGenotypes: [], protectiveGenotypes: ["TT", "GT"], magnitude: 2,
    effect: "La version T augmente le bon cholestérol (HDL).",
    summary: "Cette version est plutôt favorable au profil de cholestérol ; son absence n'est pas un risque.",
    source: "https://www.snpedia.com/index.php/Rs3764261" },
  { rsid: "rs1800775", category: "cardiovascular", trait: "CETP -629 — HDL & risque", riskGenotypes: ["CC"], magnitude: 1,
    effect: "Avec deux copies de la version C, le taux de bon cholestérol (HDL) tend à être un peu plus bas.",
    summary: "Effet modéré sur le profil de cholestérol. À regarder avec l'ensemble du bilan lipidique plutôt que seul.",
    source: "https://www.snpedia.com/index.php/Rs1800775" },

  // ============================ METABOLISM (18) ============================
  { rsid: "rs9939609", category: "metabolism", trait: "FTO — obésité", riskGenotypes: ["AA", "AT"], magnitude: 3,
    effect: "Allèle A augmente le risque d'obésité de 20-30% par allèle.",
    summary: "Le SNP le mieux établi pour l'obésité. Effet largement compensé par l'exercice régulier.",
    source: "https://www.snpedia.com/index.php/Rs9939609" },
  { rsid: "rs7903146", category: "metabolism", trait: "TCF7L2 — diabète T2", riskGenotypes: ["TT", "CT"], magnitude: 3,
    effect: "Avec la version T, la production d'insuline est moins efficace, ce qui augmente le risque de diabète de type 2.",
    summary: "C'est le marqueur génétique le plus solide du diabète de type 2. Une bonne hygiène de vie et un suivi de la glycémie réduisent nettement ce risque.",
    source: "https://www.snpedia.com/index.php/Rs7903146" },
  { rsid: "rs1801282", category: "metabolism", trait: "PPARG Pro12Ala", riskGenotypes: ["CC"], magnitude: 1,
    effect: "Ce profil est associé à un risque de diabète de type 2 légèrement plus élevé.",
    summary: "La forme Ala, plus rare, améliore la sensibilité à l'insuline et protège un peu. Cette version, la plus courante, n'apporte pas cet avantage. L'effet dépend aussi des graisses alimentaires.",
    source: "https://www.snpedia.com/index.php/Rs1801282" },
  { rsid: "rs1799945", category: "metabolism", trait: "HFE H63D — hémochromatose", riskGenotypes: ["GG", "CG"], magnitude: 2,
    effect: "Avec la version G, le corps absorbe davantage de fer, ce qui peut à la longue en provoquer un excès.",
    summary: "C'est l'une des deux principales mutations liées à l'hémochromatose (surcharge en fer). Si vous êtes porteur, il est utile de surveiller la ferritine de temps en temps.",
    source: "https://www.snpedia.com/index.php/Rs1799945" },
  { rsid: "rs1800562", category: "metabolism", trait: "HFE C282Y — hémochromatose majeure", riskGenotypes: ["AA", "AG"], magnitude: 4,
    effect: "Avec la version A, surtout en double copie, le corps risque d'accumuler trop de fer (hémochromatose).",
    summary: "C'est la mutation principale de l'hémochromatose, mais elle ne se manifeste pas chez tout le monde. Un suivi du fer, de la ferritine et de la saturation de la transferrine est recommandé pour les porteurs.",
    source: "https://www.snpedia.com/index.php/Rs1800562" },
  { rsid: "rs10830963", category: "metabolism", trait: "MTNR1B — glycémie / mélatonine", riskGenotypes: ["GG"], magnitude: 1,
    effect: "Avec deux copies de la version G, la glycémie à jeun tend à être plus élevée et la régulation nocturne du sucre est perturbée.",
    summary: "Ce gène relie le rythme jour/nuit et la gestion du sucre. Il peut augmenter le risque de diabète, y compris pendant la grossesse, d'où l'intérêt de surveiller la glycémie.",
    source: "https://www.snpedia.com/index.php/Rs10830963" },
  { rsid: "rs17782313", category: "metabolism", trait: "MC4R — appétit", riskGenotypes: ["CC"], magnitude: 1,
    effect: "Avec deux copies de la version C, l'appétit et la prise alimentaire tendent à être plus importants.",
    summary: "Ce gène règle la sensation de satiété. Une version fréquente associée à un poids un peu plus élevé, sur laquelle les habitudes alimentaires gardent toute leur influence.",
    source: "https://www.snpedia.com/index.php/Rs17782313" },
  { rsid: "rs4994", category: "metabolism", trait: "ADRB3 Trp64Arg — obésité", riskGenotypes: ["GG", "AG"], magnitude: 1,
    effect: "La version à risque rend la combustion des graisses un peu moins efficace, ce qui facilite la prise de poids.",
    summary: "Cette particularité peut compliquer la perte de poids ; un suivi alimentaire et de l'activité physique régulière aident à compenser.",
    source: "https://www.snpedia.com/index.php/Rs4994" },
  { rsid: "rs1042713", category: "metabolism", trait: "ADRB2 Arg16Gly", riskGenotypes: ["AA"], magnitude: 1,
    effect: "La version à risque modifie la façon dont le corps réagit à l'adrénaline (graisses, bronches).",
    summary: "Elle peut influencer la mobilisation des graisses et la réponse à certains traitements de l'asthme ; à signaler à votre médecin si concerné.",
    source: "https://www.snpedia.com/index.php/Rs1042713" },
  { rsid: "rs5400", category: "metabolism", trait: "GLUT2 — préférence sucre", riskGenotypes: ["TT", "CT"], magnitude: 1,
    effect: "La version à risque est liée à une attirance un peu plus forte pour le sucre.",
    summary: "Un détecteur de sucre du cerveau fonctionne différemment ; être attentif à sa consommation de sucre peut aider.",
    source: "https://www.snpedia.com/index.php/Rs5400" },
  { rsid: "rs4607103", category: "metabolism", trait: "ADAMTS9 — DT2", riskGenotypes: ["CC"], magnitude: 1,
    effect: "Ce profil est associé à un risque de diabète de type 2 un peu plus élevé.",
    summary: "Cette version réduit légèrement la sensibilité des muscles à l'insuline, ce qui pèse sur la régulation du sucre dans le sang.",
    source: "https://www.snpedia.com/index.php/Rs4607103" },
  { rsid: "rs5219", category: "metabolism", trait: "KCNJ11 E23K — DT2", riskGenotypes: ["TT"], magnitude: 1,
    effect: "La version à risque diminue un peu la sécrétion d'insuline, ce qui peut élever le risque de diabète de type 2.",
    summary: "Effet modeste ; surveiller sa glycémie et son poids reste la meilleure prévention.",
    source: "https://www.snpedia.com/index.php/Rs5219" },
  { rsid: "rs13266634", category: "metabolism", trait: "SLC30A8 — DT2", riskGenotypes: ["CC"], magnitude: 1,
    effect: "Cette version est liée à un risque un peu plus élevé de diabète de type 2 en affectant les cellules du pancréas.",
    summary: "Ce gène code un transporteur de zinc dans les cellules du pancréas qui produisent l'insuline. Cette version réduit légèrement la sécrétion d'insuline en réponse au sucre.",
    source: "https://www.snpedia.com/index.php/Rs13266634" },
  { rsid: "rs10811661", category: "metabolism", trait: "CDKN2A/2B — DT2", riskGenotypes: ["TT"], magnitude: 1,
    effect: "Ce profil est associé à un risque de diabète de type 2 plus élevé.",
    summary: "Cette version réduit la libération d'insuline par le pancréas, ce qui augmente le risque de diabète de type 2.",
    source: "https://www.snpedia.com/index.php/Rs10811661" },
  { rsid: "rs2237892", category: "metabolism", trait: "KCNQ1 — DT2", riskGenotypes: ["CC"], magnitude: 1,
    effect: "Ce profil est associé à un risque de diabète de type 2 plus élevé, surtout en populations asiatiques.",
    summary: "Ce gène code un canal potassique présent dans le cœur et le pancréas. Cette version est liée à une réponse en insuline réduite et un risque de diabète accru.",
    source: "https://www.snpedia.com/index.php/Rs2237892" },
  { rsid: "rs7754840", category: "metabolism", trait: "CDKAL1 — DT2", riskGenotypes: ["CC"], magnitude: 1,
    effect: "Cette version augmente légèrement le risque de diabète de type 2.",
    summary: "Effet modeste ; une bonne hygiène de vie reste le levier principal.",
    source: "https://www.snpedia.com/index.php/Rs7754840" },
  { rsid: "rs2241766", category: "metabolism", trait: "ADIPOQ — adiponectine", riskGenotypes: ["GG"], magnitude: 1,
    effect: "La version à risque s'accompagne d'un taux plus bas d'adiponectine, une hormone protectrice du métabolisme.",
    summary: "Cela peut réduire un peu la sensibilité à l'insuline ; maintenir un poids sain aide à compenser.",
    source: "https://www.snpedia.com/index.php/Rs2241766" },
  { rsid: "rs1801278", category: "metabolism", trait: "IRS1 Gly972Arg — résistance insuline", riskGenotypes: ["AA", "AG"], magnitude: 2,
    effect: "La version à risque perturbe la transmission du signal de l'insuline dans les cellules.",
    summary: "Elle peut favoriser une résistance à l'insuline ; surveiller glycémie et poids est utile pour les porteurs.",
    source: "https://www.snpedia.com/index.php/Rs1801278" },

  // ============================ NUTRITION (20) ============================
  { rsid: "rs1801133", category: "nutrition", trait: "MTHFR C677T — méthylation", riskGenotypes: ["TT", "CT"], magnitude: 3,
    effect: "L'allèle T réduit l'activité de la MTHFR de 30-70%, augmentant l'homocystéine.",
    summary: "Important pour méthylation et métabolisme folates. Porteurs TT bénéficient de méthylfolate plutôt qu'acide folique.",
    source: "https://www.snpedia.com/index.php/Rs1801133" },
  { rsid: "rs1801131", category: "nutrition", trait: "MTHFR A1298C", riskGenotypes: ["GG"], magnitude: 1,
    effect: "La version à risque réduit légèrement l'activité de la même enzyme des folates.",
    summary: "Son effet est plus net lorsqu'il s'ajoute à l'autre variante de cette enzyme ; un avis nutritionnel peut aider si les deux sont présentes.",
    source: "https://www.snpedia.com/index.php/Rs1801131" },
  { rsid: "rs1805087", category: "nutrition", trait: "MTR A2756G — méthionine synthase", riskGenotypes: ["GG"], magnitude: 1,
    effect: "La version à risque réduit l'activité d'une enzyme qui recycle un acide aminé, ce qui peut élever l'homocystéine.",
    summary: "Cette enzyme dépend de la vitamine B12 ; un bon statut en B12 aide à soutenir son fonctionnement.",
    source: "https://www.snpedia.com/index.php/Rs1805087" },
  { rsid: "rs1801394", category: "nutrition", trait: "MTRR A66G — recyclage B12", riskGenotypes: ["GG"], magnitude: 1,
    effect: "La version à risque diminue l'activité d'une enzyme qui régénère la vitamine B12 active.",
    summary: "Elle peut influencer le recyclage de la B12 ; veiller à un apport suffisant en B12 est judicieux.",
    source: "https://www.snpedia.com/index.php/Rs1801394" },
  { rsid: "rs602662", category: "nutrition", trait: "FUT2 — absorption B12", riskGenotypes: ["GG"], magnitude: 2,
    effect: "G (sécréteur) ou A (non-sécréteur) influence le microbiome et l'absorption B12.",
    summary: "Détermine le statut sécréteur ABO et la capacité d'absorption B12.",
    source: "https://www.snpedia.com/index.php/Rs602662" },
  { rsid: "rs601338", category: "nutrition", trait: "FUT2 — non-sécréteur", riskGenotypes: ["AA"], magnitude: 2,
    effect: "La version à risque rend non-sécréteur, ce qui s'accompagne d'une B12 plus basse, d'une flore différente et d'une protection partielle contre certaines gastro-entérites.",
    summary: "Environ une personne sur cinq en Europe est concernée ; surveiller son taux de B12 peut être utile.",
    source: "https://www.snpedia.com/index.php/Rs601338" },
  { rsid: "rs762551", category: "nutrition", trait: "CYP1A2 — métabolisme caféine", riskGenotypes: ["CC", "AC"], magnitude: 2,
    effect: "La version à risque ralentit l'élimination de la caféine par le foie.",
    summary: "Chez ces personnes, une forte consommation de café (plus de 2 par jour) a été liée à un risque cardiaque accru ; modérer le café est prudent.",
    source: "https://www.snpedia.com/index.php/Rs762551" },
  { rsid: "rs2472297", category: "nutrition", trait: "Consommation caféine — habitus", riskGenotypes: [], magnitude: 1,
    effect: "Cette version est associée à une consommation habituelle de caféine un peu plus élevée.",
    summary: "Elle reflète surtout une préférence pour le café, sans risque de santé propre.",
    source: "https://www.snpedia.com/index.php/Rs2472297" },
  { rsid: "rs1229984", category: "nutrition", trait: "ADH1B — métabolisme alcool", riskGenotypes: ["GG"], magnitude: 3,
    effect: "Ce profil correspond à une dégradation lente de l'alcool, fréquente en Europe.",
    summary: "C'est la première enzyme qui transforme l'alcool dans le corps. La forme rapide, plus rare, provoque rougeurs et inconfort qui freinent la consommation. Cette version ne procure pas cette protection.",
    source: "https://www.snpedia.com/index.php/Rs1229984" },
  { rsid: "rs671", category: "nutrition", trait: "ALDH2 — flush alcool", riskGenotypes: ["AA", "AG"], magnitude: 4,
    effect: "Une version d'une enzyme du foie ne dégrade plus correctement l'alcool, ce qui fait s'accumuler une substance toxique après avoir bu.",
    summary: "Cette version provoque rougeurs, nausées et palpitations dès de petites quantités d'alcool, et augmente nettement le risque de cancer de l'œsophage. Si vous êtes concerné, mieux vaut éviter l'alcool.",
    source: "https://www.snpedia.com/index.php/Rs671" },
  { rsid: "rs4988235", category: "nutrition", trait: "Persistance lactase", riskGenotypes: ["GG"], magnitude: 3,
    effect: "Cette version arrête la production de l'enzyme qui digère le sucre du lait après l'enfance.",
    summary: "Elle rend l'intolérance au lactose probable à l'âge adulte (ballonnements, inconfort après produits laitiers). Réduire le lactose ou utiliser des produits sans lactose aide.",
    source: "https://www.snpedia.com/index.php/Rs4988235" },
  { rsid: "rs2187668", category: "nutrition", trait: "HLA-DQ2.5 — cœliakie", riskGenotypes: ["AA", "AG"], magnitude: 3,
    effect: "Cette version porte la principale prédisposition immunitaire nécessaire pour développer la maladie cœliaque.",
    summary: "Presque tous les cœliaques ont cette prédisposition, mais la plupart des porteurs ne développeront jamais la maladie. Son absence rend la cœliaque très improbable.",
    source: "https://www.snpedia.com/index.php/Rs2187668" },
  { rsid: "rs2305480", category: "nutrition", trait: "GSDMB — sensibilité gluten / asthme", riskGenotypes: ["AA"], magnitude: 1,
    effect: "Cette version est liée à une inflammation accrue des voies respiratoires et de la muqueuse digestive.",
    summary: "Elle est associée à un risque un peu plus élevé d'asthme et de sensibilité digestive. Surveiller les symptômes respiratoires peut être utile.",
    source: "https://www.snpedia.com/index.php/Rs2305480" },
  { rsid: "rs2282679", category: "nutrition", trait: "GC — vitamine D circulante", riskGenotypes: ["CC"], magnitude: 2,
    effect: "Cette version réduit la quantité de protéine qui transporte la vitamine D dans le sang.",
    summary: "Elle tend à donner des taux de vitamine D plus bas à apport égal. Un dosage sanguin et, si besoin, une supplémentation adaptée sont conseillés.",
    source: "https://www.snpedia.com/index.php/Rs2282679" },
  { rsid: "rs10741657", category: "nutrition", trait: "CYP2R1 — synthèse 25-OH-D", riskGenotypes: ["AA"], magnitude: 2,
    effect: "Cette version diminue l'efficacité de l'enzyme du foie qui active la vitamine D.",
    summary: "Elle est associée à des taux de vitamine D un peu plus bas. Vérifier son taux et ajuster l'apport au besoin est une bonne idée.",
    source: "https://www.snpedia.com/index.php/Rs10741657" },
  { rsid: "rs7041", category: "nutrition", trait: "GC isoforme — transport vitamine D", riskGenotypes: ["GG"], magnitude: 2,
    effect: "G = transport moins efficace, statut vitamine D plus bas.",
    summary: "Affinité du transporteur. Influence la biodisponibilité.",
    source: "https://www.snpedia.com/index.php/Rs7041" },
  { rsid: "rs2228570", category: "nutrition", trait: "VDR FokI — récepteur vitamine D", riskGenotypes: ["TT"], magnitude: 1,
    effect: "Cette version produit un récepteur de la vitamine D un peu moins actif.",
    summary: "Les cellules répondent un peu moins bien à la vitamine D. Maintenir un bon taux sanguin de vitamine D est d'autant plus utile.",
    source: "https://www.snpedia.com/index.php/Rs2228570" },
  { rsid: "rs174537", category: "nutrition", trait: "FADS1 — conversion oméga-3", riskGenotypes: ["TT"], magnitude: 2,
    effect: "La version T transforme moins bien les oméga-3 végétaux (ALA) en formes actives EPA et DHA.",
    summary: "Cette enzyme transforme l'oméga-3 d'origine végétale en EPA et DHA. Cette version diminue cette transformation, donc les oméga-3 marins sont plus utiles que les végétaux.",
    source: "https://www.snpedia.com/index.php/Rs174537" },
  { rsid: "rs7946", category: "nutrition", trait: "PEMT — choline et SAM", riskGenotypes: ["AA"], magnitude: 2,
    effect: "Cette version diminue la fabrication interne de choline, un nutriment important pour le foie et les cellules.",
    summary: "Elle augmente le besoin d'apporter de la choline par l'alimentation (œufs, foie, légumineuses), surtout chez les femmes après la ménopause.",
    source: "https://www.snpedia.com/index.php/Rs7946" },
  { rsid: "rs1726866", category: "nutrition", trait: "TAS2R38 — perception amer", riskGenotypes: [], magnitude: 1,
    effect: "Cette version influence l'intensité avec laquelle on perçoit l'amertume des aliments comme le brocoli ou les choux.",
    summary: "Elle ne représente pas un risque de santé : elle explique surtout pourquoi certaines personnes trouvent les légumes amers plus désagréables. Varier la préparation peut aider à les apprécier.",
    source: "https://www.snpedia.com/index.php/Rs1726866" },

  // ============================ FITNESS (10) ============================
  { rsid: "rs1815739", category: "fitness", trait: "ACTN3 R577X — fibres rapides", riskGenotypes: [], magnitude: 2,
    effect: "Cette version détermine la présence ou l'absence d'une protéine des fibres musculaires rapides.",
    summary: "Elle n'est pas un risque de santé : elle oriente plutôt vers un profil sprint/force ou endurance. Utile pour adapter son entraînement, pas pour s'inquiéter.",
    source: "https://www.snpedia.com/index.php/Rs1815739" },
  { rsid: "rs17602729", category: "fitness", trait: "AMPD1 — fatigue musculaire", riskGenotypes: ["AA", "AG"], magnitude: 2,
    effect: "Cette version réduit une enzyme musculaire, ce qui peut faire apparaître la fatigue plus tôt lors d'efforts intenses.",
    summary: "Elle est fréquente et bénigne : elle peut limiter un peu la performance à haute intensité sans poser de problème de santé. Bien récupérer et s'échauffer aide.",
    source: "https://www.snpedia.com/index.php/Rs17602729" },
  { rsid: "rs1800012", category: "fitness", trait: "COL1A1 — densité osseuse / blessures tendon", riskGenotypes: ["TT"], magnitude: 2,
    effect: "Cette version modifie la fabrication du collagène, qui devient un peu plus fragile dans les os et les tendons.",
    summary: "Elle est associée à un risque accru de tendinite et de fragilité osseuse. Renforcement progressif des tendons et suivi de la densité osseuse sont conseillés.",
    source: "https://www.snpedia.com/index.php/Rs1800012" },
  { rsid: "rs12722", category: "fitness", trait: "COL5A1 — souplesse / blessure", riskGenotypes: ["TT"], magnitude: 2,
    effect: "Cette version rend le collagène des tendons un peu plus rigide et moins souple.",
    summary: "Elle est associée à un risque plus élevé de tendinite, notamment au tendon d'Achille. Travailler la souplesse et augmenter les charges progressivement aide à se protéger.",
    source: "https://www.snpedia.com/index.php/Rs12722" },
  { rsid: "rs8192678", category: "fitness", trait: "PPARGC1A — biogenèse mitochondriale", riskGenotypes: ["AA"], magnitude: 1,
    effect: "Cette version diminue un régulateur clé de la fabrication des centrales énergétiques des cellules (mitochondries).",
    summary: "Elle est associée à un léger désavantage pour l'endurance et la capacité aérobie. L'entraînement d'endurance reste le meilleur moyen de stimuler ses mitochondries.",
    source: "https://www.snpedia.com/index.php/Rs8192678" },
  { rsid: "rs699", category: "fitness", trait: "AGT M235T — pression artérielle exercice", riskGenotypes: ["GG"], magnitude: 1,
    effect: "Cette version augmente une hormone qui élève la tension artérielle et favorise l'épaississement du muscle cardiaque à l'effort.",
    summary: "Elle est associée à une tension plus haute et à une adaptation cardiaque à l'exercice plus marquée. Surveiller sa tension et limiter le sel sont des mesures sensées.",
    source: "https://www.snpedia.com/index.php/Rs699" },
  { rsid: "rs4253778", category: "fitness", trait: "PPARA — endurance", riskGenotypes: ["GG"], magnitude: 1,
    effect: "Ce profil favorise l'oxydation des graisses à l'effort, un atout pour l'endurance.",
    summary: "Cette version est plus fréquente chez les sportifs d'endurance et s'accompagne d'une meilleure utilisation des graisses pendant l'effort prolongé.",
    source: "https://www.snpedia.com/index.php/Rs4253778" },
  { rsid: "rs1801133", category: "fitness", trait: "MTHFR — récupération exercice", riskGenotypes: ["TT"], magnitude: 1,
    effect: "Cette version réduit l'activité d'une enzyme impliquée dans le traitement des folates (vitamine B9).",
    summary: "Elle augmente le besoin en folates, en particulier après un effort intense ou pendant la récupération. Un apport suffisant en folates (légumes verts, ou folate actif) est conseillé.",
    source: "https://www.snpedia.com/index.php/Rs1801133" },
  { rsid: "rs1799752", category: "fitness", trait: "ACE I/D — endurance vs puissance", riskGenotypes: [], magnitude: 1,
    effect: "Cette version correspond à une différence de longueur d'un gène qui oriente le profil entre endurance et puissance.",
    summary: "Ce n'est pas un risque de santé : elle aide surtout à comprendre ses prédispositions sportives. Elle n'est pas toujours mesurée de façon fiable par les tests grand public.",
    source: "https://www.snpedia.com/index.php/Rs1799752" },
  { rsid: "rs1572312", category: "fitness", trait: "NOS3 — vasodilatation effort", riskGenotypes: ["AA"], magnitude: 1,
    effect: "La version la plus répandue de ce gène aide les vaisseaux à se dilater pendant l'effort, ce qui favorise l'endurance.",
    summary: "Ce gène contrôle la dilatation des vaisseaux à l'exercice. Avec la version la moins favorable, l'apport d'oxygène aux muscles peut être un peu moins efficace.",
    source: "https://www.snpedia.com/index.php/Rs1572312" },

  // ============================ COGNITIVE (12) ============================
  { rsid: "rs6265", category: "cognitive", trait: "BDNF Val66Met", riskGenotypes: ["TT", "CT"], magnitude: 2,
    effect: "La version Met diminue la production d'un facteur qui aide le cerveau à former et entretenir ses connexions.",
    summary: "Ce gène soutient la mémoire et l'adaptation du cerveau. Les porteurs de la version Met peuvent être un peu plus sensibles au stress; sommeil, sport et apprentissage réguliers aident à compenser.",
    source: "https://www.snpedia.com/index.php/Rs6265" },
  { rsid: "rs4680", category: "cognitive", trait: "COMT Val158Met — dopamine", riskGenotypes: ["AA"], magnitude: 2,
    effect: "La version lente garde plus de dopamine à l'avant du cerveau: bonne concentration au calme, mais plus de sensibilité sous pression.",
    summary: "C'est le profil dit 'penseur': cognition fine et créative au repos, mais qui peut être vite débordée par le stress. Gérer la charge mentale et le stress est utile.",
    source: "https://www.snpedia.com/index.php/Rs4680" },
  { rsid: "rs53576", category: "cognitive", trait: "OXTR — récepteur ocytocine / empathie", riskGenotypes: ["AA"], magnitude: 1,
    effect: "La version concernée est associée à un peu moins d'empathie spontanée et à une gestion du stress social un peu moins souple.",
    summary: "Ce gène influence l'empathie, l'attachement et la façon de gérer le stress relationnel. L'effet reste modeste et très dépendant de l'environnement.",
    source: "https://www.snpedia.com/index.php/Rs53576" },
  { rsid: "rs1800497", category: "cognitive", trait: "DRD2 Taq1A — dopamine", riskGenotypes: ["AA", "AG"], magnitude: 2,
    effect: "La version concernée est associée à moins de récepteurs à la dopamine, ce qui peut accroître la vulnérabilité aux comportements addictifs.",
    summary: "Ce gène module le circuit de la récompense. Les porteurs peuvent être un peu plus sensibles aux addictions; en avoir conscience aide à poser des garde-fous.",
    source: "https://www.snpedia.com/index.php/Rs1800497" },
  { rsid: "rs1800955", category: "cognitive", trait: "DRD4 — recherche de nouveauté", riskGenotypes: [], magnitude: 1,
    effect: "Une version de ce gène est associée à une attirance plus marquée pour la nouveauté et l'exploration.",
    summary: "Ce gène de la dopamine influence le goût du nouveau. C'est un trait de tempérament, ni bon ni mauvais en soi.",
    source: "https://www.snpedia.com/index.php/Rs1800955" },
  { rsid: "rs25531", category: "cognitive", trait: "5-HTTLPR — sérotonine", riskGenotypes: [], magnitude: 1,
    effect: "La version 'courte' de ce gène est associée à une sensibilité un peu plus grande au stress et aux baisses de moral.",
    summary: "Ce gène règle le recyclage de la sérotonine et peut moduler la réponse à certains antidépresseurs. L'effet dépend beaucoup du vécu et de l'environnement.",
    source: "https://www.snpedia.com/index.php/Rs25531" },
  { rsid: "rs6311", category: "cognitive", trait: "HTR2A -1438G/A — récepteur 5-HT2A", riskGenotypes: ["GG"], magnitude: 1,
    effect: "Ce profil influence l'expression du récepteur à la sérotonine 5-HT2A.",
    summary: "Ce récepteur de la sérotonine intervient dans l'humeur. Cette version peut moduler la réponse à certains antidépresseurs et substances apparentées.",
    source: "https://www.snpedia.com/index.php/Rs6311" },
  { rsid: "rs6313", category: "cognitive", trait: "HTR2A T102C", riskGenotypes: ["TT"], magnitude: 1,
    effect: "Ce profil modifie l'expression du récepteur à la sérotonine 5-HT2A.",
    summary: "Ce récepteur de la sérotonine intervient dans l'humeur. Cette version est étudiée en lien avec la dépression et la réponse aux antidépresseurs.",
    source: "https://www.snpedia.com/index.php/Rs6313" },
  { rsid: "rs1006737", category: "cognitive", trait: "CACNA1C — humeur / bipolarité", riskGenotypes: ["AA"], magnitude: 1,
    effect: "La version concernée est associée à un risque un peu plus élevé de troubles de l'humeur.",
    summary: "Ce gène régule un canal calcique des neurones et est étudié comme facteur de vulnérabilité à la bipolarité. L'effet d'un seul gène reste faible; le contexte global compte.",
    source: "https://www.snpedia.com/index.php/Rs1006737" },
  { rsid: "rs2298952", category: "cognitive", trait: "CHRM2 — intelligence cognitive", riskGenotypes: [], magnitude: 1,
    effect: "Des versions de ce gène sont faiblement associées à des différences de mémoire de travail.",
    summary: "Ce gène intervient dans la signalisation cérébrale. Son influence sur les capacités cognitives est très modeste.",
    source: "https://www.snpedia.com/index.php/CHRM2" },
  { rsid: "rs429358", category: "cognitive", trait: "APOE — déclin cognitif", riskGenotypes: ["CC", "CT"], magnitude: 3,
    effect: "La variante e4 est associée à un déclin de la mémoire et de la cognition un peu plus rapide avec l'âge.",
    summary: "Au-delà d'Alzheimer, cette variante peut influencer la cognition normale dès la cinquantaine. Sommeil, activité physique et santé cardiovasculaire sont d'autant plus importants.",
    source: "https://www.snpedia.com/index.php/APOE" },
  { rsid: "rs17070145", category: "cognitive", trait: "KIBRA — mémoire épisodique", riskGenotypes: ["CC"], magnitude: 1,
    effect: "La version la plus favorable de ce gène est associée à une mémoire des événements légèrement meilleure.",
    summary: "Ce gène a un effet modeste mais reproductible sur la mémoire des souvenirs personnels. Sans la version favorable, la différence reste petite.",
    source: "https://www.snpedia.com/index.php/Rs17070145" },

  // ============================ HORMONES (8) ============================
  { rsid: "rs1042769", category: "hormones", trait: "AR (récepteur androgène) — sensibilité", riskGenotypes: [], magnitude: 1,
    effect: "Cette version influence la sensibilité du corps aux hormones masculines comme la testostérone.",
    summary: "Ce gène peut moduler la réponse à la testostérone et la tendance à la calvitie. Information utile surtout en cas de traitement hormonal.",
    source: "https://www.snpedia.com/index.php/AR" },
  { rsid: "rs523349", category: "hormones", trait: "SRD5A2 V89L — DHT / cheveux", riskGenotypes: ["GG"], magnitude: 2,
    effect: "La version concernée augmente la transformation de la testostérone en sa forme plus puissante (DHT).",
    summary: "Plus de DHT peut favoriser la chute de cheveux et solliciter davantage la prostate. Un traitement bloquant la DHT y est en général très efficace.",
    source: "https://www.snpedia.com/index.php/Rs523349" },
  { rsid: "rs700518", category: "hormones", trait: "CYP19A1 — aromatase", riskGenotypes: ["GG"], magnitude: 1,
    effect: "La version concernée augmente la transformation de la testostérone en œstrogène.",
    summary: "Un excès de cette conversion peut déplaire en cas de traitement à la testostérone. À surveiller surtout dans ce contexte.",
    source: "https://www.snpedia.com/index.php/Rs700518" },
  { rsid: "rs6259", category: "hormones", trait: "SHBG D356N — biodisponibilité testo", riskGenotypes: ["AA"], magnitude: 1,
    effect: "La version concernée augmente la protéine qui retient la testostérone, ce qui laisse moins de testostérone réellement active.",
    summary: "C'est la testostérone libre, plus que la totale, qui compte au quotidien. Cette version peut l'abaisser un peu.",
    source: "https://www.snpedia.com/index.php/Rs6259" },
  { rsid: "rs225014", category: "hormones", trait: "DIO2 Thr92Ala — conversion T4→T3", riskGenotypes: ["CC"], magnitude: 2,
    effect: "La version concernée transforme moins bien l'hormone thyroïdienne de stockage (T4) en sa forme active (T3) dans les tissus.",
    summary: "En cas de symptômes de thyroïde basse malgré des analyses normales, cette version peut expliquer une partie du ressenti. À discuter avec un médecin pour adapter le traitement.",
    source: "https://www.snpedia.com/index.php/Rs225014" },
  { rsid: "rs11206244", category: "hormones", trait: "DIO1 — conversion thyroïde périphérique", riskGenotypes: ["TT"], magnitude: 1,
    effect: "La version concernée modifie l'équilibre entre les formes stockée et active de l'hormone thyroïdienne.",
    summary: "Ce gène participe à la production de l'hormone thyroïdienne active dans le foie et les reins. Son effet seul reste modéré.",
    source: "https://www.snpedia.com/index.php/Rs11206244" },
  { rsid: "rs4644", category: "hormones", trait: "Galectin-3 — fibrose cardiaque", riskGenotypes: ["CC"], magnitude: 1,
    effect: "C augmente la fibrose myocardique.",
    summary: "Marqueur d'insuffisance cardiaque débutante.",
    source: "https://www.snpedia.com/index.php/Rs4644" },
  { rsid: "rs10046", category: "hormones", trait: "CYP19A1 — œstradiol post-ménop.", riskGenotypes: [], magnitude: 1,
    effect: "Influe sur la quantité d'œstrogène fabriquée par l'organisme, surtout chez la femme après la ménopause et chez l'homme.",
    summary: "Ce gène commande l'enzyme qui transforme les androgènes en œstrogène ; il aide à comprendre la réponse aux médicaments anti-aromatase utilisés dans certains cancers du sein. À discuter avec un médecin, sans valeur de risque en soi.",
    source: "https://www.snpedia.com/index.php/Rs10046" },

  // ============================ IMMUNITY (8) ============================
  { rsid: "rs7574865", category: "immunity", trait: "STAT4 — auto-immunité", riskGenotypes: ["TT"], magnitude: 1,
    effect: "La version à risque emballe légèrement certaines réponses immunitaires.",
    summary: "Elle est associée à un risque un peu plus élevé de lupus et de polyarthrite rhumatoïde. Cela reste un facteur parmi d'autres ; en parler en cas d'antécédents familiaux.",
    source: "https://www.snpedia.com/index.php/Rs7574865" },
  { rsid: "rs2476601", category: "immunity", trait: "PTPN22 — auto-immunité multi-systémique", riskGenotypes: ["AA", "AG"], magnitude: 3,
    effect: "La version à risque déréagle un frein naturel des globules blancs, qui attaquent alors plus facilement les tissus du corps.",
    summary: "C'est l'un des facteurs génétiques les plus larges d'auto-immunité chez les Européens (diabète de type 1, lupus, polyarthrite, vitiligo, thyroïdite). Une surveillance médicale est utile en cas de signes évocateurs.",
    source: "https://www.snpedia.com/index.php/Rs2476601" },
  { rsid: "rs11209026", category: "immunity", trait: "IL23R — protection digestive/cutanée", riskGenotypes: [], protectiveGenotypes: ["AA", "AG"], magnitude: 2,
    effect: "La version rare A protège contre certaines maladies inflammatoires de l'intestin et de la peau (Crohn, rectocolite, psoriasis).",
    summary: "C'est une version protectrice et rare. Ne pas l'avoir est simplement la norme, ce n'est pas un risque.",
    source: "https://www.snpedia.com/index.php/Rs11209026" },
  { rsid: "rs2066844", category: "immunity", trait: "NOD2 R702W — Crohn", riskGenotypes: ["TT", "CT"], magnitude: 2,
    effect: "La version à risque rend la paroi de l'intestin moins capable de détecter certaines bactéries.",
    summary: "Elle augmente le risque de maladie de Crohn, surtout si on porte aussi d'autres versions à risque du même gène. Utile à mentionner en cas de troubles digestifs chroniques.",
    source: "https://www.snpedia.com/index.php/Rs2066844" },
  { rsid: "rs2066845", category: "immunity", trait: "NOD2 G908R — Crohn", riskGenotypes: ["CC", "CG"], magnitude: 2,
    effect: "La version à risque gêne la reconnaissance des bactéries par la paroi intestinale.",
    summary: "Deuxième version importante de ce gène liée à la maladie de Crohn ; l'effet s'additionne si on porte plusieurs versions à risque. À signaler en cas de symptômes digestifs persistants.",
    source: "https://www.snpedia.com/index.php/Rs2066845" },
  { rsid: "rs2104286", category: "immunity", trait: "IL2RA — sclérose en plaques", riskGenotypes: ["AA"], magnitude: 1,
    effect: "La version AA est associée à un risque un peu plus élevé de sclérose en plaques.",
    summary: "Variant bien établi touchant le récepteur de l'interleukine-2 et la régulation immunitaire. L'effet individuel reste modeste.",
    source: "https://www.snpedia.com/index.php/Rs2104286" },
  { rsid: "rs3129889", category: "immunity", trait: "HLA-DRB1*15:01 — SEP", riskGenotypes: ["AG", "GG"], magnitude: 3,
    effect: "La version à risque accompagne un type immunitaire qui rend la sclérose en plaques plus probable.",
    summary: "Elle signale le principal facteur génétique connu de la sclérose en plaques, avec un risque environ trois fois plus élevé. Cela reste une prédisposition, pas une certitude de développer la maladie.",
    source: "https://www.snpedia.com/index.php/Rs3129889" },
  { rsid: "rs6457617", category: "immunity", trait: "HLA-DQB1 — auto-immunité", riskGenotypes: ["TT"], magnitude: 1,
    effect: "La version TT est associée à un risque accru de maladies auto-immunes.",
    summary: "Ce marqueur signale une région clef du système immunitaire (HLA de classe II) liée à la polyarthrite, au diabète de type 1 et à la narcolepsie.",
    source: "https://www.snpedia.com/index.php/Rs6457617" },

  // ============================ DETOX / PHARMACOGENOMICS (15) ============================
  { rsid: "rs1799853", category: "detox", trait: "CYP2C9*2 — warfarine/AINS", riskGenotypes: ["TT", "CT"], magnitude: 2,
    effect: "La version à risque ralentit l'élimination de certains médicaments par le foie.",
    summary: "Elle peut faire monter les concentrations d'anticoagulants (warfarine), d'anti-inflammatoires et de certains antihypertenseurs : des doses plus faibles sont parfois nécessaires. Information à transmettre au médecin ou au pharmacien avant un traitement.",
    source: "https://www.snpedia.com/index.php/Rs1799853" },
  { rsid: "rs1057910", category: "detox", trait: "CYP2C9*3 — warfarine très lente", riskGenotypes: ["AC", "CC"], magnitude: 3,
    effect: "La version à risque ralentit fortement l'élimination de certains médicaments par le foie.",
    summary: "Avec elle, la warfarine s'élimine très lentement et la dose doit souvent être nettement réduite. Un ajustement médical attentif est important si un tel traitement est prescrit.",
    source: "https://www.snpedia.com/index.php/Rs1057910" },
  { rsid: "rs9923231", category: "detox", trait: "VKORC1 — sensibilité warfarine", riskGenotypes: ["TT"], magnitude: 3,
    effect: "La version à risque rend l'organisme très sensible à la warfarine.",
    summary: "Avec elle, une faible dose de warfarine suffit, et une dose habituelle expose à un sur-dosage. À signaler impérativement avant de démarrer ce type d'anticoagulant.",
    source: "https://www.snpedia.com/index.php/Rs9923231" },
  { rsid: "rs4244285", category: "detox", trait: "CYP2C19*2 — clopidogrel", riskGenotypes: ["AA", "AG"], magnitude: 3,
    effect: "La version à risque empêche d'activer correctement le clopidogrel (Plavix).",
    summary: "Le médicament reste peu efficace, ce qui expose à un risque de caillot, notamment après la pose d'un stent. Dans ce cas, le médecin préfère souvent un autre antiagrégant.",
    source: "https://www.snpedia.com/index.php/Rs4244285" },
  { rsid: "rs12248560", category: "detox", trait: "CYP2C19*17 — métaboliseur ultra-rapide", riskGenotypes: ["TT", "CT"], magnitude: 2,
    effect: "La version à risque accélère l'élimination de certains médicaments par le foie.",
    summary: "Elle peut rendre les anti-acides (oméprazole) moins efficaces et modifier la réponse à certains antidépresseurs ou anticoagulants. Information utile au médecin pour ajuster un traitement.",
    source: "https://www.snpedia.com/index.php/Rs12248560" },
  { rsid: "rs3892097", category: "detox", trait: "CYP2D6*4 — antidépresseurs / opioïdes", riskGenotypes: ["AA"], magnitude: 3,
    effect: "La version à risque rend inactive une enzyme clé du foie quand on en a deux copies.",
    summary: "La codéine devient inefficace contre la douleur et certains antidépresseurs peuvent s'accumuler. Un avis pharmacologique est conseillé avant ces traitements.",
    source: "https://www.snpedia.com/index.php/Rs3892097" },
  { rsid: "rs1801272", category: "detox", trait: "CYP2A6 — nicotine, coumarines", riskGenotypes: ["AA"], magnitude: 1,
    effect: "La version à risque ralentit la dégradation de la nicotine par l'organisme.",
    summary: "Elle tend à réduire la dépendance au tabac et peut faciliter l'arrêt. Information surtout utile pour adapter une aide au sevrage.",
    source: "https://www.snpedia.com/index.php/Rs1801272" },
  { rsid: "rs2231142", category: "detox", trait: "ABCG2 — urate / médicaments", riskGenotypes: ["TT", "GT"], magnitude: 2,
    effect: "La version à risque évacue moins bien l'acide urique et certains médicaments.",
    summary: "Elle augmente le risque de goutte et peut modifier l'effet de médicaments comme certaines statines ou antiviraux. Surveiller l'acide urique et l'alimentation en cas de crises.",
    source: "https://www.snpedia.com/index.php/Rs2231142" },
  { rsid: "rs1045642", category: "detox", trait: "ABCB1 (MDR1) — biodisponibilité médicaments", riskGenotypes: ["TT"], magnitude: 1,
    effect: "La version à risque modifie une pompe qui régule le passage de nombreux médicaments dans l'organisme.",
    summary: "Elle peut changer la quantité de médicament réellement absorbée (digoxine, ciclosporine, certains antiépileptiques et antiviraux). Élément à prendre en compte lors d'ajustements de dose.",
    source: "https://www.snpedia.com/index.php/Rs1045642" },
  { rsid: "rs4880", category: "detox", trait: "SOD2 — défense antioxydante", riskGenotypes: ["TT"], magnitude: 2,
    effect: "La version TT rend l'enzyme antioxydante mitochondriale moins active.",
    summary: "Cette enzyme protège les cellules du stress oxydatif. Une activité réduite peut justifier un soin particulier aux apports antioxydants.",
    source: "https://www.snpedia.com/index.php/Rs4880" },
  { rsid: "rs1800566", category: "detox", trait: "NQO1 — détoxification quinones", riskGenotypes: ["TT"], magnitude: 2,
    effect: "La version à risque rend moins efficace une enzyme qui neutralise certaines substances toxiques.",
    summary: "Elle diminue la capacité à détoxifier des composés de la fumée, de la pollution et de certaines chimiothérapies. Limiter l'exposition au tabac et aux polluants est d'autant plus utile.",
    source: "https://www.snpedia.com/index.php/Rs1800566" },
  { rsid: "rs1695", category: "detox", trait: "GSTP1 Ile105Val — glutathion S-transférase", riskGenotypes: ["GG"], magnitude: 2,
    effect: "La version Val rend l'enzyme de détoxification GSTP1 moins efficace pour neutraliser certains toxiques et médicaments.",
    summary: "Pertinent face aux polluants et à certaines chimiothérapies. Aucune action spécifique au quotidien, surtout informatif pour le suivi médical.",
    source: "https://www.snpedia.com/index.php/Rs1695" },
  { rsid: "rs1799930", category: "detox", trait: "NAT2 — acétylation lente", riskGenotypes: ["AA"], magnitude: 2,
    effect: "Cette version ralentit l'élimination de certaines substances par le foie (acétylation lente).",
    summary: "Peut augmenter la sensibilité à quelques médicaments (comme l'isoniazide) et aux composés des viandes grillées ou de la fumée. Utile à signaler à un médecin avant certains traitements.",
    source: "https://www.snpedia.com/index.php/Rs1799930" },
  { rsid: "rs10509681", category: "detox", trait: "CYP2C8 — paclitaxel / repaglinide", riskGenotypes: ["CC"], magnitude: 1,
    effect: "Cette version modifie l'activité d'une enzyme du foie qui transforme certains médicaments (anticancéreux, antidiabétiques).",
    summary: "Surtout pertinent en cas de traitement par paclitaxel ou répaglinide, où la dose peut devoir être ajustée. À mentionner à l'oncologue ou au médecin prescripteur.",
    source: "https://www.snpedia.com/index.php/Rs10509681" },
  { rsid: "rs2032582", category: "detox", trait: "ABCB1 G2677T — efflux médicaments", riskGenotypes: ["TT"], magnitude: 1,
    effect: "T = activité P-gp réduite.",
    summary: "Variant complémentaire à rs1045642.",
    source: "https://www.snpedia.com/index.php/Rs2032582" },

  // ============================ CARRIERS (5) ============================
  { rsid: "rs334", category: "carriers", trait: "HBB — drépanocytose (sickle cell)", riskGenotypes: ["AT", "TT"], magnitude: 4,
    effect: "L'allèle T est la mutation drépanocytaire: AT correspond au porteur, TT à la maladie.",
    summary: "Maladie héréditaire récessive. Un conseil génétique est utile si le ou la partenaire est aussi porteur.",
    source: "https://www.snpedia.com/index.php/Rs334" },
  { rsid: "rs28940279", category: "carriers", trait: "PAH — phénylcétonurie", riskGenotypes: ["AC", "CC"], magnitude: 4,
    effect: "Mutation PKU (allèle C). AA = non porteur ; AC = porteur asymptomatique ; CC = atteint.",
    summary: "Allèle ancestral A (non porteur). Dépisté à la naissance ; pertinent pour le planning familial si porteur.",
    source: "https://www.snpedia.com/index.php/Rs28940279" },
  { rsid: "rs113993960", category: "carriers", trait: "CFTR ΔF508 — mucoviscidose", riskGenotypes: [], magnitude: 4,
    effect: "Il s'agit de la principale mutation responsable de la mucoviscidose (délétion dans le gène CFTR).",
    summary: "Environ 1 Européen sur 25 en est porteur sain. En cas de projet d'enfant, un conseil génétique est conseillé. Cette mutation n'est pas toujours détectée par les tests grand public.",
    source: "https://www.snpedia.com/index.php/Rs113993960" },
  { rsid: "rs80357906", category: "carriers", trait: "BRCA1 — cancer sein/ovaire", riskGenotypes: [], magnitude: 4,
    effect: "Certaines mutations du gène BRCA1 augmentent fortement le risque de cancer du sein et de l'ovaire.",
    summary: "Les tests grand public ne couvrent que quelques mutations et ne remplacent pas un dépistage complet. En cas d'antécédents familiaux, consulter un service d'oncogénétique.",
    source: "https://www.snpedia.com/index.php/BRCA1" },
  { rsid: "rs80359550", category: "carriers", trait: "BRCA2 — cancer sein/ovaire/prostate", riskGenotypes: [], magnitude: 4,
    effect: "Certaines mutations du gène BRCA2 augmentent le risque de cancer du sein, de l'ovaire et de la prostate.",
    summary: "Concerne aussi les hommes (prostate). Les tests grand public sont partiels ; en cas d'antécédents familiaux, un avis spécialisé est recommandé.",
    source: "https://www.snpedia.com/index.php/BRCA2" },
];

export function evaluate(catalog: CatalogEntry, userGenotype: string): { hasRisk: boolean; isProtective: boolean; userGenotype: string } {
  if (!userGenotype || userGenotype.length < 2) return { hasRisk: false, isProtective: false, userGenotype };
  const sorted = userGenotype.split("").sort().join("");
  const sortedRisk = catalog.riskGenotypes.map((g) => g.split("").sort().join(""));
  const sortedProt = (catalog.protectiveGenotypes ?? []).map((g) => g.split("").sort().join(""));
  return { hasRisk: sortedRisk.includes(sorted), isProtective: sortedProt.includes(sorted), userGenotype };
}

// Compound trait calculator: APOE genotype derived from rs429358 + rs7412
export function apoeGenotype(g429358: string | null, g7412: string | null): string {
  if (!g429358 || !g7412) return "unknown";
  const k = `${g429358}/${g7412}`;
  // C at 429358 = ε4, T at 429358 = ε2/ε3; T at 7412 = ε2, C at 7412 = ε3/ε4
  const map: Record<string, string> = {
    "TT/TT": "ε2/ε2", "CT/TT": "ε2/ε4", "TT/CT": "ε2/ε3",
    "CT/CT": "ε3/ε4", "CT/CC": "ε3/ε4", "CC/CC": "ε4/ε4",
    "TT/CC": "ε3/ε3", "CC/CT": "ε4/ε4", "CC/TT": "(error)",
  };
  return map[k] || "unknown";
}

import { EXTRA_CATALOG } from "./extra-catalog";
CATALOG.push(...EXTRA_CATALOG);
