// 30 additional actionable DNA entries appended to the catalog.
// Sourced from SNPedia / ClinVar / peer-reviewed literature.
import type { CatalogEntry } from "./catalog";

export const EXTRA_CATALOG: CatalogEntry[] = [
  // Longevity / inflammaging
  { rsid: "rs1042725", category: "longevity", trait: "HMGA2 — taille adulte", riskGenotypes: [], magnitude: 1,
    effect: "Cette version influence légèrement la taille adulte.",
    summary: "Une plus petite taille est faiblement associée à une meilleure longévité. Information sans portée médicale directe.",
    source: "https://www.snpedia.com/index.php/Rs1042725" },
  { rsid: "rs1051730", category: "longevity", trait: "CHRNA3 — addiction nicotine", riskGenotypes: ["TT", "CT"], magnitude: 2,
    effect: "Cette version augmente la dépendance à la nicotine et le risque de cancer du poumon chez les fumeurs.",
    summary: "Surtout pertinent en cas de tabagisme actuel ou passé : un suivi pulmonaire et un accompagnement au sevrage sont d'autant plus utiles.",
    source: "https://www.snpedia.com/index.php/Rs1051730" },
  { rsid: "rs1799884", category: "metabolism", trait: "GCK — glycémie à jeun", riskGenotypes: ["TT"], magnitude: 1,
    effect: "Cette version augmente légèrement la glycémie à jeun (de l'ordre de 3 mg/dL).",
    summary: "Effet modeste sur le sucre sanguin à jeun. À garder en tête à l'interprétation d'un bilan glycémique, sans inquiétude particulière.",
    source: "https://www.snpedia.com/index.php/Rs1799884" },
  { rsid: "rs7895340", category: "metabolism", trait: "HHEX — DT2", riskGenotypes: ["AA"], magnitude: 1,
    effect: "Cette version augmente légèrement le risque de diabète de type 2 en réduisant la sécrétion d'insuline.",
    summary: "Effet faible et fréquent dans la population. Une hygiène de vie favorable (alimentation, activité physique) reste la meilleure prévention.",
    source: "https://www.snpedia.com/index.php/Rs7895340" },
  { rsid: "rs2237895", category: "metabolism", trait: "KCNQ1 — DT2 (variant 2)", riskGenotypes: ["CC"], magnitude: 1,
    effect: "Ce profil est associé à un risque de diabète de type 2 un peu plus élevé.",
    summary: "Effet modéré qui s'ajoute aux autres facteurs génétiques. La prévention par le mode de vie reste essentielle.",
    source: "https://www.snpedia.com/index.php/Rs2237895" },
  { rsid: "rs1387153", category: "metabolism", trait: "MTNR1B — risque DT2", riskGenotypes: ["TT"], magnitude: 1,
    effect: "Cette version perturbe le rythme entre mélatonine et insuline, augmentant le risque de diabète de type 2.",
    summary: "Effet modéré sur la régulation du sucre, surtout la nuit. Un sommeil régulier et une bonne hygiène de vie aident à limiter le risque.",
    source: "https://www.snpedia.com/index.php/Rs1387153" },
  // Cardiovascular extension
  { rsid: "rs9818870", category: "cardiovascular", trait: "MRAS — coronaire", riskGenotypes: ["TT"], magnitude: 1,
    effect: "Cette version augmente légèrement le risque de maladie des artères du cœur.",
    summary: "Facteur de risque modeste, à replacer dans le contexte global (tension, cholestérol, mode de vie). Aucune action spécifique en dehors d'un suivi cardiovasculaire usuel.",
    source: "https://www.snpedia.com/index.php/Rs9818870" },
  { rsid: "rs17465637", category: "cardiovascular", trait: "MIA3 — coronaire", riskGenotypes: ["CC"], magnitude: 1,
    effect: "Cette version augmente légèrement le risque de maladie des artères du cœur.",
    summary: "Facteur de risque modeste à interpréter avec les autres paramètres cardiovasculaires. Suivi standard suffisant.",
    source: "https://www.snpedia.com/index.php/Rs17465637" },
  { rsid: "rs1122608", category: "cardiovascular", trait: "LDLR — LDL & coronaire", riskGenotypes: ["GG"], magnitude: 2,
    effect: "La version GG est associée à un cholestérol LDL plus élevé.",
    summary: "Ce marqueur régule le récepteur qui capte le LDL. Un suivi du cholestérol peut être pertinent.",
    source: "https://www.snpedia.com/index.php/Rs1122608" },
  { rsid: "rs646776", category: "cardiovascular", trait: "CELSR2/PSRC1 — LDL", riskGenotypes: ["TT"], magnitude: 2,
    effect: "La version TT est associée à un cholestérol LDL plus élevé.",
    summary: "Région très étudiée du cholestérol qui influence aussi la réponse aux statines.",
    source: "https://www.snpedia.com/index.php/Rs646776" },
  { rsid: "rs7528419", category: "cardiovascular", trait: "SORT1 — IDM", riskGenotypes: ["AA"], magnitude: 2,
    effect: "La version AA va dans le sens d'un cholestérol LDL plus élevé.",
    summary: "Marqueur d'une région clef pour la sécrétion des lipides et le risque cardiovasculaire. Effet à interpréter avec prudence.",
    source: "https://www.snpedia.com/index.php/Rs7528419" },
  // Nutrition expansion
  { rsid: "rs7501331", category: "nutrition", trait: "BCMO1 — conversion β-carotène→rétinol", riskGenotypes: ["TT", "CT"], magnitude: 2,
    effect: "La version T transforme moins bien le bêta-carotène des végétaux en vitamine A active (jusqu'à 30 à 70% de moins).",
    summary: "Si vous portez cette version, comptez moins sur les carottes et légumes oranges pour votre vitamine A et privilégiez des sources animales (foie, jaune d'œuf, huile de foie de poisson).",
    source: "https://www.snpedia.com/index.php/Rs7501331" },
  { rsid: "rs12934922", category: "nutrition", trait: "BCMO1 — conversion bêta-carotène", riskGenotypes: ["TT"], magnitude: 1,
    effect: "La version TT convertit moins bien le bêta-carotène en vitamine A.",
    summary: "Quand la conversion est réduite, les apports en vitamine A déjà formée (et non seulement en bêta-carotène) peuvent être utiles.",
    source: "https://www.snpedia.com/index.php/Rs12934922" },
  { rsid: "rs1535", category: "nutrition", trait: "FADS2 — désaturase oméga-3", riskGenotypes: ["GG"], magnitude: 2,
    effect: "Ce profil réduit fortement la conversion des oméga-3 végétaux en oméga-3 actifs.",
    summary: "Avec cette version, votre corps fabrique peu d'EPA et de DHA à partir des graines ou des noix ; des oméga-3 marins (poisson gras ou huile d'algue) sont plus efficaces.",
    source: "https://www.snpedia.com/index.php/Rs1535" },
  { rsid: "rs4654748", category: "nutrition", trait: "ALPL — vitamine B6", riskGenotypes: ["CC"], magnitude: 1,
    effect: "La version CC est associée à des taux de vitamine B6 plus bas.",
    summary: "Ce marqueur influence la forme active de la vitamine B6 dans le sang.",
    source: "https://www.snpedia.com/index.php/Rs4654748" },
  { rsid: "rs602662", category: "nutrition", trait: "FUT2 — sécréteur ABO + microbiote", riskGenotypes: ["GG"], magnitude: 2,
    effect: "Ce profil correspond au statut non-sécréteur, avec une flore intestinale particulière et une vitamine B12 souvent plus basse.",
    summary: "Le statut sécréteur influence l'écosystème intestinal et l'absorption de certains nutriments. Cette version est liée à un statut non-sécréteur.",
    source: "https://www.snpedia.com/index.php/Rs602662" },
  // Fitness extension
  { rsid: "rs4646994", category: "fitness", trait: "ACE — variant tag (D/I)", riskGenotypes: [], magnitude: 1,
    effect: "Cette version aide à distinguer un profil plutôt orienté endurance d'un profil plutôt orienté puissance.",
    summary: "Indicatif sur votre type d'effort naturel (endurance ou explosivité) ; sans conséquence sur la santé, utile pour orienter l'entraînement.",
    source: "https://www.snpedia.com/index.php/Rs4646994" },
  { rsid: "rs1801253", category: "fitness", trait: "ADRB1 Arg389Gly — réponse cardio", riskGenotypes: ["GG"], magnitude: 1,
    effect: "La version G rend le cœur un peu moins réactif à l'adrénaline.",
    summary: "Cette version peut modifier votre réponse à l'effort et à certains médicaments du cœur (bêta-bloquants) ; à mentionner à votre médecin si un tel traitement est envisagé.",
    source: "https://www.snpedia.com/index.php/Rs1801253" },
  // Cognitive
  { rsid: "rs9939609", category: "cognitive", trait: "FTO — préférences alimentaires", riskGenotypes: ["AA"], magnitude: 1,
    effect: "La version A tend à réduire la sensation de satiété et favorise une prise de poids plus facile.",
    summary: "Avec ce profil, la faim peut être moins bien régulée ; l'effet est en grande partie compensé par une activité physique régulière.",
    source: "https://www.snpedia.com/index.php/Rs9939609_cognition" },
  { rsid: "rs1799971", category: "cognitive", trait: "OPRM1 A118G — opioïdes / récompense", riskGenotypes: ["GG", "AG"], magnitude: 2,
    effect: "La version G modifie la réponse du cerveau aux opioïdes et à la récompense, avec une sensibilité accrue à l'alcool.",
    summary: "Cette version peut diminuer l'efficacité de certains antidouleurs et augmenter le risque de dépendance ; utile à signaler en cas de prescription d'opioïdes.",
    source: "https://www.snpedia.com/index.php/Rs1799971" },
  // Hormones
  { rsid: "rs6932346", category: "hormones", trait: "ESR1 — œstrogène / densité osseuse", riskGenotypes: ["TT"], magnitude: 1,
    effect: "La version TT pourrait être liée à une densité osseuse plus faible.",
    summary: "Marqueur lié au récepteur des oestrogènes et à la santé osseuse. À interpréter avec prudence, surtout après la ménopause.",
    source: "https://www.snpedia.com/index.php/Rs6932346" },
  { rsid: "rs2070951", category: "hormones", trait: "NR3C2 — récepteur minéralocorticoïde", riskGenotypes: ["GG"], magnitude: 1,
    effect: "La version GG pourrait influencer la réponse au stress et au cortisol.",
    summary: "Marqueur du récepteur aux minéralocorticoïdes, possiblement lié à la résilience au stress chronique.",
    source: "https://www.snpedia.com/index.php/Rs2070951" },
  // Detox / Pharmacogenomics
  { rsid: "rs17244841", category: "detox", trait: "HMGCR — réponse statines", riskGenotypes: ["TT"], magnitude: 2,
    effect: "La version T diminue un peu l'efficacité des statines sur le cholestérol (environ 10 à 15% de baisse en moins).",
    summary: "Si votre cholestérol LDL reste élevé malgré une statine et que vous portez cette version, un autre traitement (comme l'ézétimibe) peut être discuté avec votre médecin.",
    source: "https://www.snpedia.com/index.php/Rs17244841" },
  { rsid: "rs4149056", category: "detox", trait: "SLCO1B1 — myopathie statines", riskGenotypes: ["CC", "CT"], magnitude: 3,
    effect: "La version C augmente l'exposition de l'organisme à la simvastatine, ce qui accroît le risque de douleurs musculaires.",
    summary: "Avec cette version, mieux vaut limiter les fortes doses de simvastatine ; signalez-le à votre médecin, qui peut adapter la dose ou choisir une autre statine.",
    source: "https://www.snpedia.com/index.php/Rs4149056" },
  { rsid: "rs2032582", category: "detox", trait: "ABCB1 G2677T — efflux médicaments", riskGenotypes: ["TT"], magnitude: 1,
    effect: "La version T ralentit une pompe qui évacue certains médicaments, ce qui peut en augmenter la concentration dans le corps.",
    summary: "Cette version peut modifier la façon dont vous réagissez à certains médicaments ; information utile pour ajuster un traitement avec votre médecin.",
    source: "https://www.snpedia.com/index.php/Rs2032582" },
  { rsid: "rs2231137", category: "detox", trait: "ABCG2 — urate et antiviraux", riskGenotypes: ["AA"], magnitude: 1,
    effect: "Cette version pourrait influencer le taux d'acide urique.",
    summary: "Marqueur lié à l'élimination de l'acide urique et au risque de goutte. Les données restent partagées.",
    source: "https://www.snpedia.com/index.php/Rs2231137" },
  // Immunity
  { rsid: "rs4988321", category: "immunity", trait: "LRP5 — densité osseuse / IBD",
    riskGenotypes: ["AA"], magnitude: 1,
    effect: "La version A est associée à une densité osseuse plus basse.",
    summary: "Ce profil peut concerner à la fois les os et l'intestin ; un suivi de la santé osseuse est pertinent si d'autres facteurs de risque sont présents.",
    source: "https://www.snpedia.com/index.php/Rs4988321" },
  { rsid: "rs2241880", category: "immunity", trait: "ATG16L1 — Crohn / autophagie", riskGenotypes: ["GG"], magnitude: 2,
    effect: "La version G perturbe un mécanisme de nettoyage des cellules intestinales et augmente le risque de maladie de Crohn.",
    summary: "Facteur de risque connu pour la maladie de Crohn ; il ne suffit pas à lui seul à la déclencher mais mérite attention en cas de symptômes digestifs persistants.",
    source: "https://www.snpedia.com/index.php/Rs2241880" },
  { rsid: "rs3197999", category: "immunity", trait: "MST1 — IBD",
    riskGenotypes: ["AA"], magnitude: 1,
    effect: "La version A est associée à un risque accru de colite ulcéreuse (inflammation chronique du côlon).",
    summary: "Facteur de risque pour les maladies inflammatoires de l'intestin ; à garder en tête en cas de troubles digestifs chroniques.",
    source: "https://www.snpedia.com/index.php/Rs3197999" },
  // Carriers
  { rsid: "rs1801252", category: "hormones", trait: "ADRB1 Ser49Gly — IC chronique", riskGenotypes: ["GG"], magnitude: 1,
    effect: "La version G peut modifier l'évolution d'une insuffisance cardiaque chronique.",
    summary: "Information de pharmacogénomique utile pour ajuster les bêta-bloquants ; à discuter avec un cardiologue en cas d'insuffisance cardiaque.",
    source: "https://www.snpedia.com/index.php/Rs1801252" },
];
