// 30 additional actionable DNA entries appended to the catalog.
// Sourced from SNPedia / ClinVar / peer-reviewed literature.
import type { CatalogEntry } from "./catalog";

export const EXTRA_CATALOG: CatalogEntry[] = [
  // Longevity / inflammaging
  { rsid: "rs1042725", category: "longevity", trait: "HMGA2 — taille adulte", riskGenotypes: [], magnitude: 1,
    effect: "Influence la taille adulte; petite taille corrélée à longévité accrue.",
    summary: "Variant taille classique. Trade-off taille/IGF-1/longévité.",
    source: "https://www.snpedia.com/index.php/Rs1042725" },
  { rsid: "rs1051730", category: "longevity", trait: "CHRNA3 — addiction nicotine", riskGenotypes: ["TT", "CT"], magnitude: 2,
    effect: "Allèle T augmente la dépendance tabagique et le risque cancer du poumon.",
    summary: "Cluster CHRNA3-CHRNA5. Si fumeur ou ex-fumeur, suivi pneumo recommandé.",
    source: "https://www.snpedia.com/index.php/Rs1051730" },
  { rsid: "rs1799884", category: "metabolism", trait: "GCK — glycémie à jeun", riskGenotypes: ["TT"], magnitude: 1,
    effect: "T augmente glycémie à jeun de ~3 mg/dL.",
    summary: "Glucokinase, senseur de glucose hépatique.",
    source: "https://www.snpedia.com/index.php/Rs1799884" },
  { rsid: "rs7895340", category: "metabolism", trait: "HHEX — DT2", riskGenotypes: ["AA"], magnitude: 1,
    effect: "A augmente le risque DT2 via altération sécrétion insuline.",
    summary: "Variant GWAS classique du diabète.",
    source: "https://www.snpedia.com/index.php/Rs7895340" },
  { rsid: "rs2237895", category: "metabolism", trait: "KCNQ1 — DT2 (variant 2)", riskGenotypes: ["CC"], magnitude: 1,
    effect: "C augmente le risque DT2.",
    summary: "Locus KCNQ1, second SNP indépendant.",
    source: "https://www.snpedia.com/index.php/Rs2237895" },
  { rsid: "rs1387153", category: "metabolism", trait: "MTNR1B — risque DT2", riskGenotypes: ["TT"], magnitude: 1,
    effect: "T augmente le risque DT2 via dysrégulation circadienne mélatonine/insuline.",
    summary: "Effet additif avec rs10830963.",
    source: "https://www.snpedia.com/index.php/Rs1387153" },
  // Cardiovascular extension
  { rsid: "rs9818870", category: "cardiovascular", trait: "MRAS — coronaire", riskGenotypes: ["TT"], magnitude: 1,
    effect: "T augmente le risque coronarien.",
    summary: "MRAS = signalisation Ras vasculaire.",
    source: "https://www.snpedia.com/index.php/Rs9818870" },
  { rsid: "rs17465637", category: "cardiovascular", trait: "MIA3 — coronaire", riskGenotypes: ["CC"], magnitude: 1,
    effect: "C augmente le risque coronarien.",
    summary: "MIA3/TANGO1 = stress collagène.",
    source: "https://www.snpedia.com/index.php/Rs17465637" },
  { rsid: "rs1122608", category: "cardiovascular", trait: "LDLR — LDL & coronaire", riskGenotypes: ["GG"], magnitude: 2,
    effect: "G augmente le LDL et le risque coronarien.",
    summary: "Variant régulateur du récepteur LDL.",
    source: "https://www.snpedia.com/index.php/Rs1122608" },
  { rsid: "rs646776", category: "cardiovascular", trait: "CELSR2/PSRC1 — LDL", riskGenotypes: ["TT"], magnitude: 2,
    effect: "T augmente le LDL.",
    summary: "Locus 1p13. Variant pharmacogénomique pour réponse aux statines.",
    source: "https://www.snpedia.com/index.php/Rs646776" },
  { rsid: "rs7528419", category: "cardiovascular", trait: "SORT1 — IDM", riskGenotypes: ["AA"], magnitude: 2,
    effect: "A augmente l'IDM.",
    summary: "Variant phare du locus 1p13 sur la sécrétion VLDL.",
    source: "https://www.snpedia.com/index.php/Rs7528419" },
  // Nutrition expansion
  { rsid: "rs7501331", category: "nutrition", trait: "BCMO1 — conversion β-carotène→rétinol", riskGenotypes: ["TT", "CT"], magnitude: 2,
    effect: "T = conversion β-carotène en vitamine A diminuée 30-70%.",
    summary: "Si carrier T, privilégier rétinol préformé (foie, jaune, fish liver oil) plutôt que carottes.",
    source: "https://www.snpedia.com/index.php/Rs7501331" },
  { rsid: "rs12934922", category: "nutrition", trait: "BCMO1 — variant complémentaire", riskGenotypes: ["AA"], magnitude: 1,
    effect: "Effet additif avec rs7501331 sur la conversion.",
    summary: "Combiner avec rs7501331 pour évaluer le besoin en vit A préformée.",
    source: "https://www.snpedia.com/index.php/Rs12934922" },
  { rsid: "rs1535", category: "nutrition", trait: "FADS2 — désaturase oméga-3", riskGenotypes: ["GG"], magnitude: 2,
    effect: "G = conversion ALA → EPA/DHA réduite.",
    summary: "Avec rs174537, indique besoin EPA/DHA marin direct.",
    source: "https://www.snpedia.com/index.php/Rs1535" },
  { rsid: "rs4654748", category: "nutrition", trait: "ALPL — vit B6 (PLP)", riskGenotypes: ["TT"], magnitude: 1,
    effect: "T = niveaux de pyridoxal phosphate (PLP) plus bas.",
    summary: "Influence la forme active de B6.",
    source: "https://www.snpedia.com/index.php/Rs4654748" },
  { rsid: "rs602662", category: "nutrition", trait: "FUT2 — sécréteur ABO + microbiote", riskGenotypes: ["GG"], magnitude: 2,
    effect: "GG = non-sécréteur, microbiote différent, B12 souvent plus basse.",
    summary: "Effet sur l'écosystème intestinal et l'absorption.",
    source: "https://www.snpedia.com/index.php/Rs602662" },
  // Fitness extension
  { rsid: "rs4646994", category: "fitness", trait: "ACE — variant tag (D/I)", riskGenotypes: [], magnitude: 1,
    effect: "Tag SNP pour ACE I/D, indiqué pour endurance vs puissance.",
    summary: "Allèle I = endurance, D = puissance.",
    source: "https://www.snpedia.com/index.php/Rs4646994" },
  { rsid: "rs1801253", category: "fitness", trait: "ADRB1 Arg389Gly — réponse cardio", riskGenotypes: ["GG"], magnitude: 1,
    effect: "G = réponse adrénergique cardiaque réduite (récepteur β1).",
    summary: "Influence la réponse aux β-bloquants et la réponse exercice.",
    source: "https://www.snpedia.com/index.php/Rs1801253" },
  // Cognitive
  { rsid: "rs9939609", category: "cognitive", trait: "FTO — préférences alimentaires", riskGenotypes: ["AA"], magnitude: 1,
    effect: "Le même variant FTO influence la satiété.",
    summary: "Effet partiellement compensé par exercice physique régulier.",
    source: "https://www.snpedia.com/index.php/Rs9939609_cognition" },
  { rsid: "rs1799971", category: "cognitive", trait: "OPRM1 A118G — opioïdes / récompense", riskGenotypes: ["GG", "AG"], magnitude: 2,
    effect: "G = sensibilité altérée aux opioïdes, dépendance accrue alcool.",
    summary: "Influence réponse aux antidouleurs et risque d'addiction.",
    source: "https://www.snpedia.com/index.php/Rs1799971" },
  // Hormones
  { rsid: "rs6932346", category: "hormones", trait: "ESR1 — œstrogène / densité osseuse", riskGenotypes: ["TT"], magnitude: 1,
    effect: "T = densité osseuse plus basse, risque ostéoporose accru.",
    summary: "Récepteur des œstrogènes. Pertinent post-ménopause + hommes hypogonadiques.",
    source: "https://www.snpedia.com/index.php/Rs6932346" },
  { rsid: "rs2070951", category: "hormones", trait: "NR3C2 — récepteur minéralocorticoïde", riskGenotypes: ["GG"], magnitude: 1,
    effect: "G influence la réponse au stress / cortisol.",
    summary: "Pertinent pour résilience au stress chronique.",
    source: "https://www.snpedia.com/index.php/Rs2070951" },
  // Detox / Pharmacogenomics
  { rsid: "rs17244841", category: "detox", trait: "HMGCR — réponse statines", riskGenotypes: ["TT"], magnitude: 2,
    effect: "T = réponse aux statines réduite (~10-15%).",
    summary: "Si carrier + LDL non maîtrisé sous statine, considérer ezétimibe.",
    source: "https://www.snpedia.com/index.php/Rs17244841" },
  { rsid: "rs4149056", category: "detox", trait: "SLCO1B1 — myopathie statines", riskGenotypes: ["CC", "CT"], magnitude: 3,
    effect: "C augmente l'exposition à la simvastatine → risque myopathie.",
    summary: "FDA recommande de limiter simvastatine 40mg si C carrier.",
    source: "https://www.snpedia.com/index.php/Rs4149056" },
  { rsid: "rs2032582", category: "detox", trait: "ABCB1 G2677T — efflux médicaments", riskGenotypes: ["TT"], magnitude: 1,
    effect: "T = activité P-gp réduite, exposition médicaments augmentée.",
    summary: "Combiné avec rs1045642 pour MDR1.",
    source: "https://www.snpedia.com/index.php/Rs2032582" },
  { rsid: "rs2231137", category: "detox", trait: "ABCG2 — urate et antiviraux", riskGenotypes: ["AA"], magnitude: 1,
    effect: "Compl. de rs2231142 sur ABCG2.",
    summary: "Effet additif sur la goutte.",
    source: "https://www.snpedia.com/index.php/Rs2231137" },
  // Immunity
  { rsid: "rs4988321", category: "immunity", trait: "LRP5 — densité osseuse / IBD",
    riskGenotypes: ["AA"], magnitude: 1,
    effect: "A associé à densité osseuse plus basse.",
    summary: "Wnt signaling. Os + intestin.",
    source: "https://www.snpedia.com/index.php/Rs4988321" },
  { rsid: "rs2241880", category: "immunity", trait: "ATG16L1 — Crohn / autophagie", riskGenotypes: ["GG"], magnitude: 2,
    effect: "G augmente le risque de Crohn.",
    summary: "Autophagie, défense intestinale. Variant clinique majeur.",
    source: "https://www.snpedia.com/index.php/Rs2241880" },
  { rsid: "rs3197999", category: "immunity", trait: "MST1 — IBD",
    riskGenotypes: ["AA"], magnitude: 1,
    effect: "A associé à colite ulcéreuse.",
    summary: "Macrophage stimulating 1.",
    source: "https://www.snpedia.com/index.php/Rs3197999" },
  // Carriers
  { rsid: "rs1801252", category: "hormones", trait: "ADRB1 Ser49Gly — IC chronique", riskGenotypes: ["GG"], magnitude: 1,
    effect: "G = pronostic différent en insuffisance cardiaque chronique.",
    summary: "Pharmacogénomique β-bloquants.",
    source: "https://www.snpedia.com/index.php/Rs1801252" },
];
