/**
 * Static French medical reference databases for autocomplete.
 * Based on Vidal / RCP top prescriptions, INSERM allergen lists, common supplements.
 * Pure data — no runtime deps. Safe to import client-side.
 */

export type Medication = { dci: string; brand?: string[]; class: string };
export type Allergy = { name: string; category: "médicament" | "alimentaire" | "environnemental" | "contact" };
export type Supplement = { name: string; category: string; commonDose?: string };

export const MEDICATIONS_FR: Medication[] = [
  // === Antalgiques / antipyrétiques ===
  { dci: "Paracétamol", brand: ["Doliprane", "Efferalgan", "Dafalgan"], class: "Antalgique" },
  { dci: "Ibuprofène", brand: ["Advil", "Nurofen", "Spedifen"], class: "AINS" },
  { dci: "Kétoprofène", brand: ["Profénid", "Bi-Profénid"], class: "AINS" },
  { dci: "Naproxène", brand: ["Apranax", "Naprosyne"], class: "AINS" },
  { dci: "Diclofénac", brand: ["Voltarène", "Flector"], class: "AINS" },
  { dci: "Célécoxib", brand: ["Celebrex"], class: "AINS COX-2" },
  { dci: "Tramadol", brand: ["Topalgic", "Contramal", "Ixprim"], class: "Antalgique opioïde" },
  { dci: "Codéine", brand: ["Codoliprane", "Klipal"], class: "Antalgique opioïde" },
  { dci: "Morphine", brand: ["Skenan", "Moscontin", "Actiskenan"], class: "Opioïde fort" },
  { dci: "Oxycodone", brand: ["Oxycontin", "Oxynorm"], class: "Opioïde fort" },
  { dci: "Fentanyl", brand: ["Durogesic", "Abstral"], class: "Opioïde fort" },
  { dci: "Néfopam", brand: ["Acupan"], class: "Antalgique non opioïde" },

  // === Statines / lipides ===
  { dci: "Atorvastatine", brand: ["Tahor", "Lipitor"], class: "Statine" },
  { dci: "Rosuvastatine", brand: ["Crestor"], class: "Statine" },
  { dci: "Simvastatine", brand: ["Zocor", "Lodales"], class: "Statine" },
  { dci: "Pravastatine", brand: ["Elisor", "Vasten"], class: "Statine" },
  { dci: "Fluvastatine", brand: ["Lescol", "Fractal"], class: "Statine" },
  { dci: "Ézétimibe", brand: ["Ezetrol", "Inegy"], class: "Hypolipémiant" },
  { dci: "Fénofibrate", brand: ["Lipanthyl"], class: "Fibrate" },

  // === Antihypertenseurs ===
  { dci: "Amlodipine", brand: ["Amlor"], class: "Inhibiteur calcique" },
  { dci: "Nifédipine", brand: ["Adalate"], class: "Inhibiteur calcique" },
  { dci: "Diltiazem", brand: ["Tildiem", "Mono-Tildiem"], class: "Inhibiteur calcique" },
  { dci: "Vérapamil", brand: ["Isoptine"], class: "Inhibiteur calcique" },
  { dci: "Ramipril", brand: ["Triatec"], class: "IEC" },
  { dci: "Périndopril", brand: ["Coversyl", "Bipreterax"], class: "IEC" },
  { dci: "Enalapril", brand: ["Renitec"], class: "IEC" },
  { dci: "Lisinopril", brand: ["Zestril", "Prinivil"], class: "IEC" },
  { dci: "Captopril", brand: ["Lopril"], class: "IEC" },
  { dci: "Losartan", brand: ["Cozaar", "Hyzaar"], class: "ARA II" },
  { dci: "Valsartan", brand: ["Tareg", "Nisis", "Cotareg"], class: "ARA II" },
  { dci: "Irbésartan", brand: ["Aprovel", "CoAprovel"], class: "ARA II" },
  { dci: "Candésartan", brand: ["Atacand", "Kenzen"], class: "ARA II" },
  { dci: "Telmisartan", brand: ["Micardis", "Pritor"], class: "ARA II" },
  { dci: "Bisoprolol", brand: ["Cardensiel", "Detensiel", "Cardiocor"], class: "Bêta-bloquant" },
  { dci: "Aténolol", brand: ["Tenormine"], class: "Bêta-bloquant" },
  { dci: "Métoprolol", brand: ["Lopressor", "Seloken"], class: "Bêta-bloquant" },
  { dci: "Nébivolol", brand: ["Nebilox", "Temerit"], class: "Bêta-bloquant" },
  { dci: "Propranolol", brand: ["Avlocardyl"], class: "Bêta-bloquant" },
  { dci: "Carvédilol", brand: ["Kredex"], class: "Bêta-bloquant" },
  { dci: "Hydrochlorothiazide", brand: ["Esidrex"], class: "Diurétique thiazidique" },
  { dci: "Indapamide", brand: ["Fludex"], class: "Diurétique" },
  { dci: "Furosémide", brand: ["Lasilix"], class: "Diurétique de l'anse" },
  { dci: "Spironolactone", brand: ["Aldactone"], class: "Diurétique épargneur" },
  { dci: "Éplérénone", brand: ["Inspra"], class: "Antialdostérone" },

  // === Antidiabétiques ===
  { dci: "Metformine", brand: ["Glucophage", "Stagid"], class: "Antidiabétique biguanide" },
  { dci: "Gliclazide", brand: ["Diamicron"], class: "Sulfamide hypoglycémiant" },
  { dci: "Glimépiride", brand: ["Amarel"], class: "Sulfamide hypoglycémiant" },
  { dci: "Sitagliptine", brand: ["Januvia", "Janumet"], class: "Gliptine" },
  { dci: "Vildagliptine", brand: ["Galvus", "Eucreas"], class: "Gliptine" },
  { dci: "Empagliflozine", brand: ["Jardiance"], class: "Gliflozine SGLT2" },
  { dci: "Dapagliflozine", brand: ["Forxiga"], class: "Gliflozine SGLT2" },
  { dci: "Liraglutide", brand: ["Victoza", "Saxenda"], class: "Analogue GLP-1" },
  { dci: "Sémaglutide", brand: ["Ozempic", "Rybelsus", "Wegovy"], class: "Analogue GLP-1" },
  { dci: "Dulaglutide", brand: ["Trulicity"], class: "Analogue GLP-1" },
  { dci: "Tirzépatide", brand: ["Mounjaro"], class: "Agoniste GIP/GLP-1" },
  { dci: "Insuline glargine", brand: ["Lantus", "Toujeo", "Abasaglar"], class: "Insuline lente" },
  { dci: "Insuline asparte", brand: ["NovoRapid", "Fiasp"], class: "Insuline rapide" },
  { dci: "Insuline lispro", brand: ["Humalog", "Liprolog"], class: "Insuline rapide" },

  // === Thyroïde ===
  { dci: "Lévothyroxine", brand: ["Lévothyrox", "Thyrofix", "L-Thyroxin", "Tcaps"], class: "Hormone thyroïdienne" },
  { dci: "Liothyronine (T3)", brand: ["Cynomel"], class: "Hormone thyroïdienne" },
  { dci: "Carbimazole", brand: ["Néo-Mercazole"], class: "Antithyroïdien" },

  // === Gastro / IPP / digestif ===
  { dci: "Oméprazole", brand: ["Mopral", "Zoltum"], class: "IPP" },
  { dci: "Esoméprazole", brand: ["Inexium"], class: "IPP" },
  { dci: "Pantoprazole", brand: ["Eupantol", "Inipomp"], class: "IPP" },
  { dci: "Lansoprazole", brand: ["Lanzor", "Ogast"], class: "IPP" },
  { dci: "Rabéprazole", brand: ["Pariet"], class: "IPP" },
  { dci: "Ranitidine", brand: ["Azantac", "Raniplex"], class: "Anti-H2" },
  { dci: "Famotidine", brand: ["Pepdine"], class: "Anti-H2" },
  { dci: "Dompéridone", brand: ["Motilium", "Péridys"], class: "Antiémétique" },
  { dci: "Métoclopramide", brand: ["Primpéran"], class: "Antiémétique" },
  { dci: "Lopéramide", brand: ["Imodium"], class: "Antidiarrhéique" },
  { dci: "Macrogol", brand: ["Forlax", "Movicol", "Transipeg"], class: "Laxatif osmotique" },
  { dci: "Mésalazine", brand: ["Pentasa", "Fivasa"], class: "Anti-inflammatoire intestinal" },

  // === Pneumologie ===
  { dci: "Salbutamol", brand: ["Ventoline", "Airomir"], class: "Bronchodilatateur β2" },
  { dci: "Terbutaline", brand: ["Bricanyl"], class: "Bronchodilatateur β2" },
  { dci: "Salmétérol", brand: ["Serevent", "Seretide"], class: "β2 longue durée" },
  { dci: "Formotérol", brand: ["Foradil", "Symbicort"], class: "β2 longue durée" },
  { dci: "Budésonide", brand: ["Pulmicort", "Symbicort"], class: "Corticoïde inhalé" },
  { dci: "Fluticasone", brand: ["Flixotide", "Seretide"], class: "Corticoïde inhalé" },
  { dci: "Béclométasone", brand: ["Bécotide", "Innovair"], class: "Corticoïde inhalé" },
  { dci: "Tiotropium", brand: ["Spiriva"], class: "Anticholinergique" },
  { dci: "Montélukast", brand: ["Singulair"], class: "Antileucotriène" },

  // === Psychiatrie / neurologie ===
  { dci: "Sertraline", brand: ["Zoloft"], class: "ISRS" },
  { dci: "Escitalopram", brand: ["Seroplex"], class: "ISRS" },
  { dci: "Citalopram", brand: ["Seropram"], class: "ISRS" },
  { dci: "Fluoxétine", brand: ["Prozac"], class: "ISRS" },
  { dci: "Paroxétine", brand: ["Deroxat"], class: "ISRS" },
  { dci: "Fluvoxamine", brand: ["Floxyfral"], class: "ISRS" },
  { dci: "Venlafaxine", brand: ["Effexor"], class: "IRSNa" },
  { dci: "Duloxétine", brand: ["Cymbalta"], class: "IRSNa" },
  { dci: "Mirtazapine", brand: ["Norset"], class: "Antidépresseur tétracyclique" },
  { dci: "Agomélatine", brand: ["Valdoxan"], class: "Antidépresseur mélatoninergique" },
  { dci: "Amitriptyline", brand: ["Laroxyl"], class: "Antidépresseur tricyclique" },
  { dci: "Clomipramine", brand: ["Anafranil"], class: "Antidépresseur tricyclique" },
  { dci: "Bromazépam", brand: ["Lexomil"], class: "Benzodiazépine" },
  { dci: "Alprazolam", brand: ["Xanax"], class: "Benzodiazépine" },
  { dci: "Lorazépam", brand: ["Temesta"], class: "Benzodiazépine" },
  { dci: "Diazépam", brand: ["Valium"], class: "Benzodiazépine" },
  { dci: "Oxazépam", brand: ["Seresta"], class: "Benzodiazépine" },
  { dci: "Clonazépam", brand: ["Rivotril"], class: "Benzodiazépine" },
  { dci: "Zolpidem", brand: ["Stilnox"], class: "Hypnotique Z" },
  { dci: "Zopiclone", brand: ["Imovane"], class: "Hypnotique Z" },
  { dci: "Hydroxyzine", brand: ["Atarax"], class: "Anxiolytique antihistaminique" },
  { dci: "Buspirone", brand: ["Buspar"], class: "Anxiolytique non-BZD" },
  { dci: "Lithium", brand: ["Téralithe"], class: "Thymorégulateur" },
  { dci: "Valproate", brand: ["Dépakine", "Dépamide", "Dépakote"], class: "Antiépileptique / thymorégulateur" },
  { dci: "Lamotrigine", brand: ["Lamictal"], class: "Antiépileptique" },
  { dci: "Lévétiracétam", brand: ["Keppra"], class: "Antiépileptique" },
  { dci: "Prégabaline", brand: ["Lyrica"], class: "Antiépileptique / antalgique" },
  { dci: "Gabapentine", brand: ["Neurontin"], class: "Antiépileptique / antalgique" },
  { dci: "Quétiapine", brand: ["Xeroquel"], class: "Antipsychotique atypique" },
  { dci: "Olanzapine", brand: ["Zyprexa"], class: "Antipsychotique atypique" },
  { dci: "Rispéridone", brand: ["Risperdal"], class: "Antipsychotique atypique" },
  { dci: "Aripiprazole", brand: ["Abilify"], class: "Antipsychotique atypique" },
  { dci: "Halopéridol", brand: ["Haldol"], class: "Antipsychotique typique" },
  { dci: "Méthylphénidate", brand: ["Ritaline", "Concerta", "Quasym", "Medikinet"], class: "Psychostimulant TDAH" },
  { dci: "Lisdexamfétamine", brand: ["Vyvanse"], class: "Psychostimulant TDAH" },
  { dci: "Atomoxétine", brand: ["Strattera"], class: "TDAH non stimulant" },
  { dci: "Donépézil", brand: ["Aricept"], class: "Anti-Alzheimer" },
  { dci: "Mémantine", brand: ["Ebixa"], class: "Anti-Alzheimer" },
  { dci: "Lévodopa + carbidopa", brand: ["Sinemet", "Modopar"], class: "Antiparkinsonien" },
  { dci: "Sumatriptan", brand: ["Imigrane", "Imiject"], class: "Antimigraineux" },
  { dci: "Zolmitriptan", brand: ["Zomig"], class: "Antimigraineux" },

  // === Cardio (anti-thrombotiques) ===
  { dci: "Aspirine faible dose", brand: ["Kardégic", "Aspégic"], class: "Antiagrégant" },
  { dci: "Clopidogrel", brand: ["Plavix"], class: "Antiagrégant" },
  { dci: "Ticagrélor", brand: ["Brilique"], class: "Antiagrégant" },
  { dci: "Prasugrel", brand: ["Efient"], class: "Antiagrégant" },
  { dci: "Warfarine", brand: ["Coumadine"], class: "AVK" },
  { dci: "Fluindione", brand: ["Préviscan"], class: "AVK" },
  { dci: "Acénocoumarol", brand: ["Sintrom", "Mini-Sintrom"], class: "AVK" },
  { dci: "Apixaban", brand: ["Eliquis"], class: "AOD" },
  { dci: "Rivaroxaban", brand: ["Xarelto"], class: "AOD" },
  { dci: "Dabigatran", brand: ["Pradaxa"], class: "AOD" },
  { dci: "Edoxaban", brand: ["Lixiana"], class: "AOD" },
  { dci: "Énoxaparine", brand: ["Lovenox"], class: "HBPM" },
  { dci: "Tinzaparine", brand: ["Innohep"], class: "HBPM" },
  { dci: "Trimétazidine", brand: ["Vastarel"], class: "Antiangineux" },
  { dci: "Ivabradine", brand: ["Procoralan"], class: "Bradycardisant" },
  { dci: "Amiodarone", brand: ["Cordarone"], class: "Antiarythmique" },
  { dci: "Flécaïnide", brand: ["Flécaïne"], class: "Antiarythmique" },
  { dci: "Digoxine", brand: ["Hémigoxine", "Digoxine Nativelle"], class: "Tonicardiaque" },

  // === Immunosuppresseurs / rhumato ===
  { dci: "Méthotrexate", brand: ["Novatrex", "Imeth", "Metoject"], class: "Immunosuppresseur" },
  { dci: "Hydroxychloroquine", brand: ["Plaquenil"], class: "Antipaludique / immunomod." },
  { dci: "Sulfasalazine", brand: ["Salazopyrine"], class: "Antirhumatismal" },
  { dci: "Azathioprine", brand: ["Imurel"], class: "Immunosuppresseur" },
  { dci: "Ciclosporine", brand: ["Néoral", "Sandimmun"], class: "Immunosuppresseur" },
  { dci: "Tacrolimus", brand: ["Prograf", "Advagraf"], class: "Immunosuppresseur" },
  { dci: "Mycophénolate", brand: ["CellCept", "Myfortic"], class: "Immunosuppresseur" },
  { dci: "Adalimumab", brand: ["Humira"], class: "Anti-TNF" },
  { dci: "Étanercept", brand: ["Enbrel"], class: "Anti-TNF" },
  { dci: "Infliximab", brand: ["Remicade"], class: "Anti-TNF" },
  { dci: "Allopurinol", brand: ["Zyloric"], class: "Hypouricémiant" },
  { dci: "Colchicine", brand: ["Colchimax"], class: "Antigoutteux" },

  // === Corticoïdes ===
  { dci: "Prednisolone", brand: ["Solupred"], class: "Corticoïde" },
  { dci: "Prednisone", brand: ["Cortancyl"], class: "Corticoïde" },
  { dci: "Méthylprednisolone", brand: ["Médrol", "Solu-Medrol"], class: "Corticoïde" },
  { dci: "Bétaméthasone", brand: ["Célestène", "Diprostène"], class: "Corticoïde" },
  { dci: "Dexaméthasone", brand: ["Dectancyl", "Soludecadron"], class: "Corticoïde" },
  { dci: "Hydrocortisone", brand: ["Hydrocortisone Roussel"], class: "Corticoïde de substitution" },

  // === Antibiotiques ===
  { dci: "Amoxicilline", brand: ["Clamoxyl"], class: "Pénicilline A" },
  { dci: "Amoxicilline + acide clavulanique", brand: ["Augmentin", "Ciblor"], class: "Pénicilline + IBL" },
  { dci: "Pénicilline V", brand: ["Oracilline"], class: "Pénicilline" },
  { dci: "Pénicilline G", brand: ["Extencilline"], class: "Pénicilline" },
  { dci: "Pristinamycine", brand: ["Pyostacine"], class: "Synergistine" },
  { dci: "Clarithromycine", brand: ["Naxy", "Zeclar"], class: "Macrolide" },
  { dci: "Azithromycine", brand: ["Zithromax", "Ordipha"], class: "Macrolide" },
  { dci: "Roxithromycine", brand: ["Rulid"], class: "Macrolide" },
  { dci: "Spiramycine", brand: ["Rovamycine"], class: "Macrolide" },
  { dci: "Doxycycline", brand: ["Vibramycine", "Tolexine", "Doxypalu"], class: "Cycline" },
  { dci: "Minocycline", brand: ["Minolis", "Mestacine"], class: "Cycline" },
  { dci: "Ciprofloxacine", brand: ["Ciflox"], class: "Fluoroquinolone" },
  { dci: "Lévofloxacine", brand: ["Tavanic"], class: "Fluoroquinolone" },
  { dci: "Ofloxacine", brand: ["Oflocet"], class: "Fluoroquinolone" },
  { dci: "Norfloxacine", brand: ["Noroxine"], class: "Fluoroquinolone" },
  { dci: "Cotrimoxazole", brand: ["Bactrim"], class: "Sulfamide + triméthoprime" },
  { dci: "Métronidazole", brand: ["Flagyl"], class: "Nitro-imidazolé" },
  { dci: "Fosfomycine", brand: ["Monuril", "Uridoz"], class: "Antibiotique urinaire" },
  { dci: "Nitrofurantoïne", brand: ["Furadantine", "Furadoïne"], class: "Antibiotique urinaire" },
  { dci: "Céfixime", brand: ["Oroken"], class: "Céphalosporine 3G" },
  { dci: "Ceftriaxone", brand: ["Rocéphine"], class: "Céphalosporine 3G" },
  { dci: "Cefpodoxime", brand: ["Orelox"], class: "Céphalosporine 3G" },
  { dci: "Clindamycine", brand: ["Dalacine"], class: "Lincosamide" },
  { dci: "Vancomycine", brand: ["Vancocine"], class: "Glycopeptide" },

  // === Antiviraux / antifongiques / antiparasitaires ===
  { dci: "Aciclovir", brand: ["Zovirax"], class: "Antiviral HSV/VZV" },
  { dci: "Valaciclovir", brand: ["Zelitrex"], class: "Antiviral HSV/VZV" },
  { dci: "Oseltamivir", brand: ["Tamiflu"], class: "Antiviral grippe" },
  { dci: "Fluconazole", brand: ["Triflucan"], class: "Antifongique azolé" },
  { dci: "Itraconazole", brand: ["Sporanox"], class: "Antifongique azolé" },
  { dci: "Terbinafine", brand: ["Lamisil"], class: "Antifongique" },
  { dci: "Albendazole", brand: ["Eskazole", "Zentel"], class: "Antiparasitaire" },
  { dci: "Métronidazole", brand: ["Flagyl"], class: "Antiparasitaire" },

  // === Antihistaminiques ===
  { dci: "Cétirizine", brand: ["Zyrtec", "Zyrtecset", "Virlix"], class: "Antihistaminique H1" },
  { dci: "Loratadine", brand: ["Clarityne"], class: "Antihistaminique H1" },
  { dci: "Desloratadine", brand: ["Aerius"], class: "Antihistaminique H1" },
  { dci: "Fexofénadine", brand: ["Telfast"], class: "Antihistaminique H1" },
  { dci: "Lévocétirizine", brand: ["Xyzall"], class: "Antihistaminique H1" },
  { dci: "Ébastine", brand: ["Kestin"], class: "Antihistaminique H1" },
  { dci: "Bilastine", brand: ["Inorial", "Bilaska"], class: "Antihistaminique H1" },

  // === Ophtalmologie ===
  { dci: "Latanoprost", brand: ["Xalatan", "Monoprost"], class: "Antiglaucomateux" },
  { dci: "Timolol", brand: ["Timoptol", "Nyogel"], class: "Antiglaucomateux β-bloquant" },
  { dci: "Brimonidine", brand: ["Alphagan"], class: "Antiglaucomateux α2" },
  { dci: "Dorzolamide", brand: ["Trusopt", "Cosopt"], class: "Antiglaucomateux IAC" },

  // === Dermatologie ===
  { dci: "Isotrétinoïne", brand: ["Roaccutane", "Curacné"], class: "Rétinoïde acné" },
  { dci: "Trétinoïne", brand: ["Retacnyl", "Locacid"], class: "Rétinoïde topique" },
  { dci: "Adapalène", brand: ["Differine", "Epiduo"], class: "Rétinoïde topique" },
  { dci: "Métronidazole topique", brand: ["Rozex", "Rosex"], class: "Antibactérien topique" },

  // === Urologie / sexuel ===
  { dci: "Finastéride", brand: ["Propecia", "Chibro-Proscar"], class: "Inhibiteur 5α-réductase" },
  { dci: "Dutastéride", brand: ["Avodart", "Combodart"], class: "Inhibiteur 5α-réductase" },
  { dci: "Tamsulosine", brand: ["Josir", "Omix", "Mecir"], class: "α-bloquant urologique" },
  { dci: "Sildénafil", brand: ["Viagra", "Revatio"], class: "Inhibiteur PDE5" },
  { dci: "Tadalafil", brand: ["Cialis", "Adcirca"], class: "Inhibiteur PDE5" },
  { dci: "Vardénafil", brand: ["Levitra"], class: "Inhibiteur PDE5" },
  { dci: "Solifénacine", brand: ["Vesicare"], class: "Anticholinergique vésical" },

  // === Hormones / TRT / contraception ===
  { dci: "Testostérone (gel)", brand: ["Androgel", "Testogel", "Tostran"], class: "Androgène" },
  { dci: "Testostérone (injectable)", brand: ["Androtardyl", "Nebido"], class: "Androgène" },
  { dci: "Testostérone (DHT topique)", brand: ["Andractim"], class: "Androgène" },
  { dci: "Œstradiol", brand: ["Oestrodose", "Estreva", "Estrofem"], class: "Œstrogène THM" },
  { dci: "Progestérone", brand: ["Utrogestan", "Estima"], class: "Progestatif" },
  { dci: "Lévonorgestrel", brand: ["Norlevo", "Microval"], class: "Contraceptif progestatif" },
  { dci: "Drospirénone + éthinylœstradiol", brand: ["Jasmine", "Yaz", "Jasminelle"], class: "Pilule combinée" },
  { dci: "Lévonorgestrel + éthinylœstradiol", brand: ["Minidril", "Leeloo", "Adepal"], class: "Pilule combinée" },
  { dci: "Désogestrel", brand: ["Cerazette", "Optimizette"], class: "Pilule progestative" },
  { dci: "DHEA", brand: ["DHEA"], class: "Hormone surrénalienne" },

  // === Oncologie courante (orale) ===
  { dci: "Tamoxifène", brand: ["Nolvadex", "Tamoxifène EG"], class: "SERM" },
  { dci: "Anastrozole", brand: ["Arimidex"], class: "Inhibiteur aromatase" },
  { dci: "Létrozole", brand: ["Femara"], class: "Inhibiteur aromatase" },
  { dci: "Imatinib", brand: ["Glivec"], class: "Inhibiteur tyrosine kinase" },

  // === Divers / vitamines prescription ===
  { dci: "Vitamine D3 (cholécalciférol)", brand: ["Uvedose", "Zymad", "Vitamine D3 BON"], class: "Vitamine" },
  { dci: "Vitamine B12 (cyanocobalamine)", brand: ["Vitamine B12 Delagrange"], class: "Vitamine" },
  { dci: "Acide folique", brand: ["Spéciafoldine"], class: "Vitamine B9" },
  { dci: "Fer (sulfate ferreux)", brand: ["Tardyferon", "Fumafer"], class: "Fer" },
  { dci: "Mélatonine (LP)", brand: ["Circadin", "Slenyto"], class: "Hormone" },
];

export const ALLERGIES_FR: Allergy[] = [
  // === Médicaments ===
  { name: "Pénicilline", category: "médicament" },
  { name: "Amoxicilline", category: "médicament" },
  { name: "Céphalosporines", category: "médicament" },
  { name: "Sulfamides", category: "médicament" },
  { name: "Macrolides", category: "médicament" },
  { name: "Quinolones", category: "médicament" },
  { name: "Aspirine", category: "médicament" },
  { name: "AINS", category: "médicament" },
  { name: "Ibuprofène", category: "médicament" },
  { name: "Paracétamol", category: "médicament" },
  { name: "Codéine", category: "médicament" },
  { name: "Morphine", category: "médicament" },
  { name: "Tramadol", category: "médicament" },
  { name: "Iode (produit de contraste)", category: "médicament" },
  { name: "Anesthésiques locaux (lidocaïne)", category: "médicament" },
  { name: "Curares", category: "médicament" },
  { name: "Héparine", category: "médicament" },
  { name: "Vaccin (œuf)", category: "médicament" },
  // === Alimentaires ===
  { name: "Arachide (cacahuète)", category: "alimentaire" },
  { name: "Fruits à coque (noix)", category: "alimentaire" },
  { name: "Amande", category: "alimentaire" },
  { name: "Noisette", category: "alimentaire" },
  { name: "Noix de cajou", category: "alimentaire" },
  { name: "Pistache", category: "alimentaire" },
  { name: "Lait de vache", category: "alimentaire" },
  { name: "Œuf", category: "alimentaire" },
  { name: "Gluten / Blé", category: "alimentaire" },
  { name: "Soja", category: "alimentaire" },
  { name: "Poisson", category: "alimentaire" },
  { name: "Crustacés", category: "alimentaire" },
  { name: "Mollusques", category: "alimentaire" },
  { name: "Sésame", category: "alimentaire" },
  { name: "Céleri", category: "alimentaire" },
  { name: "Moutarde", category: "alimentaire" },
  { name: "Lupin", category: "alimentaire" },
  { name: "Sulfites", category: "alimentaire" },
  { name: "Fraise", category: "alimentaire" },
  { name: "Kiwi", category: "alimentaire" },
  { name: "Pêche", category: "alimentaire" },
  { name: "Tomate", category: "alimentaire" },
  { name: "Histamine (intolérance)", category: "alimentaire" },
  { name: "Lactose (intolérance)", category: "alimentaire" },
  { name: "FODMAPs", category: "alimentaire" },
  // === Environnementaux ===
  { name: "Pollens (graminées)", category: "environnemental" },
  { name: "Pollens (bouleau)", category: "environnemental" },
  { name: "Pollens (cyprès)", category: "environnemental" },
  { name: "Pollens (ambroisie)", category: "environnemental" },
  { name: "Pollens (olivier)", category: "environnemental" },
  { name: "Acariens", category: "environnemental" },
  { name: "Poils de chat", category: "environnemental" },
  { name: "Poils de chien", category: "environnemental" },
  { name: "Poils de cheval", category: "environnemental" },
  { name: "Plumes / oiseaux", category: "environnemental" },
  { name: "Moisissures (Alternaria)", category: "environnemental" },
  { name: "Moisissures (Aspergillus)", category: "environnemental" },
  { name: "Latex", category: "environnemental" },
  { name: "Venin d'abeille", category: "environnemental" },
  { name: "Venin de guêpe", category: "environnemental" },
  { name: "Venin de frelon", category: "environnemental" },
  { name: "Poussière", category: "environnemental" },
  // === Contact ===
  { name: "Nickel", category: "contact" },
  { name: "Chrome", category: "contact" },
  { name: "Cobalt", category: "contact" },
  { name: "Parfum / fragrance", category: "contact" },
  { name: "Cosmétiques (parabens)", category: "contact" },
  { name: "Conservateurs (MIT/MCI)", category: "contact" },
  { name: "Teintures capillaires (PPD)", category: "contact" },
  { name: "Caoutchouc (thiurames)", category: "contact" },
  { name: "Lanoline", category: "contact" },
  { name: "Formaldéhyde", category: "contact" },
  { name: "Sparadrap / colophane", category: "contact" },
];

export const SUPPLEMENTS_FR: Supplement[] = [
  // === Vitamines ===
  { name: "Vitamine D3", category: "Vitamine", commonDose: "1000-4000 UI" },
  { name: "Vitamine D3 + K2", category: "Vitamine", commonDose: "4000 UI + 100 μg" },
  { name: "Vitamine B12 (méthylcobalamine)", category: "Vitamine", commonDose: "500-1000 μg" },
  { name: "Vitamine B12 (cyanocobalamine)", category: "Vitamine", commonDose: "500 μg" },
  { name: "Vitamine B-complex", category: "Vitamine" },
  { name: "Vitamine B1 (thiamine)", category: "Vitamine" },
  { name: "Vitamine B2 (riboflavine)", category: "Vitamine" },
  { name: "Vitamine B3 (niacinamide)", category: "Vitamine", commonDose: "500 mg" },
  { name: "Vitamine B5 (pantothénate)", category: "Vitamine" },
  { name: "Vitamine B6 (P5P)", category: "Vitamine", commonDose: "25-50 mg" },
  { name: "Vitamine B9 (méthylfolate)", category: "Vitamine", commonDose: "400-800 μg" },
  { name: "Vitamine C", category: "Vitamine", commonDose: "500-1000 mg" },
  { name: "Vitamine C liposomale", category: "Vitamine", commonDose: "1000 mg" },
  { name: "Vitamine E (tocophérols mixtes)", category: "Vitamine", commonDose: "200-400 UI" },
  { name: "Vitamine K2 MK7", category: "Vitamine", commonDose: "100-200 μg" },
  { name: "Vitamine A (rétinol)", category: "Vitamine", commonDose: "3000 UI" },
  { name: "Bêta-carotène", category: "Vitamine" },
  { name: "Choline (citicoline / CDP-choline)", category: "Vitamine", commonDose: "250-500 mg" },
  { name: "Inositol (myo-inositol)", category: "Vitamine", commonDose: "2-4 g" },

  // === Minéraux ===
  { name: "Magnésium bisglycinate", category: "Minéral", commonDose: "300-400 mg" },
  { name: "Magnésium citrate", category: "Minéral", commonDose: "300-400 mg" },
  { name: "Magnésium thréonate", category: "Minéral", commonDose: "1.5-2 g" },
  { name: "Magnésium malate", category: "Minéral", commonDose: "400 mg" },
  { name: "Magnésium taurate", category: "Minéral", commonDose: "300 mg" },
  { name: "Zinc bisglycinate", category: "Minéral", commonDose: "15-25 mg" },
  { name: "Zinc picolinate", category: "Minéral", commonDose: "15-30 mg" },
  { name: "Zinc + cuivre", category: "Minéral" },
  { name: "Sélénium (sélénométhionine)", category: "Minéral", commonDose: "100-200 μg" },
  { name: "Iode (iodure de potassium)", category: "Minéral", commonDose: "150-300 μg" },
  { name: "Fer bisglycinate", category: "Minéral", commonDose: "25-50 mg" },
  { name: "Calcium citrate", category: "Minéral", commonDose: "500-1000 mg" },
  { name: "Bore", category: "Minéral", commonDose: "3-6 mg" },
  { name: "Chrome picolinate", category: "Minéral", commonDose: "200 μg" },
  { name: "Manganèse", category: "Minéral" },
  { name: "Molybdène", category: "Minéral" },
  { name: "Lithium orotate", category: "Minéral", commonDose: "5-20 mg" },
  { name: "Silicium organique", category: "Minéral" },
  { name: "Potassium", category: "Minéral" },

  // === Acides gras / Lipides ===
  { name: "Oméga-3 (huile de poisson EPA/DHA)", category: "Lipide", commonDose: "1-3 g" },
  { name: "Oméga-3 (huile d'algue DHA)", category: "Lipide", commonDose: "500 mg DHA" },
  { name: "Krill oil", category: "Lipide", commonDose: "1-2 g" },
  { name: "Huile de lin", category: "Lipide" },
  { name: "Huile de cameline", category: "Lipide" },
  { name: "MCT oil (C8/C10)", category: "Lipide" },
  { name: "Acide hyaluronique", category: "Lipide" },

  // === Adaptogènes ===
  { name: "Ashwagandha (KSM-66)", category: "Adaptogène", commonDose: "300-600 mg" },
  { name: "Ashwagandha (Sensoril)", category: "Adaptogène", commonDose: "125-250 mg" },
  { name: "Rhodiola Rosea", category: "Adaptogène", commonDose: "200-400 mg" },
  { name: "Ginseng (Panax)", category: "Adaptogène", commonDose: "200-400 mg" },
  { name: "Éleuthérocoque", category: "Adaptogène" },
  { name: "Schisandra", category: "Adaptogène" },
  { name: "Holy Basil (Tulsi)", category: "Adaptogène" },
  { name: "Maca", category: "Adaptogène", commonDose: "1.5-3 g" },

  // === Champignons médicinaux ===
  { name: "Reishi", category: "Champignon", commonDose: "1-2 g" },
  { name: "Cordyceps", category: "Champignon", commonDose: "1-3 g" },
  { name: "Lion's Mane (Hericium)", category: "Champignon", commonDose: "500-1000 mg" },
  { name: "Chaga", category: "Champignon" },
  { name: "Maitake", category: "Champignon" },
  { name: "Shiitaké", category: "Champignon" },
  { name: "Turkey Tail", category: "Champignon" },

  // === Longévité / Biohacking ===
  { name: "NMN (nicotinamide mononucléotide)", category: "Longévité", commonDose: "250-1000 mg" },
  { name: "NR (nicotinamide riboside)", category: "Longévité", commonDose: "250-500 mg" },
  { name: "Resvératrol", category: "Longévité", commonDose: "100-500 mg" },
  { name: "Quercétine", category: "Longévité", commonDose: "500-1000 mg" },
  { name: "Spermidine", category: "Longévité", commonDose: "1-5 mg" },
  { name: "Fisétine", category: "Longévité", commonDose: "100-500 mg" },
  { name: "PQQ", category: "Longévité", commonDose: "10-20 mg" },
  { name: "CoQ10 (ubiquinol)", category: "Longévité", commonDose: "100-200 mg" },
  { name: "CoQ10 (ubiquinone)", category: "Longévité", commonDose: "100-300 mg" },
  { name: "Acide alpha-lipoïque (R-ALA)", category: "Longévité", commonDose: "300-600 mg" },
  { name: "Astaxanthine", category: "Longévité", commonDose: "4-12 mg" },
  { name: "Rapamycine (off-label)", category: "Longévité" },
  { name: "Métformine (off-label)", category: "Longévité" },
  { name: "Sulforaphane (broccoli sprouts)", category: "Longévité" },
  { name: "Curcumine + pipérine", category: "Longévité", commonDose: "500-1000 mg" },

  // === Hormones / stéroïdes naturels ===
  { name: "DHEA", category: "Hormone", commonDose: "25-50 mg" },
  { name: "Mélatonine", category: "Hormone", commonDose: "0.3-3 mg" },
  { name: "Prégnénolone", category: "Hormone", commonDose: "10-50 mg" },
  { name: "Progestérone (crème transdermique)", category: "Hormone" },
  { name: "Tongkat Ali (Eurycoma)", category: "Hormone", commonDose: "200-400 mg" },
  { name: "Tribulus Terrestris", category: "Hormone", commonDose: "500-1500 mg" },
  { name: "Fenugrec (Testofen)", category: "Hormone", commonDose: "600 mg" },

  // === Performance / sport ===
  { name: "Créatine monohydrate", category: "Performance", commonDose: "5 g" },
  { name: "Bêta-alanine", category: "Performance", commonDose: "3-5 g" },
  { name: "L-citrulline", category: "Performance", commonDose: "6-8 g" },
  { name: "L-arginine", category: "Performance", commonDose: "3-6 g" },
  { name: "Whey protein isolate", category: "Performance", commonDose: "20-40 g" },
  { name: "Caséine", category: "Performance" },
  { name: "BCAA", category: "Performance" },
  { name: "EAA (acides aminés essentiels)", category: "Performance" },
  { name: "HMB", category: "Performance" },
  { name: "Bicarbonate de sodium", category: "Performance" },
  { name: "Électrolytes (LMNT)", category: "Performance" },

  // === Cognitif / nootropique ===
  { name: "Alpha-GPC", category: "Nootropique", commonDose: "300-600 mg" },
  { name: "Bacopa Monnieri", category: "Nootropique", commonDose: "300-600 mg" },
  { name: "L-théanine", category: "Nootropique", commonDose: "100-400 mg" },
  { name: "Caféine + L-théanine", category: "Nootropique" },
  { name: "Phosphatidylsérine", category: "Nootropique", commonDose: "100-300 mg" },
  { name: "Gotu Kola", category: "Nootropique" },
  { name: "Ginkgo biloba", category: "Nootropique", commonDose: "120-240 mg" },
  { name: "Méthylène bleu (USP)", category: "Nootropique" },
  { name: "Créatine (cognitif)", category: "Nootropique" },

  // === Anti-inflammatoire / Détox ===
  { name: "Boswellia", category: "Anti-inflammatoire", commonDose: "300-500 mg" },
  { name: "Bromelaïne", category: "Anti-inflammatoire" },
  { name: "MSM", category: "Anti-inflammatoire" },
  { name: "Glucosamine + chondroïtine", category: "Anti-inflammatoire" },
  { name: "Collagène (peptides bio-actifs)", category: "Anti-inflammatoire", commonDose: "10-20 g" },
  { name: "Collagène marin", category: "Anti-inflammatoire" },
  { name: "NAC (N-acétylcystéine)", category: "Détox", commonDose: "600-1200 mg" },
  { name: "Glutathion liposomal", category: "Détox", commonDose: "250-500 mg" },
  { name: "Glycine", category: "Détox", commonDose: "3-5 g" },
  { name: "TUDCA", category: "Détox", commonDose: "250-500 mg" },
  { name: "Chardon-marie (silymarine)", category: "Détox", commonDose: "150-450 mg" },
  { name: "Charbon activé", category: "Détox" },
  { name: "Chlorella", category: "Détox" },
  { name: "Spiruline", category: "Détox" },

  // === Microbiote ===
  { name: "Probiotiques multi-souches", category: "Microbiote" },
  { name: "Saccharomyces boulardii", category: "Microbiote" },
  { name: "Lactobacillus rhamnosus GG", category: "Microbiote" },
  { name: "Bifidobacterium longum", category: "Microbiote" },
  { name: "Lactobacillus reuteri", category: "Microbiote" },
  { name: "Akkermansia muciniphila", category: "Microbiote" },
  { name: "Prébiotiques (FOS/inuline)", category: "Microbiote" },
  { name: "L-glutamine", category: "Microbiote", commonDose: "5-10 g" },
  { name: "Butyrate (post-biotique)", category: "Microbiote" },

  // === Cardio-métabolique ===
  { name: "Berbérine", category: "Cardio-métabolique", commonDose: "500 mg x 2-3" },
  { name: "Berbérine + dihydroberbérine", category: "Cardio-métabolique" },
  { name: "Bergamote (Citrus bergamia)", category: "Cardio-métabolique", commonDose: "500-1000 mg" },
  { name: "Levure de riz rouge", category: "Cardio-métabolique" },
  { name: "Ail noir (extrait)", category: "Cardio-métabolique", commonDose: "600-1200 mg" },
  { name: "Nitrate (jus de betterave)", category: "Cardio-métabolique" },
  { name: "Taurine", category: "Cardio-métabolique", commonDose: "1-3 g" },
  { name: "L-carnitine", category: "Cardio-métabolique", commonDose: "1-3 g" },
  { name: "Acétyl-L-carnitine (ALCAR)", category: "Cardio-métabolique", commonDose: "500-1500 mg" },

  // === Fibres / digestion ===
  { name: "Psyllium blond", category: "Fibre", commonDose: "5-10 g" },
  { name: "Glucomannane", category: "Fibre" },
  { name: "Inuline", category: "Fibre" },
  { name: "Fibres d'acacia", category: "Fibre" },
  { name: "Enzymes digestives", category: "Digestion" },
  { name: "Bétaïne HCl", category: "Digestion" },
  { name: "Gingembre", category: "Digestion" },

  // === Sommeil ===
  { name: "Glycine (sommeil)", category: "Sommeil", commonDose: "3 g avant coucher" },
  { name: "Magnésium glycinate (sommeil)", category: "Sommeil", commonDose: "300-400 mg" },
  { name: "Apigénine", category: "Sommeil", commonDose: "50 mg" },
  { name: "L-tryptophane", category: "Sommeil", commonDose: "500-2000 mg" },
  { name: "5-HTP", category: "Sommeil", commonDose: "100-300 mg" },
  { name: "GABA", category: "Sommeil" },
  { name: "Valériane", category: "Sommeil" },
  { name: "Passiflore", category: "Sommeil" },
  { name: "CBD", category: "Sommeil" },
];
