export const SPECIALTIES: string[] = [
  "Médecin généraliste",
  "Cardiologue",
  "Endocrinologue",
  "Gastro-entérologue",
  "Pneumologue",
  "Néphrologue",
  "Hépatologue",
  "Hématologue",
  "Oncologue",
  "Neurologue",
  "Psychiatre",
  "Psychologue",
  "Psychothérapeute",
  "Coach mental",
  "Dermatologue",
  "Allergologue",
  "Rhumatologue",
  "Orthopédiste",
  "Urologue",
  "Andrologue",
  "Gynécologue",
  "Sexologue",
  "ORL",
  "Ophtalmologue",
  "Dentiste",
  "Stomatologue",
  "Orthodontiste",
  "Chirurgien",
  "Anesthésiste",
  "Radiologue",
  "Nutritionniste",
  "Diététicien",
  "Naturopathe",
  "Médecin fonctionnel",
  "Médecin orthomoléculaire",
  "Kinésithérapeute",
  "Ostéopathe",
  "Chiropracteur",
  "Podologue",
  "Acupuncteur",
  "Hypnothérapeute",
  "Coach sportif",
  "Coach longévité",
  "Génétique médicale",
  "Médecin du sport",
  "Médecin du travail",
];
